### ISSUE TITLE
[BUG] Print does not work in the debugger in the latest versions

### ISSUE THREAD

**Issue by avraam-inside** [microsoft/debugpy#1016]
print in the debugger via pytest DOES NOT WORK in the latest version of the extension

![image](https://user-images.githubusercontent.com/52919010/184640044-e2bc2e00-1ac7-46ab-9253-25ad9711888f.png)

And in the recent version - it works: 

![image](https://user-images.githubusercontent.com/52919010/184598957-0d82e20f-f97e-4ae8-87c5-a3b454ffbf09.png)

This problem has been hanging for several months. Please fix it.

PS: it is impossible to start a bug report via vscode, a screenshot is not inserted there as conveniently as directly in github, please give the opportunity to write bug reports directly through github, outside of the unfinished process in VSCode.

**Comment by fabioz** [comment]
This is expected if you're using pytest because pytest itself captures the output.

See: https://github.com/microsoft/debugpy/issues/899#issuecomment-1095384631 for details for how to deal with that.

p.s.: There's already a related issue to pass `--capture=no` when debugging with pytest: https://github.com/microsoft/vscode-python/issues/19322
