### ISSUE TITLE
shell scripts takes more than 5s in debug mode

### ISSUE THREAD

**Issue by eastonsuo** [microsoft/debugpy#1038]
as you can see in this picture, when open debug mode in notebook, it takes more than 5s to execute shell script 

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/12948621/187603749-3d813ed3-9cda-4bd2-acf7-5b1b54ece3bb.png">

this issue is intruduced in https://github.com/microsoft/debugpy/pull/883

dont know why and maybe I can fix it?
## Environment data

- debugpy version: 1.6.2
- OS and version: MacOS
- Python version (& distribution if applicable, e.g. Anaconda): 3.9
- Using VS Code or Visual Studio: terminal

## Actual behavior

takes 5s more

## Expected  behavior

takes a short time 

## Steps to reproduce:
1. debugpy 1.6.3
2. open debug in notebook 
3. execute a shell script

**Comment by int19h** [comment]
Is there anything specific about the shell script? Does it spawn more Python instances?

**Comment by eastonsuo** [comment]
> Is there anything specific about the shell script? Does it spawn more Python instances?

any shell script can trigger this, such as `!ls` and `!ps aux`, debugpy version 1.6.0 not have this issue

**Comment by fabioz** [comment]
This is fixed in master already (https://github.com/microsoft/debugpy/commit/ea423ae5983c54b0a633dd51f2f7454078fdfa30).

A new release with it still isn't available thought.

**Comment by fabioz** [comment]
Note that it's a 1 line fix, so, you could apply it locally.

i.e.: Run in the debugger:
```
from _pydev_bundle import pydev_monkey
print(pydev_monkey.__file__)
```

Open that file and add the `set_global_debugger(None)` as well as its import as done in https://github.com/microsoft/debugpy/commit/ea423ae5983c54b0a633dd51f2f7454078fdfa30 (you just need the change to `pydev_mokey`, the rest of the fix is just testing).

Note: the tests are done referencing `gevent`, but the failure isn't really related to `gevent`, any fork+exec where the target isn't Python could be affected.
