### ISSUE TITLE
debugpy over ssh question

### ISSUE THREAD

**Issue by ddurham2** [microsoft/debugpy#105]
Recently the ms-python vscode extension began using debugpy over the older ptvsd.  With this, it's using debugpy.launcher rather than the extensions older ptvsd_launcher.py script.

I have a setup with two containers (running in the same pod in a k8s cluster).  One container is running vscode w/ the ms-python extension installed. And the other container is running a python environment and a slew of other libraries that the python code depends on, and has the ptvsd module installed and a copy of ptvsd_launcher.py that comes with the extension.

Note, being in the same pod (but different containers), they share a 127.0.0.1 local interface.

Going further, I had replaced ms-python's ptvsd_launcher.py script with a script which would ssh over to the other pod and execute the real ptvsd_launcher.py script over there and fire up ptvsd which connects back to 127.0.0.1:port for debugging.  Also, there is some necessary environmental setup and tear-down before and after the python debugging session starts and stops.

Long story short.. I did two container setup just so to keep the two containers' system dependencies as separate as possible.

Now, this worked fine, until the change to debugpy, of course.  After some examination of what changed, it appears that it should be a little simpler because debugpy includes its own launcher... which means that while I need to replace the extension's debugpy/launcher/__main__.py script with a script that ssh-es to the other container, the thing I run on the other container is already included as part of the debugpy pip package.  Okay cool.

A little switch-a-roo with the script, and here's the flow now:
```
ms-python launches debugpy/launcher/__main__.py -->
  __main__.py calls os.execv('ssh localhost setup-script ...same-args...') -->
     (on other container)
     setup-script does setup work and then exec's debugpy/launcher/__main__.py <...same-args...> -->
        At this point, the process should begin and allow debugging.
```
A few things to note:
- ssh is configured to pass the DEBUGPY_LAUNCHER_PORT env var.  It gives a specific error message if I don't.
- The i/o path for stdio is preserved from ms-python all the way to the execution of debugpy/launcher/__main__.py on the other container (A print() statement at the beginning of debugpy/__main__py comes through to the console).
- The same version of debugpy is installed on the second container as is currently shipping with the ms-python extension.
- The python code being debugged lives in a shared folder between the two containers so that it's kept in sync.

However, it does not work.  When I start debugging, it launches, everything executes as expected, but the python script script just simply does not run.  I get no stdout from the script being debugged.  No breakpoints will hit.  If I touch a file in /tmp at the very beginning of the script I'm debugging, it simply doesn't get there.  I don't see any errors (where should I see them?).  The debugger simply exits just soon after it appears to be starting.

Also, I can confirm that the debugpy instance process itself is successfully connecting to the DEBUGPY_LAUNCHER_PORT which the ms-python extension is listening on. 

Any thoughts on why this might not be functioning? Or what else I could check.  TIA

----
I gave remote debugging a try... but since it seems to only support connecting to an existing process, I had to try setting up a pre-launch task to start it waiting on the debugger to connect. That sort of worked, but not too well. Plus, there's no hook for disconnect whereby I could kill the process when the user disconnects.  It's just not a good UX.

**Comment by int19h** [comment]
Logs might provide some clues - since this is launch, try setting `"logToFile":true` in the debug config, and then check the directory where the extension is installed for `debugpy*.log`. 

(Alternatively, or if it's attach, set `DEBUGPY_LOG_DIR` to where you want the logs to go - but note that this must be an actual environment variable, not "env" in your config, because the latter is only applied to the debuggee process, not to the adapter & launcher processes.)

**Comment by karthiknadig** [comment]
@ddurham2 This is an interesting setup. Let me see if I understand correctly.  You have two containers, say IDE-container (where the extension is installed) and python-container (where you want to run code you want to debug). You have modified the `python_launcher.py` (on the IDE-container side) to start the ssh session and connect to the python-container. There you launch the your code under the debugger via a starter script.

Here are a few things you can try:
### Option 1:
You could take advantage of the pre-launch task to setup ssh and start debugpy.adapter (in the python-container) instead of the debugpy.launcher, in server mode.
```
 python3 -m debugpy.adapter --help
usage: __main__.py [-h] [--port PORT] [--host HOST]
                   [--access-token ACCESS_TOKEN]
                   [--server-access-token SERVER_ACCESS_TOKEN] [--log-dir DIR]
                   [--log-stderr]

optional arguments:
  -h, --help            show this help message and exit
  --port PORT           start the adapter in debugServer mode on the specified port
  --host HOST           start the adapter in debugServer mode on the specified host
  --log-dir DIR         enable logging and use DIR to save adapter logs
  --log-stderr          enable logging to stderr
```
So you could start debugpy in server mode (in python-container), like:
```
python3 -m debugpy.adapter --host 127.0.0.1 --port 5678
```
This will start the debug adapter in server mode. Now from the extension you can connect to it, and debug adapter will manage the lifetime of the debugger or your code.
```
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "path to my script",
            "console": "internalConsole", // <--- This is likely the only setting that will work with this
            "debugServer": 5678, // <------ this is VS Code's own setting to connect to a debug adapter running at `localhost:5678`.
            "cwd": "~/GIT/issues/demo_apr", // <--- This should be the path to the root in the python-container
            "pythonPath": "/usr/bin/python3" // <---- Path to python in the python-container
        }
```
In this mode, the debug.adapter running in the python-container will start the debugger and handle launching your code. One caveat, the layout of where the code and python is on both sides should match. You may see an error like this:
```
             Couldn't spawn debuggee: [Errno 2] No such file or directory: '~/ide-side-path/demo_apr'

             Command line:['/usr/bin/python3', '/usr/local/lib/python3.5/dist-packages/debugpy', '--connect', '63598', '--adapter-access-token', '8496967c2e40fafee6355cb9ede568d251d4092e3b261fbbd24a9ef33765f2cf', '~/GIT/issues/demo_apr/somecode.py']
```
Few issues with this:
* Both sides the project layout should match, and python should match.
* Between starting the adapter and connecting to it you might need some delay.

### Option 2:
Note that the debugger supports connecting from either direction. 
#### Listen mode: 
this is where debugpy acts like a server and waits for connection from a client. I this case it would be VS Code.
```
python3 -m debugpy --listen 127.0.0.1:5678 --wait-for-client ./myscript.py
```

#### Connect mode: 
this is where debugpy acts like a client and connects to the IDE.
```
python3 -m debugpy --connect 127.0.0.1:5678 ./myscript.py
```
To use connect mode you will need to use a slightly different configuration. We added this to support container scenarios, since it is not easy to know how long it takes for the container to be ready.
the configuration you would use would look like this:
```js
{
            "name": "Listen",
            "type": "python",
            "request": "attach",
            "listen": {
                "host": "127.0.0.1",
                "port": 5678
            },
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ]
        },
```
Here you could have a pre-launch task that starts the python-container and runs your set up. And the debugger connects back when it is ready. And a postDebugTask, to kill debugpy after the session ends.

Few issues with this mode:
* This will behave as attach, so when you disconnect, it will not kill the debuggee. You will need a post debug task.

Both options are not ideal for your setup. But, do try it and let me know if either of them gets you closer to what you had before. I am assuming Option 2 will work better, and likely adding a "terminate on disconnect" switch might help here.

**Comment by ddurham2** [comment]
Okay!  Thanks for the info.  So the logging helped...

Long story, short, apparently the arguments passed to the debugpy.launcher are ignored and irrelevant.  Only the port env var is important.  It is apparently connecting to the server, and being told what to execute.  This was confusing, because the ms-python extension is running the debugpy.launcher with the script it needs to debug based on what's in the launch.json file.  But that information is communicated again later over the TCP connection.

That is unfortunate, because in my launch.json file I set program to a configuration file (a file included in the source tree being debugged), and I rewrite the arguments to the launcher with the a "boostrapping" .py file I want it to run followed by that configuration file.. which ultimately does execute the file being edited in the IDE.

So.. this whole time, the debugger is trying to execute my configuration file rather than the .py file I add to the launcher command line.  The logging made this apparent.

Well, I can live with this, but it seems like the extension no longer needs to pass any args... Or perhaps the debugpy.launcher's args should be honored, if given, instead of what the server says to execute.

Also, I tried, but it doesn't appear that I should run debugpy directly telling it to --connect 127.0.0.1:<DEBUGPY_LAUNCHER_PORT>,  correct?

Before I close this... do you see anyway to override the script that debugpy ultimate debugs rather than it being told over its connection to DEBUGPY_LAUNCHER_PORT?

Thanks

**Comment by ddurham2** [comment]
Well.. I think I managed to do it via a monkey patch.  In my script that does the setup/teardown I just import the debugpy.launcher.debuggee and wrap spawn() within my own method and insert the boostrap .py file into cmdline where it needs to go.  

Just a little cleanup and I should be good to go.  Thanks!

BTW- I'm all open to making a PR for a more standard feature if you thought it helpful in any other situations. Let me know.

**Comment by int19h** [comment]
Ahh, yes, that would do it :)

The reason why the arguments to the launcher are there but ignored is kinda funny. The launcher needs a bunch of things from debug config JSON, and passing them on command line clutters it a with lot of data that's irrelevant to the user (if you've seen how ptvsd 4 looks when using "integratedTerminal", you probably know what I mean!). And then again we already had a backchannel for the launcher to send "output" events, and handle process lifetime requests like "terminate". So it was easier to just pass it there. 

But then the command line for the launcher didn't have anything other than the port number. If you run different scripts repeatedly, and then look at terminal logs, you can't see which run was which. And so we started passing the target script and its arguments to the launcher, purely so that they are logged in the terminal, and you can see what you were actually running.

So that's why it is the way it is. The good news for you is that we'll have to deal with arguments differently in order to fix https://github.com/microsoft/debugpy/issues/86. It won't change the overall arrangement - it just means that launcher should ignore "args" in the JSON that it receives over the socket, and parse its sys.argv instead. Which would also solve your problem.

**Comment by int19h** [comment]
Couple things related to the scenario overall.

If I understand correctly, the whole point here is to basically make F5 (launch) work transparently over SSH. We have discussed this before a few times, but never had a specific ask for it. I think it's worth filing this as a separate enhancement issue, and we can discuss how this can be done best there, keeping in mind that some things might be easier to do on client side, since we can also change the extension.

Now, as an implementation detail for your particular implementation, you're also effectively rewriting the startup script name and adding some arguments (or maybe environment variables) in the configuration, right? That is actually a good example of something that *is* [easier to do in VSCode](https://code.visualstudio.com/api/references/vscode-api#DebugConfigurationProvider).

**Comment by ddurham2** [comment]
Ah cool.  That's be pretty sweet if it could directly ssh and run something. There's some possibly unsafe assumptions that'd have to be made .. like that debugpy, of compatible version is in place as well as having an exactly synchronized source tree (as has been pointed out) on the other side.   I suppose the shell process executed by the ssh process could do some of this validation.. but then you have venvs and whatnot.  (I've once saw a clever script which executed a single-file python scripts remotely but which exist locally just by executing the python interpreter remotely, but piping in the python script as stdin.  Works when there are no unusual dependencies.)

In my case, I'm controlling the two containers' environments, so those assumptions are safe.

But if it could be solved, that'd be pretty sweet.  When I made an attempt to use attach, I tried having  the ssh's script fire up the a pythong script which waited on a debugger to attach, and then used exec() to run the target script. 

---

As for my setup, I just didn't want the launch.json file (checked into version control in a number of projects) to have to have details about how this whole debugging-over-ssh worked nor any details about the bootstrap code I need to run ahead of the real script.  In case those details changed, I didn't want to require a change to all the projects in version control.

So to make my situation clear, let's say in the IDE (which is vscode running in a container) you have foo.py and hit F5.  Before foo.py runs (on the neighboring container where the actual runtime is set up that allows foo.py to do its thing), bar.py needs to actually be executed (under the debugger is fine) which does its setup junk and then imports foo.py (using importlib), executing it.  I know that's unusual, but it seems to work just fine and magically hits breakpoints in foo.py.

And, to make things more interesting, what the ssh command does is execute yet a more parent python script that does a few things then, monkey patches debuggee.spawn before invoking the real debugpy/launcher/__main__.py script (like this:  exec(open(debugpy.launcher.__path__[0] + "/__main__.py").read())
 ) ... which then debugs bar.py and on to foo.py

Maybe that wasn't more clear... how about this picture
```
F5-in-IDE --fork/execv--> debugpy/launcher/__main__.py --execv--> ssh-to-localhost --> monkeypatch-and-start-debugpy.py --> exec(open(launcher/__main__.py).read()) --> bar.py --> foo.py
```

**Comment by int19h** [comment]
For your scenario involving custom tasks, I wonder if "preLaunchTask" might be able to help here. This would mean that foo.py and bar.py run under two different processes, though.  

DebugConfigurationProvider lets you alter the actual JS object for the config after it has been parsed from launch.json - and also works in cases where somebody starts the debug session programmatically with a dynamically generated config (e.g. if you click "Debug Test" in a Python file).

And since it can also inspect the original config, this allows you to add some high-level properties specific to your scenario, and then generate derived properties like "args" that debug adapter will see. The only trick is figuring out which configs should be touched - the usual trick is to use a custom "request", and rewrite that into "launch" or "attach" after you're done with other properties. You can also do this with "type" (and rewrite it into "python" after).

The biggest benefit, I guess, is that this is a supported extensibility point, so it won't randomly break for you. For debugpy, we are going to maintain protocol and debug config stability going forward - anything that is not deprecated at the point we ship 1.0.0 stable, basically. But the adapter and the launcher are two tightly coupled components - indeed, launcher is adapter's implementation detail. I don't anticipate significant changes here after we fix the argv problem... but if some bug comes up that's easier to fix by changing the details of that interaction, we'll go down that route rather than ensuring that launcher is invoked in a compatible way.

**Comment by int19h** [comment]
And yeah, for SSH remoting, the idea was to do all the initial setup through the same SSH connection -  if there's Python on the other end, we can stream the bootstrap script as you describe, but that script can e.g. be a self-extracting Python archive, containing the entire debugpy. So, ideally, all you need is a machine with Python and SSH, and everything else "just works".

**Comment by ddurham2** [comment]
For ssh, nice plan.  Can't wait! :)

Okay, it might might some sense to use a DebugConfigurationProvider.  I think that could insert the setup script just fine, and I should, obviously, no longer need the "more parent" script to do the monkey patching (it does a little be of extra setup, but I could probably combine it with the bootstrap script that I asked the debugger to execute).   I will look into that.  Thanks

**Comment by ddurham2** [comment]
I believe this answers all my questions for now.
