### ISSUE TITLE
Is there any way to break the upper limit of the number of watch windows in debug

### ISSUE THREAD

**Issue by ydmykr** [microsoft/debugpy#1056]
At one time, the maximum number of variables was 300. Now it seems that the maximum number of variables has been cancelled, but the watch window still seems to be 300, and I can't find the .py file to modify this setting. Is there a way to modify the upper limit of the watch window's storage variables? (Even though it will take up more of PC memory).

**Comment by judej** [comment]
Is this on VSCode or on Visual Studio?

**Comment by fabioz** [comment]
@ydmykr I think there are some hard-coded things that are in play here.

Can you provide an example (source code and screenshot) where the limit is reached so that we can implement such customization (while being sure we're actually tackling the issue you are seeing)?

**Comment by ydmykr** [comment]
@judej It's vscode

**Comment by ydmykr** [comment]
@fabioz I refer to this [issue](https://stackoverflow.com/a/56330258/18359438). It was also mentioned in the comments that max items to show: 300

**Comment by fabioz** [comment]
Unfortunately this isn't currently customizable.

The workaround is changing the value `MAX_ITEMS_TO_HANDLE = 300` in the actual source code in `_pydevd_bundle/pydevd_resolver.py`.

You can run in the debugger:

```
from _pydevd_bundle import pydevd_resolver
print(pydevd_resolver.__file__)
```

To know where this file is located in your case.

I'll take a look into making that at least customizable.

**Comment by fabioz** [comment]
I'm still working on this item.

The idea will be that instead of simply cutting it in the tree it'll show the plain values up to a number and then it'll add an item such as:

 `more...` 

and then it'll partition it in buckets inside it:

i.e.:
`[100:400]`, `[400:700]` and so on.

I'll make it possible to customize those through environment variables (possibly there'll be a limit to buckets too -- I'll play a bit with the UI to see at which point things start to get slow).

**Comment by ydmykr** [comment]
Thanks for your comment, I will try it! But I still think it would be a better design to set it as a definable option in the editor
