### ISSUE TITLE
PEP657 Column position of raised exceptions

### ISSUE THREAD

**Issue by tonybaloney** [microsoft/debugpy#1099]
In Debugpy, exceptions raised in Python 3.11 are missing the fine-grained position:

For example, in the following code:

```python
d = {
    "x": {
        "y": {
            "z": {
                "theta": 1
            }
        }
    }
}

result = d["x"]["y"]["z"]["beta"]
```

On the CLI I get the position of the KeyError offset in the line underlined using [PEP657](https://peps.python.org/pep-0657/) API:

```command
$ python exploding_kitten.py
...
  File "/Users/anthonyshaw/tmp/exploding_kitten.py", line 11, in <module>
    result = d["x"]["y"]["z"]["beta"]
             ~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'beta'
```

But in VS Code it only highlights the line and not the position of the exception, making it harder to work out where the error came from.

<img width="989" alt="screenshot 2022-10-25 at 13 33 54" src="https://user-images.githubusercontent.com/1532417/197670293-8eec8dca-b6ef-443f-9513-b2512c3a3ee8.png">

Please can PEP657 be implemented in debugpy so that the Stopped event sent back via DAP include the position (start col, end col) of the raised exception.

**Comment by pablogsal** [comment]
Notice that the `traceback` module implements the highlighting if you don't want to make a custom highlighter:

```
import traceback

d = {
    "x": {
        "y": {
            "z": {
                "theta": 1
            }
        }
    }
}

try:
    result = d["x"]["y"]["z"]["beta"]
except Exception as e:
    f = e

print("\n".join(traceback.extract_tb(f.__traceback__).format()))
```

Note: this needs to be executed from a file as source is not displayed in the REPL

**Comment by tonybaloney** [comment]
<img width="920" alt="screenshot 2022-11-04 at 07 56 27" src="https://user-images.githubusercontent.com/1532417/199833282-acae5b0b-a5c9-4bbb-ac67-b30c7b854445.png">
<img width="1097" alt="screenshot 2022-11-04 at 07 56 44" src="https://user-images.githubusercontent.com/1532417/199833297-700fddf7-ad68-4e37-90e3-2fe6b85418bc.png">
Thanks for the update. Is there a way to propagate the col offset through DAP to the stop-point message? That way, the arrow inside the editor will point to the column and not highlight the whole line

**Comment by fabioz** [comment]
It seems that the stack trace from the DAP does indeed have a column. I'll reopen to investigate further.

**Comment by fabioz** [comment]
Getting the actual column where the frame is stopped seems to have a number of intricacies related to it...

@pablogsal I see that there's a way to format the traceback, but following the code it seems there's a lot of internal things to map the bytecode offset to the character (going from bytes -> char, parsing using the ast to find a BinOp or Subscript and then computing anchors based on that...).

I guess I can copy all that code to get the start column for the current pos in a frame or analyze the formatted string looking for `^`, but I was wondering if there was a better API to deal with that somewhere...

**Comment by pablogsal** [comment]
I am not sure I follow... why you need to copy that code when you can just execute it? If you format the trace back with the traceback module, you will get all those things computed for you.

I am clearly missing something here. Could you please explain in detail what is what you are trying to do and why you cannot leverage existing APIs?

**Comment by fabioz** [comment]
I'd like to get the column (because I want to show the executing column in the editor and not just in the traceback string).

**Comment by fabioz** [comment]
@pablogsal the image below shows the use-case (the traceback module does many additional operations to infer the final position during the traceback printing).

![image](https://user-images.githubusercontent.com/117621/199966668-b04ce191-ba52-46e9-9092-f8aad9c85779.png)

**Comment by pablogsal** [comment]
I am afraid you are going to need to explain the problem with more details because I am missing a ton of context here. What **exactly** are you trying to achieve?

Precisely because the traceback module does all these extra things, I am asking you why you cannot just use the APIs provided in the traceback module and just print the traceback?

**Comment by pablogsal** [comment]
If you are just trying to get the column you can just use the co_positions attribute in the code object in combination with the instruction offset from the exception or the frame.

**Comment by pablogsal** [comment]
So basically this:

https://github.com/python/cpython/blob/2844aa6a8eb1d486b5c432f0ed33a2082998f41e/Lib/traceback.py#L367

The instruction index is taken from the frame or the traceback.

Check the PEP for details but basically co_positions return you a generator of 4 tuples representing start and end line numbers and start and end column offsets for every instruction. Once you know the instruction that failed you can get the position easily from there.

Is this what you need ?

**Comment by pablogsal** [comment]
So basically this:

https://github.com/python/cpython/blob/2844aa6a8eb1d486b5c432f0ed33a2082998f41e/Lib/traceback.py#L367

The instruction index is taken from the frame or the traceback.

Check the PEP for details but basically co_positions return you a generator of 4 tuples representing start and end line numbers and start and end column offsets for every instruction. Once you know the instruction that failed you can get the position easily from there.

Is this what you need ?

**Comment by fabioz** [comment]
Humm, ok. The debugger does 2 things:

1. Print the traceback and show it to the user (this works well with the current APIs).
2. Show the line and column where the code is stopped. In this case the debugger needs the actual column where it's stopped.

The debugger is using `co_positions` with the instruction offset from the exception of the frame to get the current columns:

https://github.com/microsoft/debugpy/commit/a2a33283889c989bb840202411bb5e5aae013709#diff-6458f9e28ef139ef8e23d8fff5936d26eebe5ee46a5b095c100f35f6ccc882a3R240

-- that is later on passed on to the `traceback.FrameSummary`

https://github.com/microsoft/debugpy/commit/a2a33283889c989bb840202411bb5e5aae013709#diff-096f2487391f489de3955c8d78e1506c3d655de5267ed8ec9300a321c7882b41R1472

Now, using that column in the example:

```
d = {
    "x": {
        "y": {
            "z": {
                "theta": 1
            }
        }
    }
}

result = d["x"]["y"]["z"]["beta"]
```
Actually provides a column pointing to `= d` (column 9) when the column wanted is `["beta"]`. The endcol seems fine though.

So, after that, to get to the actual start line, the `traceback.FrameSummary` needs to do many additional operations when formatting (because the endcol is correct but the start col is not), so, the mapping ends up mapping that col 9 end col 43 to the following anchor:

```
line: result = d["x"]["y"]["z"]["beta"]
frame_summary.colno 9
frame_summary.end_colno 43
anchors _Anchors(left_end_offset=16, right_start_offset=24, primary_char='~', secondary_char='^')
```

i.e.: it converts from utf-8 to chars (https://github.com/python/cpython/blob/2844aa6a8eb1d486b5c432f0ed33a2082998f41e/Lib/traceback.py#L479) and checks whether it's in a `BinOp` or `Subscript` to get the actual columns (https://github.com/python/cpython/blob/2844aa6a8eb1d486b5c432f0ed33a2082998f41e/Lib/traceback.py#L590).

So, my question is whether this additional processing to compute the anchors based on the actual code is available in an easier to use API.

**Comment by pablogsal** [comment]
> So, my question is whether this additional processing to compute the anchors based on the actual code is available in an easier to use API.

No, and is unlikely that there will be. The anchors are just a way to offer better indications but they are not part of the public API. Indeed, the way we display these anchors and how many of them can and will change between versions of the interpreter. The only public apis are the one's provided by the traceback module and the ones described in the PEP

**Comment by fabioz** [comment]
> But the start column _is_ correct because that instruction is operating over the result of the previous getitems so the span of the instruction starts at "d" and ends at the corresponding dictionary access.

I get that it's semantically correct, but it's the same for all the accesses at that line, so, it's not that helpful (showing the range could be better, but the debug adapter protocol can only show one column not really a range and I think showing only the end column may be a bit strange for users).

> No, and is unlikely that there will be. The anchors are just a way to offer better indications but they are not part of the public API. Indeed, the way we display these anchors and how many of them can and will change between versions of the interpreter. The only public apis are the one's provided by the traceback module and the ones described in the PEP.

Roger that ;)

> Obviously you are welcomed to re implement that based on the co_positions output but copy paste that code is something I would not recommend because the internals can and will change.

Maybe using the end column and just trying to back up based on some word heuristics would be reasonable -- I also have the feeling that the current implementation used on the traceback will change... maybe it'd be interesting to have some API which could provide those anchors even if the anchors themselves change and heuristics get better, but yeah, I get that right now this isn't an option, so, off to doing some other code to handle that ;)

**Comment by pablogsal** [comment]
I will discuss this with other core devs to see if we can consider a better APIs for the future, but as you can imagine a lot of users won't be happy if we allow the API to change between versions. The problem of offering apis in the standard library is that the amount of consumers is really high and every one has different stability requirements, constraints and needs so even if your this use case will be fine, the maintenance cost for us can be unbounded so we need to be very conservative and offer building blocks.

I understand this answer is somewhat disappointing and I apologise but unfortunately we need to ensure the maintenance cost on our side stays controlled because we have seen too many instances of how hard is to change or even fix anything once is exposed as public.

Thanks for your understanding and you fantastic work with debugpy!

**Comment by fabioz** [comment]
> I understand this answer is somewhat disappointing and I apologise but unfortunately we need to ensure the maintenance cost on our side stays controlled because we have seen too many instances of how hard is to change or even fix anything once is exposed as public.

Oh, no need to apologize here. I understand well the constraints in which CPython devs must operate on (I can even copy the whole internal code related to that -- the only downside is that if it gets better I won't get the upgrades for free).

Thanks for the great work in CPython ;)

**Comment by fabioz** [comment]
@pablogsal I actually created a copy and started doing some tests on my side to make sure the integration is ok, but it seems I found an issue related to unicode in the code in `traceback.py`: https://github.com/python/cpython/issues/99103.

**Comment by pablogsal** [comment]
This is for the report, we will take a look soon 👍
