### ISSUE TITLE
Can't expand to check the data of a Variable when debugging pytorch code

### ISSUE THREAD

**Issue by rardz** [microsoft/debugpy#1143]
for the pytorch Variable object listed in the debug panel, expand to see its `data` part shows no tensor which suppose to have in a pytorch Variable, and among the items in `data`, there is another nested `data` part which have endless nested `data` part in it.

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:32:23.601Z)
- OS Version: Linux x64 4.13.1-gentoo
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.2.1
vscode-ai|ms-|0.1.7
cpptools|ms-|0.16.0
rust|rus|0.4.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by int19h** [comment]
What is the expected resolution on debugpy side? As I noted above, the debugger currently simply reports the attributes that the object has, so infinite expansion is not actually a bug. For repr, the limitation on multiline is from VSCode itself, we don't do anything here.

If the desire is to see rich representation, it seems that this is exactly the kind of case that should be handled by the Data Viewer in Jupyter support?

**Comment by paulacamargo25** [comment]
@int19h  thanks for the explanation, II thought it was possible on the debugpy side to limit this infinite expansion somehow.. In that case, is it not possible to display the information in the debugger as the user wants?, because it will not be a bug as you mention.

**Comment by int19h** [comment]
Limiting child expansion is possible in this particular case, but why? It accurately reflects the actual self-recursive data structure that is being represented, and one could argue that removing it may mislead the users into believing that a data structure is not recursive when it actually is.

Note that the issue kinda evolved over time. When it was originally filed, even the basic repr of these values in the debugger didn't show the elements. But the current state of affairs can be seen in [this screeshot](https://github.com/microsoft/debugpy/issues/1143#issuecomment-1340086378), where it shows the repr that came from PyTorch, which includes the elements. The problem is the same as with numpy arrays - even if you see the repr, for large arrays ("some matrices have 100~1000 rows/columns"), it's very awkward and inconvenient to browse to e.g. locate one particular data item.

This is exactly the problem that Data Viewer in vscode-jupyter is meant to solve, and it seems like it [already supports this](https://github.com/microsoft/vscode-jupyter/issues/304)? It might be a discovability issue if people aren't finding this functionality.

Let's see what the users have to say, though. Aside from Data Viewer support, what else can be done with the current representation in Variables to improve it? Bear in mind that we are limited to what we can do in a single line of text.

**Comment by int19h** [comment]
I'm going to close this since the original issue is by-design. For the discussion of how to improve repr for tensors, there was a new issue filed that has a specific proposal to discuss: https://github.com/microsoft/debugpy/discussions/1199.

**Comment by satyabikash** [comment]
Read the variable in the Debug console in the vscode 
: {variable}.cpu().data.numpy().save("data.npy")
