### ISSUE TITLE
Load objects in advance before the debug file

### ISSUE THREAD

**Issue by ydmykr** [microsoft/debugpy#1144]
If I have a csv file that contains various attributes of the object, do I have a way to load the csv file in advance of the debug file instead of reading it during the run.

I know that there is an args parameter in the vscode debug `launch.json`, but can it read the csv file?

**Comment by int19h** [comment]
"args" in launch.json is treated as strings that are passed to your application verbatim, except for the escaping necessary to satisfy the shell. It cannot substitute them with file content. In general, I don't see how a CSV file could be loaded as a Python object graph before the debuggee starts running, since all Python objects are in-memory. 

If you don't want to hardcode the filename in your code, I would suggest using an environment variable for it, and set it via "env" in your launch.json.

The other thing that might be useful is "code". You can use it instead of "program" and "module", and the value should be a string containing Python code, which is passed to the interpreter via `-c`. You can do whatever initial setup you want there, and then e.g. use runpy to run your actual code. Although if the initial setup is non-trivial, it would be more convenient to create a separate module that does just that, and then calls the main script.
