### ISSUE TITLE
Debugger module name conflict

### ISSUE THREAD

**Issue by datta-nimmaturi** [microsoft/debugpy#1190]
## Environment data

- debugpy version: 1.6.5.
- OS and version: Ubuntu 20.04
- Python version: 3.8.10
- Using VS Code or Visual Studio: VS Code
- Python extension Version: v2022.20.2 (also tried older versions)

## Actual behavior

I have a folder called code inside workspace.
When the file (workspace/code/main_v2.py) is run without debugging, it works fine. When I try Start Debugging, it throws the following error.

Debugger doesn't run. It throws the error: 

`_pydev_bundle._pydev_saved_modules.DebuggerInitializationError: It was not possible to initialize the debugger due to a module name conflict.

i.e.: the module "code" could not be imported because it is shadowed by:
/work/code/__init__.py
Please rename this file/folder so that the original module from the standard library can be imported.`

## Expected  behavior

Debugger should run fine as expected.

## Steps to reproduce:
1. Create a Project.
2. Add a module named 'code' in the project. And a file in it.
3. Import something from the code module.
4. Debug the current file.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/122433216/213986514-324d9492-d699-40f7-8001-a57636027c22.png">

**Comment by int19h** [comment]
`code` is indeed a [module in the Python standard library](https://docs.python.org/3/library/code.html) that the debugger uses among many others. Due to the way module imports work in Python, if you have a local file or directory with the same name as a standard module, that local file takes precedence, breaking any code that depends on said module (including, potentially, other modules in stdlib). Since we can't avoid using the stdlib, the best we can do is provide instructions to fix this on the app side.

**Comment by datta-nimmaturi** [comment]
How do I fix this on the app side? Rename the module and change all the places it is called?
But I'm curious how it works when I do "run" instead of "debug".

**Comment by int19h** [comment]
Yes, you need to make sure that none of your module and package names clash with the standard Python ones. Unfortunately, this means that future versions of Python can break your code by adding new modules to stdlib. The only mitigation to this problem is to use a top-level package to namespace all your modules, and to use fully qualified or relative imports - then the only thing that can clash with stdlib is the name of that top-level package, which is much easier to manage.

The reason why it works when the debugger isn't involved is because your app is not itself trying to import `code` from stdlib, nor did it import some other module that might indirectly import `code`. But it's difficult to rely on since the latter part in particular is an implementation detail; any stdlib module can import any other if it needs to. For example, `pdb` also imports `code`, since it's a module provided specifically for debuggers and similar tools that want to provide a REPL similar to the standard Python one.
