### ISSUE TITLE
[Feature request] Support Listening multiples port in vscode attach

### ISSUE THREAD

**Issue by HAOCHENYE** [microsoft/debugpy#1215]
Thanks for your great work of debugpy, which benefits me a lot! But I recently encountered an issue that I cannot be solved with my current understanding of debugpy. 

I tried to use Slurm CLI tool to start a Python program in a distributed way:

```bash
srun -p xxx python my_script.py
```

Then, srun will run the python script in multiple independent processes. Therefore, I cannot directly set ports by `python -m debugpy` like this:

```bash
srun -p xxx python -m debugpy --listen ${port} my_script.py
```

Since the same port should not be set across processes. So I chose to debugpy Python API in the code:

```python
import debugpy
import socket
address = socket.gethostbyname(socket.gethostname())
port = int(os.environ['SLURM_PROCID']) + 5678
print(f"===========================address is: {address}=============================")
print(f"===========================port is: {port}=============================")
debugpy.listen(('0.0.0.0', port))
debugpy.wait_for_client()
```
and then I need to configure multiple attach in VsCode. It means that if a breakpoint is set, I have to apply `F5` across all attached debuggers which is not convenient.

In fact, each program process is almost the same, and It would be very convenient if "python attach" can listen on multiple ports. Is this a reasonable requirement? Or is there a more suitable solution?

**Comment by int19h** [comment]
We support similar scenarios when the runner itself is written in Python - in that case, you start the runner under debugger, and all Python subprocesses that it creates are automatically attached to. 

For this one, I think it would be easier if each process tried to connect back to VSCode instead - that is, use `debugpy.connect()`, and "listen" in your launch.json. That way it doesn't need to manage collisions in a port range, and you wouldn't have to tweak it depending on the number of processes. I believe this would work already from the debuggee side, but VSCode will not show connections after the first one as new debug sessions, because they're not subprocesses relative to each other. But we could have a mode where the adapter has dummy root process node and assigns all new processes that aren't subprocesses of any existing session to that. Now that I think about it, this might actually be a useful workaround in some other scenarios.

Can you take a look at `debugpy.connect()` and see the above sounds reasonable for your use case?

**Comment by HAOCHENYE** [comment]
I‘m not very familiar with the principle of `debugpy`, and I've been trying to comprehend the information described in https://github.com/microsoft/debugpy/blob/main/doc/Subprocess%20debugging.md. 

Does it mean that I can configure a server port in the IDE, which is actually initiated by the dummy root process launched by the adapter?  The dummy root process will collect information from all the debugged processes. 

The configure of `launch.json` maybe like this:

```json
            "name": "Python: Attach",
            "type": "python", 
            "request": "attach",
            "listen": {
                "host": "{ip}", "port": 5678
            },
            "mode": "{dummy}"
```

and the `srun` command:

```python
srun -p xxx python -m debugpy --connect “address:port” --mode "${dummy}"
"
```

Have I understood you correctly?

**Comment by int19h** [comment]
Sorry, I should have been clearer. You can configure a server port in the IDE, but there's no functionality for the dummy root process - that's the part that would have to be implemented in debugpy first for your scenario to work. I was just thinking that implementing it would be easier than pursuing the multi-port listener on the debuggee side, since there's a lot of coordination you'd have to do for the latter to ensure that the ports never clash.

**Comment by HAOCHENYE** [comment]
> Sorry, I should have been clearer. You can configure a server port in the IDE, but there's no functionality for the dummy root process - that's the part that would have to be implemented in debugpy first for your scenario to work. I was just thinking that implementing it would be easier than pursuing the multi-port listener on the debuggee side, since there's a lot of coordination you'd have to do for the latter to ensure that the ports never clash.

Looking forward to this feature! Please @ me in this issue if this feature is supported 😆 .

**Comment by judej** [comment]
Thank you for the report. Given our current resources are working on the Python 3.12 debugger, we will not be fixing this issues in the pre Python 3.12 debugger.
