### ISSUE TITLE
Debugging a Python program in VS Code seems to pollute PowerShell's history

### ISSUE THREAD

**Issue by huangsijun17** [microsoft/debugpy#1223]
## Environment data

- debugpy version: v2023.2.0
- OS and version: Windows 11 22621.382
- Python version : Python 3.10.5
- Using VS Code or Visual Studio: VS Code

> 版本: 1.75.1 (system setup)
> 提交: 441438abd1ac652551dbe4d408dfcec8a499b8bf
> 日期: 2023-02-08T21:32:34.589Z
> Electron: 19.1.9
> Chromium: 102.0.5005.194
> Node.js: 16.14.2
> V8: 10.2.154.23-electron.0
> OS: Windows_NT x64 10.0.22621
> 沙盒化: No

## Actual behavior

After I debug the Python program in VS Code, I go to PowerShell and press the up key on the keyboard. The last command stored is the startup command when debugging the Python program in VS Code.

## Expected  behavior

After I debug the Python program in VS Code, I go to PowerShell and press the up key on the keyboard. The last command stored is the command I entered last time in PowerShell.

## Steps to reproduce:

1. Debug a Python program in VS Code.
2. Open Windows Poershell.
3. Press the keyboard on the keyboard.

**Comment by int19h** [comment]
You can change this behavior by setting `"console":"internalConsole"` in launch.json, but this will also mean that your app will be using the Debug Console instead of the integrated terminal.

In general, debugpy itself simply hands the command line back to the client (in this case, VSCode) for processing; how to submit it to the terminal for execution is up to the client. VSCode has some tricks to avoid history pollution in Bash, but I'm not sure if there's any way for them to run the command via PowerShell like that. Still, it might be worth filing an issue on https://github.com/microsoft/vscode/
