### ISSUE TITLE
Is there a way to save the debug cache

### ISSUE THREAD

**Issue by ydmykr** [microsoft/debugpy#1247]
I have a piece of code where the breakpoint I marked is in the middle of the code, and each debug takes a long time to get it to run to the breakpoint.

Is there a way for me to read the previously loaded properties and then run functions that directly run the breakpoint section.

I think what I need is similar to interactive or jupyter-notebook, but every time I restart vscode or kernel, I still need to spend a lot of time running the previous cells.

**Comment by int19h** [comment]
This is impossible in general due to potential side effects of running code, and debugger doesn't have enough information about the running app to know which code is truly side-effect free. Thus there's no "debug cache".

But if your computation really is side-effect-free, then you could do this manually by serializing your state and then reloading it.
