### ISSUE TITLE
Attach-to-PID incorrectly defaults to unsupported "subProcess":true

### ISSUE THREAD

**Issue by amine-aboufirass** [microsoft/debugpy#1266]
Type: <b>Bug</b>

- VS Code Version: 
```
1.77.1
b7886d7461186a5eac768481578c1d7ca80e2d21
x64
```

- OS Version: 
![image](https://user-images.githubusercontent.com/24267968/230572546-32be751d-af13-449e-bb82-e4c223168e79.png)

 # Steps to Reproduce:

Folder contents:

```
.vscode
    launch.json
cli.py
test_debugpy_issue_simplified.py
```

Contents of `cli.py`:

```
print("hello world")
```

Contents of `test_debugpy_issue_simplified`:

```
import subprocess
import os
import json

print(os.getpid())
input()

configArgs = ["python", "cli.py"]

ret_code=0
while ret_code==0:
    ret_code = subprocess.call(configArgs, shell=False, universal_newlines=True)
    print(ret_code)
```

Contents of `launch.json`:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true
        },
        {
            "name": "Python: Attach using Process Id",
            "type": "python",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "justMyCode": true
        }
    ]
}
```

In order to replicate the issue, carry out the following steps:

- Open up a Powershell or CMD terminal
- Run `python .\test_debugpy_issue.py`
- Note the provided PID
- *Run > start debugging > * Attach to process with PID noted above
- Add breakpoint on line 10 in `test_debug_issue_simplified.py`
- Go back to terminal and press ENTER
- Step over to line 12 in Vs Code
- Step over line 12

The debugger freezes at `subprocess.call`. Running the script without debugging works just fine.

Extension version: 2023.6.0
VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|16.00GB (8.30GB free)|
|Process Argv|. --crash-reporter-id 9b1252ae-b8bc-46bc-a7ab-9ad131591069|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsccsb:30705552
pythonb192cf:30669361
azdwalk:30687957
pythonms35:30701012
j16hj152:30706079

```

</details>

**Comment by int19h** [comment]
`shell=True` means that the subprocess that gets spawned immediately is a shell process rather than a Python process, so subprocess debugging doesn't kick in at all. You should be getting the same effect from setting `"subProcess":false`. 

The real issue here is that we simply don't support subprocess debugging in combination with attach-to-PID at the moment. Unfortunately, this went unnoticed when we changed the default for `"subProcess"` to be true, which is why you get this behavior. We should also probably show an error message if `"subProcess"` is used at all in an "attach" configuration (it doesn't actually apply because subprocess detouring has to happen in the debuggee before attaching, so it's configured via `debugpy.configure()`).

**Comment by int19h** [comment]
For attach configurations, "subProcess" in launch.json is not applicable in any attach scenario, because by the time the debuggee sees the config, it is already too late to apply the necessary changes to the process. That's why you need to use either the API - `debugpy.configure(subProcess=...)` - or the CLI - `debugpy --configure-subProcess ...` - to change it.

**Comment by gramster** [comment]
I will add this to the FAQ.
