### ISSUE TITLE
Report sockets opened by debugpy

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/debugpy#1337]
In order to implement the [Port Attributes API](https://github.com/microsoft/vscode-python/issues/21292). We need to know the port info that debugpy generates for the debugging process. You can send this as a log message that we can track and then disable port forwarding on those ports.

**Comment by int19h** [comment]
@paulacamargo25
The protocol is as follows: when client connects to the adapter, unless it is a secondary session (i.e. subprocess attach), it receives a `debugpySockets` event looking something like this:
```json5
        {
              "seq": 6,
              "type": "event",
              "event": "debugpySockets",
              "body": {
                  "sockets": [
                      {
                          "host": "127.0.0.1",
                          "port": 63435,
                          "internal": false
                      },
                      {
                          "host": "127.0.0.1",
                          "port": 63437,
                          "internal": true
                      },
                      {
                          "host": "127.0.0.1",
                          "port": 63436,
                          "internal": true
                      }
                  ]
              }
          }
```
Thereafter, such events are sent whenever the adapter opens or closes a port, with the content of "sockets" updated accordingly. At any given moment, the only ports that should be forwarded are those that were present in the most recent such event with `["internal"] === false`.

See https://github.com/microsoft/debugpy/pull/1404 for implementation.

**Comment by Anthony-Eid** [comment]
Hi I'm trying to implement a client side debug adapter and I'm having trouble handling debugpySockets event. Is it safe to ignore the event? And when you mention port forwarding do you mean that the client should also listen to ports marked with `["internal"] = false` when running a debugger? 

Thanks in advance!!

**Comment by int19h** [comment]
It is safe to ignore that event; it is there in case you need that information.

"Forwarding" in the discussion above specifically pertains to VSCode port forwarding when doing remote debugging (e.g. in Docker containers) - in that case the part of the client that handles that will need to know which ports need to be forwarded from the container to VSCode so that the latter can attach to the debugger inside the container. If you're not doing anything like that you don't have to worry about it.

If you _are_ doing anything like that, the only ports that you need to care about are indeed those that are not "internal" - the ones that are "internal" are used for local IPC between debugpy components and debuggee, basically. The "internal" ones are there in case you need to know whether a port being opened is owned by debugpy regardless of how it is used.
