### ISSUE TITLE
There is no stopped event after pause request

### ISSUE THREAD

**Issue by pointhex** [microsoft/debugpy#1376]
I am developing a DAP client for qtcreator and faced the problem that after "pause" I don't get the "stopped" event and debugging looks frozen. It happens with PySide6 lib and time.sleep(100) look to "Steps to reproduce".

Environment data
- debugpy version: 1.6.7.post1
- OS and version: Ubuntu 22.04
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.6
- Using VS Code or Visual Studio: -

Actual behaviour
- sent the "pause" request
- get the "pause" response successful
- didn't get "stopped" event
- It looks like all debugging is stuck because even ctrl + c, doesn't work to stop it.

Log
qtc.dbg.dapengine: "Content-Length: 59\r\n\r\n{\"arguments\":{},\"command\":\"pause\",\"seq\":5,\"type\":\"request\"}"
qtc.dbg.dapengine: "Content-Length: 86\r\n\r\n{\"seq\": 11, \"type\": \"response\", \"request_seq\": 5, \"success\": true, \"command\": \"pause\"}"

Expected  behavior
- sent the "pause" request
- get the "pause" response successful
- get "stopped" event

Steps to reproduce:
python3 -Xfrozen_modules=off -m debugpy --listen 127.0.0.1:5679 --wait-for-client main.py

first example:
```
import sys
from PySide6.QtWidgets import QApplication
if __name__ == "__main__":
    app = QApplication(sys.argv)
    sys.exit(app.exec())
```
second example:
```
import sys
import time
if __name__ == "__main__":
    while True:
        print("here --->")
        time.sleep(1000)
```
When the timer is finished "stopped" event comes.

**Comment by int19h** [comment]
The debugger works on Python VM level (`sys.settrace` etc), and thus it cannot pause the thread while Python is inside a long-running native call. The same applies to blocking I/O operations - e.g. if you try this with `input()` you'll see the same thing. The "stopped" event is reported as soon as debugger first gets a chance to do anything on the affected thread, so it should be considered best-effort. There's nothing we can do about this, unfortunately - handling this properly requires some form of mixed-mode Python/native debugging (so that the native debugger can handle the break), which is only available in Visual Studio on Windows at the moment.

**Comment by pointhex** [comment]
Thank you for the answer! Is it possible to start mixed mode somehow? And is there any documentation about it?

**Comment by int19h** [comment]
It is a completely separate debugger, not a part of debugpy: https://learn.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2022. I don't think it can be reused outside of VS, since it depends on VS native debugger.
