### ISSUE TITLE
Launch not working for packaged application start over cli

### ISSUE THREAD

**Issue by thimmy687** [microsoft/debugpy#142]
Hi,

we have a django application [integreat-cms-django](https://github.com/Integreat/cms-django) which will be packaged before running.

so we use a own cli to run the server instead of using the standard manage.py.

unfortunately I can not start the debugging with the normal launch configuration, and the attaching is also not so well working.

So maybe we can allow to start the launch with our cli instead of the normal manage.py?

Here is our project and under ./dev-tools/run.sh is the current start process shown:
https://github.com/Integreat/cms-django

BR

**Comment by int19h** [comment]
For "launch", the debugger needs the script to be started directly via a Python interpreter, because it has to know how to inject itself into the command line it ultimately produces. So you can't use run.sh directly, but you can try to mimic what it does via VSCode tooling, such as pre-launch tasks.

Alternatively, you can tweak your script such that it starts the server via debugpy, and then [attach to it over a socket](https://github.com/microsoft/debugpy/wiki/Command-Line-Reference#hostport).
