### ISSUE TITLE
[sys.monitoring] SystemExit handling

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#1455]
`SystemExit` is special because whether it indicates an actual failure or normal exit depends on the exit code. Exception breakpoint logic should default to `SystemExit(0)` not being reported, but should also allow specifying a list of valid success exit codes to suppress reporting for - this is used heavily in web apps where e.g. `SystemExit(3)` is typically used to signal process reload and should also be treated as success.

**Comment by aashayamballi** [comment]
Facing a similar issue in our containerized Django application when I use debugpy with a vscode debugger. whenever I save a file when the debugger is on it gives the systemexit error in the manage.py file

**Comment by int19h** [comment]
Note that this issue is for the new debugger implementation that we're working on - it's not about a bug. If you're seeing a problem like that in the existing debugpy implementation, please file a separate bug in this repo. However, if you have `"django": true` in your debug config, it shouldn't break on `SystemExit(3)` with the default exception settings.

**Comment by danielniccoli** [comment]
@int19h @aashayamballi 

The behavior of debugpy is not in compliance with the specifications. Because the underlying issue is broader that just the `SystemExit()` behaviour, I raised a separate ticket on the matter, which explains the problem and suggests a solution that should not only fix the issue you are having, but other issues as well. Unforatunately, it was closed and moved to a discussion. Please contribute, if you wish to see it fixed.

The issue: https://github.com/microsoft/debugpy/issues/1590
The discussion: https://github.com/microsoft/debugpy/discussions/1591

**Comment by judej** [comment]
shelving work for sys.monitoring implmentation for now
