### ISSUE TITLE
Breakpoints ignored if file extension is not `.py`

### ISSUE THREAD

**Issue by HiPhish** [microsoft/debugpy#1514]
## Environment data

- debugpy version: 1.8.0
- OS and version: Void Linux (Linux 6.6.11)
- Python version: 3.12.1 (CPython)
- Using VS Code or Visual Studio: No, using Neovim with [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap)

## Actual behavior

When starting the debugger to debug a program breakpoints are ignored unless the program ends in `.py`

## Expected  behavior

Break points should work regardless of file extension

## Steps to reproduce:

Here is a small example script:

```python
#!/bin/env python3


def add(x: int, y: int) -> int:
    """Recursively add up two numbers."""
    if y == 0:
        return x
    return add(x + 1, y - 1)


if __name__ == '__main__':
    x, y = 2, 3
    print(add(x, y))
```

1. Set breakpoint on line 6 (`if y == 0`)
2. Start the debugger with the following configuration: `{"program": "my-prog", "request": "launch", "args": []}`
3. The debugger will continue right through to the end

**Comment by judej** [comment]
@HiPhish, thanks for reporting the issue. The debugger resolves source mappings and determines which files should have breakpoints applied. Without a .py extension, the debugger may be unable to confidently identify the file type as Python.  Currently .py files are required. Closing this issue since given our current limited resources, it's unlikely we will be able to fix this issue in the near future. Thanks!
