### ISSUE TITLE
Launch request cwd is not respected by the debugger

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#154]
It is neither. It's just on a plain old "launch" request. And I've always specified cwd. It just stopped working. 

```
        {
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "args": [...],
            "console": "integratedTerminal"
        }
```

_Originally posted by @yandemontreal in https://github.com/microsoft/vscode-python/issues/11425#issuecomment-622516122_

**Comment by int19h** [comment]
@yandemontreal, does this reproduce with a trivial script? Something like this:
```py
import os
print("cwd:", os.getcwd())
```
Also, can you check debugpy version? `import debugpy; print(debugpy.__version__)` somewhere in your code should do the trick.

**Comment by int19h** [comment]
Oh, and can you also share the output in the terminal when you try to run it? What command line is generated there for `debugpy/launcher`, in particular.

**Comment by yandemontreal** [comment]
@int19h The debugpy version is 1.0.0b7
While trying to get a reproducer, I realized the problem is not with the cwd. The issue seems to be  deeper into my stack, specifically with the `Start Process` keyword of Robot Framework. I'm attempting to start a python script (process) and the python process I'm launching returns "No module named xyz.py".

I don't want to keep this issue open longer than needed, but just know that the issue does not happen with version 71113 and also does not happen when not using the debugger. I would need more time to dig deeper, but let me know if I can get any sort of info for you.

**Comment by int19h** [comment]
To clarify, you're starting a Python script that uses some framework to spawn another Python script? Or are you trying to use the framework runner as your `pythonPath`?

**Comment by yandemontreal** [comment]
I'm starting a Python script, which calls the framework as a Python module (`submodule.call()`). That framework then spawns a process which is a call to python. I've created a reproducer that includes Robot Framework (you'd have to `pip install robotframework`)

As far as I have looked, it's as if the launched process is now assumed to be a module. As if I had launched it with `-m`. If I remove the .py extension from the call (in the .robot file attached), then it will work.

As for terminal output:
Before:
```
C:\debugpy-154> cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && C:\Users\xyz\AppData\Local\Continuum\anaconda3\envs\python36\python.exe c:\Users\xyz\.vscode\extensions\ms-python.python-2020.3.71113\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 49697 c:\debugpy-154\test.py "
-- Stuff --
C:\debugpy-154>C:/Users/xyz/AppData/Local/Continuum/anaconda3/Scripts/activate
(base) C:\debugpy-154>conda activate python36
(python36) C:\debugpy-154>
```
After ms-python update:
```
C:\debugpy-154>C:/Users/xyz/AppData/Local/Continuum/anaconda3/Scripts/activate
(base) C:\debugpy-154> cmd /C "set "DEBUGPY_LAUNCHER_PORT=49993" && C:\Users\xyz\AppData\Local\Continuum\anaconda3\envs\python36\python.exe c:\Users\xyz\.vscode\extensions\ms-python.python-2020.4.76186\pythonFiles\lib\python\debugpy\no_wheels\debugpy\launcher c:\debugpy-154\test.py "
-- Stuff --
(base) C:\debugpy-154>conda activate python36
(python36) C:\debugpy-154>
```
[debugpy-154.zip](https://github.com/microsoft/debugpy/files/4570942/debugpy-154.zip)

**Comment by int19h** [comment]
I can repro. @fabioz, it appears to be a pydevd issue. Specifically, when it's doing command line rewriting for the second subprocess (when the Robot Framework process tries to spawn the target script), the log goes like so:
```
Patching args: ['python', 'test-process.py']
New args: python c:\Users\pminaev\.vscode\extensions\ms-python.python-2021.8.1105858891\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py --port 61730 --ppid 10660 --client 127.0.0.1 --client-access-token ... --DEBUG_RECORD_SOCKET_READS --multiprocess --module --skip-notify-stdin --json-dap-http --file test-process.py
```
Note `--module` - I don't think that's supposed to be there. Skimming through pydevd source, I think this is because `setup_to_argv` propagates `--module` unconditionally, even though it shouldn't be automatically applied to child processes.
