### ISSUE TITLE
Puzzling behavior of debugging with debugpy

### ISSUE THREAD

**Issue by colourfulspring** [microsoft/debugpy#1542]
Hi,
I found a puzzling behavior of my vscode python debug extension.

In my machine, I tried to debug this python code in my vscode:
```py
flag = True
flag2 = True

for i in range(5):
    if flag:
        print("aaa", flush=True)
        print("bbb", flush=True)
        if not flag2:
            break
    elif flag2:
        pass
```
I put a breakpoint at the last line of my code, `pass`. In my understanding, because `flag = True`, the elif statement would never be executed. But in my vscode, the program stopped at the `pass` line.

For more test, I changed `pass` to `print("ccc", flush=True)`, which means my code is:
```python
flag = True
flag2 = True

for i in range(5):
    if flag:
        print("aaa", flush=True)
        print("bbb", flush=True)
        if not flag2:
            break
    elif flag2:
        print("ccc", flush=True)
```
The breakpoint still exists, at the last line of my code `print("ccc", flush=True)`. I debug the code again.
This time the program ends. The breakpoint didn't blocked the program.

My friend suggested me using `pdb` to do the same test and `pdp` didn't have this problem.
I don't understand why is it. Is there any specific reason for this behavior?

My OS is ubuntu 20.04.6 LTS (Focal Fossa).
My python version is 3.11.4
My debugpy version is 1.8.1

**Comment by judej** [comment]
@colourfulspring, I am not able to reproduce the issue with the above code on Python 3.12.6 and debugpy 1.8.7. If you are continuing to see it, please reopen the issue. The reason for this could be that the `flush` might be causing the debugger to assume that there are side-effect and therefore reevaluate the breakpoints and optimize out the last one. But since I was unable to reproduce it, I can't confirm.
thanks!
