### ISSUE TITLE
Improve dealing with blocking evaluate requests

### ISSUE THREAD

**Issue by jackwickham** [microsoft/debugpy#157]
## Environment data
- PTVSD version: 4.3.2
- OS and version: MacOS and CentOS
- Python version: 3.6 and 3.7
- Using VS Code or Visual Studio: VS Code, and interacting with ptvsd directly

## Actual behavior
When justMyCode is set to false, operations on a spark dataframe that has been constructed in python using `session.createDataFrame` will hang if run in the debugger repl, but not if run normally. Spark appears to hang, printing `[Stage 0:>           (0 + 1) / 1]`.

## Expected  behavior
The code should not hang, or it should not matter what the state of justMyCode is.

## Steps to reproduce:
With pyspark installed (I have the latest spark 3.0 preview build), I can reproduce it by trying to debug the following script with `"justMyCode": false` in launch.json.
```python
from pyspark.sql import Row, SparkSession

def my_compute_function(session):
    row1 = Row(id='1', name='name')
    df = session.createDataFrame([row1])
    df.show() # set a breakpoint on this or the next line, and evaluate `df.show()` in the repl when it breaks
    return df


session = SparkSession.builder.master("local").appName("df-show").getOrCreate()
my_compute_function(session)
```

In ptvsd 4.2.10, it also hangs if you step over the `df.show()` line, but that was fixed by moving to 4.3.2. I guess that is because of https://github.com/microsoft/ptvsd/issues/1372, although I haven't verified that.

**Comment by fabioz** [comment]
I'll start to work on this issue.

My current idea for the fix will be doing the following:

- Detect it's taking to long to do some evaluation.
- If it times out:
    - notify the user 
    - make all other threads run
        - when the evaluation finishes, stop all other threads again
        - if the evaluation still doesn't finish after some timeout, notify the client (I'll also experiment with https://docs.python.org/3/c-api/init.html?highlight=pythreadstate_setasyncexc#c.PyThreadState_SetAsyncExc to see if it's possible to cancel the execution so that the program is not stuck forever).

As a note, I think that for the first one we can have something like a 10s. timeout (which the user could configure to be lower/higher/disabled) and the second should not be active by default since it's possible that the evaluation is really expected to be a long running operation (right now I'll only enable those to be set only through environment variables -- we can make a setting for that later if needed).

After that's done for the evaluation we should probably do something similar for the use case where just getting a representation of some object takes a really long time (which is probably the culprit in https://github.com/microsoft/debugpy/issues/274).

@int19h @karthiknadig I'll start to work on that approach, but I'm open to feedback if you think something should be different here.

**Comment by int19h** [comment]
Sounds good!

For the notification, we can always add a custom message and wire it up on VSCode side - indeed, we already discussed such a thing for #170. Then it could be an async message that does not block or otherwise interrupt the evaluation - merely notifies the user that it's still ongoing.

Also, DAP has added "progress" events not long ago - take a look at `ProgressStartEvent` in the [spec](https://microsoft.github.io/debug-adapter-protocol/specification). VSCode has some built-in UX for this, but it's more low-key, like a spinning circle. If you use that, I think we can reduce the timeout, so it kicks in after, say, 1s. If async exception injection works out, we can wire that one to `CancelRequest`. This would also fix #173.

**Comment by int19h** [comment]
To clarify: 1s is probably too low to try resuming other threads - 10s sounds more reasonable (we can experiment and figure out what works best). But 1s would be a better threshold for a low-key notification that evaluation is taking a long time.

**Comment by fabioz** [comment]
As a note, I'm still working on this issue.

I've just finished the part related to unblocking threads, which required dealing with asynchronous messages (both on pydevd as on debugpy), but there are things still missing:

- provide a message saying that evaluation is taking a long time and how to mitigate that
- provide thread interruption
- more work on corner case where a breakpoint is hit in the secondary thread during the evaluation (unblocking the evaluate request from debugpy was the first step, but it still seems to deadlock going forward, so, this needs a bit more investigation).
