### ISSUE TITLE
Terminal debug experience in Python Debbuger Extension

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/debugpy#1612]
We are implemented a debug terminal with shell integration, in order to do that we will need an extra implementation in debugpy side.

In order to start debugging from the terminal, we need to specify a connect or listen port in the command: `python -m debugpy --connect 5678 file.py`.

What we want is to be able to use only: `python -m debugpy file.py` and debugpy set internally the connect port by default to 5678.

**Comment by rchiodo** [comment]
What's preventing you from passing the arguments? Seems unnecessary to change debugpy to support this if you can just pass the arguments.

**Comment by karthiknadig** [comment]
The scenario is in the debug terminal user can just type something like. This is part of work that we are doing to make debuging  basic things config free.

```
>>> python myscirpt.y
```
and we want to be able to launch it under the debugger. That is the ideal experience we want.

As midway solution is to run: 
```
>>> debugpy myscript.py
``` 
But this requires `--connect ` to work correctly. Instead, if we could pass the connection data via environment variables (or any other mechanism) the users won't have to figure this out.

**Comment by rchiodo** [comment]
So you intercept `python myscript.py` and then turn it into `python -m debugpy myscript.py`? Can't you just add the connect options then?


Or are you telling users to run `python -m debugpy myscript.py`?

**Comment by karthiknadig** [comment]
The shell integration allows us to do extra things, in addition to executing the command user provided. Not removing or replacing it. Also, `python myscript.py` is the eventual ideal case (debugging is controlled via a toggle), but it is not possible right now. 

But, `debugpy myscript.py` is possible. We have a prototype working with `python -m debugpy --connect <port> mypyscript,py`. And we see that if we can remove the `--connect` and get a script/bin launcher for debugpy we can make this with simpler version of the command.

This also makes it so users can use debugging using `debugpy myscitpt.py` and run without debugging using `python myscript.py`

**Comment by rchiodo** [comment]
Okay just to make sure I understand, you `can't` replace the arguments, the command has to run as is. So you want defaults and a command line runner for `debugpy` so the user can just use `debugpy myscript.py`

**Comment by karthiknadig** [comment]
That is correct.

**Comment by int19h** [comment]
Hardcoding the port may be unwise since it can interfere with other concurrent uses. I think for this you'll want to start the debug config with `"listen" { "port": 0 }` to have it use a free ephemeral port, read the actual port to use (see [this](https://github.com/microsoft/debugpy/blob/a286befecd26176025fd121819cf467ba308a0da/src/debugpy/adapter/__main__.py#L99-L119) for details), then pass it to `debugpy --connect` somehow.

Env vars are probably the easier. Instead of special-casing each CLI switch separately, I would suggest something like `DEBUGPY_EXTRA_ARGV` that would simply be injected into `sys.argv` by debugpy server before parsing. And then you'd just do `DEBUGPY_EXTRA_ARGV=--connect ...` before letting the shell run it.

**Comment by karthiknadig** [comment]
The environment variable idea is actually great. I want that to use listen mode on Debugpy side, ephemeral port selection via 0, use wait for client, all passed in via environment variable.

Is there is mechanism to pull the port out of Debugpy? 

The reason I want this mode is, we can’t pause the terminal content from executing. So with Debugpy in listen mode we can guarantee order of this. Only catch is that we need the port, can Debugpy dump the port into a file or pipe?

**Comment by int19h** [comment]
@karthiknadig, there is a mechanism, albeit undocumented (it's currently only used for the test suite) - see the link in my earlier comment.

**Comment by int19h** [comment]
The same mechanism should be usable. When you do `debugpy --listen`, the server spawns the adapter, and the adapter does the actual listening for the purposes of incoming client connections. That info gets written out to the file in exact same way via `DEBUGPY_ADAPTER_ENDPOINTS`, so as long as you can make sure that env var is in effect for the adapter, you should be able to read it from the file.

I think there might be a slight issue there in that the way the adapter writes out that file is not atomic (i.e. it just creates the file with that exact name and does a write). So there's a potential race there where if you just watch the filesystem for the file, there's a chance that the adapter has already created the file, but isn't done writing to it, and so opening might fail because the file is locked, or if it succeeds, it might observe an empty or partially written file. For tests this was "good enough" - at least we never ran into this issue, as far as I know - but if product logic is going to rely on it, it would be best to change the adapter code to do an atomic write-and-rename, so that polling or watching for that exact file name will always show it as either non-existing or as containing valid data.

**Comment by karthiknadig** [comment]
If `DEBUGPY_ADAPTER_ENDPOINTS` is a named pipe or fifo would it just write to that?

**Comment by int19h** [comment]
That's a good question. You can [look at the code](https://github.com/microsoft/debugpy/blob/a286befecd26176025fd121819cf467ba308a0da/src/debugpy/adapter/__main__.py#L99-L119) - it does a simple open/write/close on start, although it does try to delete it on shutdown (but swallows any exceptions from that). So yes, I think it would work as well.

**Comment by karthiknadig** [comment]
Then I think `DEBUGPY_EXTRA_ARGV` will just work.

**Comment by karthiknadig** [comment]
The feature request here is to support `DEBUGPY_EXTRA_ARGV` env variable that we can inject into the terminal. `debugpy` should read this variable, and consume from it if explicit CLI equivalent is not there.

**Comment by int19h** [comment]
This would be the locus of the implementation: https://github.com/microsoft/debugpy/blob/a286befecd26176025fd121819cf467ba308a0da/src/debugpy/server/cli.py#L403

**Comment by AdamYoblick** [comment]
Hi @paulacamargo25 - This work is done and the corresponding PR has been merged in. It will be in the next release of debugpy. I'm currently working on #1613, and I'm planning on finishing that task before doing a debugpy release. The work for 1613 is actually done, but I need to test on mac and linux before merging it in.

**Comment by paulacamargo25** [comment]
Thanks for your work @AdamYoblick, do you plan to do a release of debugpy this month right?

**Comment by AdamYoblick** [comment]
> Thanks for your work @AdamYoblick, do you plan to do a release of debugpy this month right?

Yes, I just finished testing the other issue and Karthik approved the PR, so I will merge it in tomorrow and do a release of debugpy tomorrow or Thursday most likely.
