### ISSUE TITLE
Add a runner to `debugpy` package

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#1613]
A runner that allows us to launch `debugpy` from terminal directly, instead of `python -m debugpy`

After installing `debugpy` in an environment, there is no executable runner added to `scripts` or `bin` directory of that environment.

For windows:
Suppose you have an environment : `C:\project\.venv`
Then there should be a binary: `C:\project\.venv\Scripts\debugpy.exe`

For linux/mac:
Suppose you have an environment : `~/project/.venv`
Then there should be a binary: `~/project/.venv/bin/debugpy`

**Comment by AdamYoblick** [comment]
Hi @karthiknadig - I was talking to Graham on how to do this, and I think what we want to use is something like this: https://setuptools.pypa.io/en/latest/userguide/entry_point.html

This will create an alias which is runnable from the root of the package which I think will satisfy your requirement. I don't think it will create binaries per se, but I think it will do what you're asking for. I'll check with Brett to be sure.

Does this sound ok?

**Comment by karthiknadig** [comment]
It could work. Good to check with @brettcannon on this.

From what I can tell, it does allow us to launch `debugpy` by calling `> debugpy`. But it should work even if the package path is added to `PATH` or `PYTHONPATH`. The issue here is that `debugpy` is not installed in the environment. I am assuming this mechanism adds something to the `Scripts` or `bin` directory, even if it is not a binary it is ok. As long as we have some way to invoke it. They key is that it should work even if `debugpy` is not directly installed in the environment.

**Comment by AdamYoblick** [comment]
Ok thanks, I'll get the entry point created and do some testing.

**Comment by AdamYoblick** [comment]
@karthiknadig Ok so I did initial testing of the entry point in the first scenario which is when the package is directly installed in the environment being used. The entry point works like a charm. I was able to run `debugpy -V` instead of `python -m debugpy -V` and the output was identical.

So the other scenarios are debugpy is installed in a global environment, but not in a virtual environment, and it should still work from the venv as long as the package is on the path or pythonpath?

**Comment by karthiknadig** [comment]
The other scenario is that you do `pip install -t some_directory debugpy` , this will install debugoy in some directory, not a global environment. Now we need to able to run debugpy from that location. The test would be install debugpy to some target directory. Then go to some project some where else, see if you can launch debugpy from terminal for that project.

Python debugger extensions bundles debugpy this way by installing it to a directory. So from debugger extension's install location we need to able to add it to VS Code terminal. we can modify the PATH or PYTHONPATH in the VS Codes terminal.

**Comment by AdamYoblick** [comment]
I tested the following:

1. Install debugpy to a random folder like this: `python -m pip install -t .\temp --no-index --find-links . debugpy`
2. Add that folder to both `PATH` and `PYTHONPATH`
3. Tried running both `python -m debugpy -V` and `debugpy -V` from a different directory, but it didn't work.

Let me search online to see if there's another way to do this

**Comment by AdamYoblick** [comment]
@int19h - Hey Pavel, I wanted to get your thoughts on this because Karthik said this is something you wanted to do a while back. Basically the entry point works, but trying to run when debugpy is installed to a standalone directory doesn't work, even when you add that directory to PATH.

I know that we mess with sys.path when debugpy is invoked directly from code (instead of from the installed module). I was thinking we could do something similar here - detect if we're running from an entry point, and if we are, modify sys.path accordingly. If we can't detect it, we could have an env var force the behavior.

Thoughts?

**Comment by AdamYoblick** [comment]
> I tested the following:
> 
> 1. Install debugpy to a random folder like this: `python -m pip install -t .\temp --no-index --find-links . debugpy`
> 2. Add that folder to both `PATH` and `PYTHONPATH`
> 3. Tried running both `python -m debugpy -V` and `debugpy -V` from a different directory, but it didn't work.
> 
> Let me search online to see if there's another way to do this

Actually I misspoke. Looks like setting `PYTHONPATH` to the install directory of the package, then adding the bin directory inside the package to `PATH` does the trick! I don't think any more changes are needed in debugpy source for this to work. 😄

**Comment by judej** [comment]
[like]  Jude Kavalam reacted to your message:
________________________________
