### ISSUE TITLE
What happened to v1.8.3 and v1.8.4?

### ISSUE THREAD

**Issue by cicdguy** [microsoft/debugpy#1647]
We were using v1.8.3 from PyPI and I just saw that the v1.8.5 tag was created an hour ago.
Just curious to know where v1.8.3 and v1.8.4 went and why they were removed?

**Comment by AdamYoblick** [comment]
Man, you guys are quick with ingesting new bits. 😄 

Unfortunately we had some issues with the internal tool that does our releases, and 1.8.3 was an incomplete release. I removed it as soon as I became aware. 1.8.4 had some similar problems. 1.8.5 should be good to go, I will create the corresponding github release tomorrow.

**Comment by elisw93** [comment]
In the future, it would be preferable if bad releases were yanked (per [PEP 592](https://peps.python.org/pep-0592/)) rather than removed altogether. (However, I saw that there was already [one yanked release](https://pypi.org/project/debugpy/1.4.2/) from 2021, so it's possible that there was a reason these packages couldn't be yanked...)

**Comment by AdamYoblick** [comment]
I agree. The reason I had to delete it after yanking it is because we have some internal tools that "do the wrong thing" and enumerate releases, yanked or not. 

This was breaking builds of other products, so I had to get rid of that release asap. 

I have a task to fix that bad logic, but I had to unblock first. Apologize again, I will try to avoid this in the future.
