### ISSUE TITLE
`super()`: no arguments

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/debugpy#1732]
## Environment data

- debugpy version: 1.8.7
- OS and version: Win 11 24H2
- Python version (& distribution if applicable, e.g. Anaconda): 3.12.0 via `uv`
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Cannot run `super()` in Debug Console

## Expected  behavior

Can run `super()` in Debug Console

## Steps to reproduce:

```python
class A:
    def method(self):
        print("super!")

class B(A):
    def method(self):
        super().method()

B().method()
```

1. Set breakpoint in line `super().method()`
2. Run file with debugger attached
3. At breakpoint, run `super().method()` in Debug Console

![Image](https://github.com/user-attachments/assets/90611b82-2d59-4ef3-81cb-e45911a18b54)

**Comment by rchiodo** [comment]
Thanks for the issue but that's by design. The debugger is just running what you type in a python `eval` call. `super()` isn't allowed in an `eval` call.

 `super()` really means `super(__class__, self)`. See this PEP: https://peps.python.org/pep-3135/

If you want this to work, you'd do this instead:

```
super(__class__, self).method()
```

**Comment by bersbersbers** [comment]
Thanks - learned something 😃
