### ISSUE TITLE
Halt release CI if wheels fail to build?

### ISSUE THREAD

**Issue by elisw93** [microsoft/debugpy#1784]
The release [1.8.10](https://pypi.org/project/debugpy/1.8.10/#files) was uploaded to PyPI with only a source distribution and one wheel, and was subsequently yanked for being incomplete. This has happened in the past, eg #1647.

Is there any plan to implement checks in the release process to prevent this from happening in the future?

I did see https://github.com/microsoft/debugpy/issues/1775, which this issue might be a duplicate of, but I can't access any of the resources linked in that issue and I don't have any more context here.

**Comment by rchiodo** [comment]
We have checks in place, they just failed. That's why it was yanked. You can't know what you don't know before you know it. 

It was related to a subrepo'd pydevd and it pulled down a dist-info for another vendored package. Some reason publishing decided that because of that embedded dist-info, we were publishing that too and it failed halfway through.

I think the best we can do is yank it when it fails.
