### ISSUE TITLE
Step into library import statement gives "Could not load source '<string>': Source unavailable."

### ISSUE THREAD

**Issue by luabud** [microsoft/debugpy#209]
Set a breakpoint to a ``import numpy`` statement and step into it. It'll raise: ``Could not load source '<string>': Source unavailable.``

VS Code Insiders 1.33.0
Extension version 2019.3.6215

launch.json file:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Python-test",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "stopOnEntry": true,
            "cwd": "${workspaceFolder}",
        },
    ]
}
```

**Comment by fabioz** [comment]
@int19h given that we keep on hitting this issue, I'll change the approach. Instead of filtering modules which should be considered library code I'll whitelist what should be user code -- I think that the only case where we really want to consider it is `<string>` on some cases (where we already have a custom handling) and 'ipython' cells (so, other than that, everything else will be user code).

@Sutyke related to the `step in`/`step in my code`, I believe this is a feature that needs to be first added to VSCode/DAP itself (the debugger can already do that internally, but the UI would need to support that to integrate properly).

**Comment by int19h** [comment]
I think at this point we should just throw in the towel and declare that if it's not path-mapped, `<...>` is not user code. There's just no good way for us to detect otherwise - even walking the stack to see where it was called from isn't reliable in real world scenarios.

**Comment by kqqian** [comment]
vsc 1.46.0, after add "justMyCode": false, it can debug into python inner code.

**Comment by aminechm** [comment]
what worked for me was clearing all .pyc and __pycache__ recursively using : https://gist.github.com/hbsdev/a17deea814bc10197285

in both my local workspace and equivalent Docker container

**Comment by kqqian** [comment]
谢谢，我会尽快查收
