### ISSUE TITLE
Code Reloading

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#212]
Allow code to be modified while at break-point, then continue executing the modified code.

**Comment by puremourning** [comment]
I would be keen on supporting this in vimspector, so if adapter vendors go down this route i'd strongly advocate for adding to the base DAP protocol rather than custom code. Vimspector has no way to run adapter-specific code (nor should it!).

**Comment by fabioz** [comment]
I created https://github.com/microsoft/debug-adapter-protocol/issues/176 to add a new message in the specification (we'll probably go with a custom message until that makes it into the official specification).

**Comment by puremourning** [comment]
Would it be possible to base it on the existing jdt.ls/java debug server message? They use hotcodereplace 

Refs

https://github.com/puremourning/vimspector/issues/252

https://github.com/microsoft/java-debug/search?q=hotcodereplace&type=

hoping not to have to back invidual custom messages for each server type in vimspector  if poss. Hopefully some discussion will come from the DAP proposal too.

**Comment by fabioz** [comment]
I'm not sure if that's feasible... we don't really support `hot code replace` here (which would change the current executing frame), as that's not supported by Python itself.

What we aim to support is code reload, which means that the debugger is able to change code that's NOT currently executing (so, we'd change the contents of a class or function in-place -- with a bunch of caveats -- one of those is that it'll only work if that code isn't currently executing).

**Comment by puremourning** [comment]
Oh and you need the client to do the file watching? that will be potentially tricky (eg to determine which files should be watched). Could debugpy watch the files with [watchdog] (https://pypi.org/project/watchdog/) and then use the java model (ask the client ‘should I reload this’)? That means debugpy gets to decide which reloads would work too. Just thinking out loud - I’m hoping that DAP can adopt something general, and I’m not we’d to the java model - just don’t want lots of individual servers coming up with something different like in LSP

**Comment by fabioz** [comment]
My initial idea is that only the file changed on the editor will have code reload applied (so, when the contents of the current editor change and the user saves the file in the editor, then code reload will take place if the editor implementor is interested in doing that -- the initial implementation would be having vscode-python call the a custom message when that happens as I suspect it'll take more time to have that added to the official DAP spec).

So, no file watching should be required (but that's of course up to the editor implementor, `debugpy` will just provide the support for the reload and can't really dictate how it'll be used).

**Comment by int19h** [comment]
I think we'll have to do it on debugpy side if only because it won't work otherwise in remote attach scenarios. But the bonus would be that it'd also automatically work for all clients.

It does mean we'd have to vendor something like fs-watcher though, which has dependencies of its own. It might be possible to reduce the amount of vendored code if the feature targets Python 3 specifically.

**Comment by fabioz** [comment]
> I think we'll have to do it on debugpy side if only because it won't work otherwise in remote attach scenarios. But the bonus would be that it'd also automatically work for all clients.

Why wouldn't it work with remote attach scenarios (given that the file path would be translated as usual)?

We can do a file watcher, but that comes with lots of caveats by itself, so, if we can avoid it, I think it'd be better...

**Comment by int19h** [comment]
In remote attach, the filesystem is remote relative to the IDE, so it wouldn't be able to watch it. And if it just reports files being changed in the editor, that wouldn't make much sense, since they'd only be changed on IDE side - the debuggee would still be dealing with old code, until the user synchronizes it manually somehow.

**Comment by fabioz** [comment]
Humm, but then editing those contents on the server side (instead of in the editor) would probably be kind of a pain too (and it'd become unsynchronized with the contents of the editor in the client side).

Maybe we could send the contents of the file in the code reload message and have the debug server update that file?

**Comment by int19h** [comment]
At that point, it's probably better to just use VSCode's own [remoting support over SSH](https://code.visualstudio.com/docs/remote/ssh). In which case, from debugger's perspective, the debug session becomes local. 

Where the debugging remote scenario can be interesting is when there's no path mapping set up (intentionally), and thus source code is fetched over the wire via `Source` display. If I remember correctly, such source is considered read-only from the IDE perspective - but DAP has messages for the debugger to report changes, implying that it can change on the other side during the session. This is kind of an edge case, I think, but since it's specifically accommodated in the protocol, it might not be as rare as I think.

The other thing we'll have to think about is how it'll work with PTVS, since it also uses debugpy. While it can also monitor files, of course, the implementation of any custom messages etc would have to be done from scratch there, since we can't reuse TS code from vscode-python.

**Comment by fabioz** [comment]
Ok, I'll take a look at supporting this with a file watcher.

**Comment by fabioz** [comment]
As a note, I'm working on this.

My idea is starting with a simple polling-based file watcher (there are many pitfalls with the native-based implementations such as `watchdog`, and polling must always be a fallback because on some scenarios the native-based approach doesn't work).

`watchgod` is the one that came closer to what I expected, but it has some issues -- i.e.: no support for python 2.7, and I think the scanning could try to cache based on the folder modified time instead of always scanning full trees to make things a bit more performant.

So, I'm currently taking a look at implementing the poll-based file watcher to use here.

**Comment by fabioz** [comment]
I've finished the poll-based file watcher and I'm thinking about how to do the tracking.

My initial idea is to support something as the following in the launch configuration arguments:

```
autoReload: {
    enable: true,
    watchDirs: ['c:/temp'],
    pollTargetTime: 3,
    ignoreDirectories: ['node_modules'],
    fileExtensions: ['.py', '.pyw']
}
```

Notes: 
`enable` (default=`true`), used to enable/disable the code reload.
`watchDirs` (default: all the entries of the PYTHONPATH if justMyCode=false, otherwise all the non library entries of the PYTHONPATH), used to specify the directories to recursively watch (the extension could pass the `${workspace}` here if it wanted when `justMyCode=true`, but that's optional).
`pollTargetTime` (default=`3`), this is the target time for a single poll in seconds (the polling will throttle to avoid consuming cpu while scanning for changes -- lower values would be able to find about the changes earlier, but would also consume more cpu).
`ignoreDirectories` (default: `['.git', '__pycache__', 'node_modules']`), this can be used to skip directories for a faster directory scanning.
`fileExtensions` (default: `['.py']`), this can be used in case the user deals with some custom file extension.

So, with that, by default any client would have auto-reload turned on.

When a file change is detected, I'm thinking about just sending an 'output` event with a `console` category with the details on how the reload proceeded (i.e.: if it was possible to do the reload and what was updated), so, no further integration would be needed from the client side.

**Comment by int19h** [comment]
(@luabud, can you also take a look?)

I like the approach in general! Some bikeshedding on property names follows.

"watchDirs" should be "watchDirectories", for consistency with "ignoreDirectories".

I wonder if perhaps we could make "ignoreDirectories" and "fileExtensions" to use globs a la gitignore - does it complicate the implementation much? If it can be done, then we could turn them into two complementary properties like so:
```json5
"include": ["*.py", "*.pyw"],
"exclude": ["**/node_modules/**"]
```

And "pollTargetTime" could be something like "pollingInterval" for better clarity, and also for consistency with some other extensions (like WSL support) that use this terminology in similar circumstances.

**Comment by luabud** [comment]
This is super cool! +1 to Pavel's suggestions. 

Quick basic question, since this would be enabled by default, we wouldn't have to add this argument to our current existing launch.json entries, right? So users would only declare it they want to change something, e.g. which directories to watch?

**Comment by fabioz** [comment]
> Quick basic question, since this would be enabled by default, we wouldn't have to add this argument to our current existing launch.json entries, right? So users would only declare it they want to change something, e.g. which directories to watch?

Yes, it should work out of the box by default.

I'll take a look at supporting the glob format (which should be straightforward) and renaming those property names (if everything goes well I'll submit a pull request on Friday).

**Comment by karthiknadig** [comment]
We already have the "rules" which allow include and exclude patterns. I am wondering if this will add confusion, since this will be yet another set of rules to include or exclude files/dirs

**Comment by luabud** [comment]
@karthiknadig but rules isn't documented in the schema, is it? maybe we can add it too following the same convention?

**Comment by int19h** [comment]
I think it's fine, so long as we use top-level objects to provide clear scoping for "include" and "exclude", and we're consistent in how it works for both scopes.

**Comment by fabioz** [comment]
As a note, I got the code working but it still needs some cleanup (which should take one more day) before submitting a pull request  (so, my plan is providing the pull request on Thursday next week).

**Comment by vviikk** [comment]
Is there any documentation regarding this?

**Comment by karthiknadig** [comment]
@vviikk If you want to enable this, you can do so from the debug configuration. Look for the following setting:
![image](https://user-images.githubusercontent.com/3840081/118170864-752e9c80-b3df-11eb-88b6-58925f94740a.png)

These are the available values. This feature is not enabled by default. So you have to set `"enable": true`
```
      "autoReload": {
          "enable": true,
          "exclude": [
              "**/.git/**",
              "**/__pycache__/**",
              "**/node_modules/**",
              "**/.metadata/**",
              "**/site-packages/**"
          ],
          "include": [
              "**/*.py",
              "**/*.pyw"
          ]
      }
```
