### ISSUE TITLE
Debug REPL Evaluate code in any module

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#221]

**Comment by int19h** [comment]
No traction on this to date; closing until we decide we actually need it.

**Comment by oplatek** [comment]
Hello, I found the no traction comment funny.

I started using VSCode 3 months ago because of Copilot, and last week, I needed to do some serious debugging.

Because of missing REPL, I decided to debug the whole thing in Ipdb and even wrote a blog post about it.
https://opla.cz/2023/12/05/debugging-in-vscode/

To conclude at least me would appreciate the REPL greatly and I would return to debugging in VScode in stead of Ipdb :)

**Comment by int19h** [comment]
Debug Console is the VSCode equivalent of REPL. This issue is not about REPL in general, but specifically about one potential feature: evaluating code in that REPL in the context of an arbitrary module that is already loaded (so that this module's globals are your globals). Currently, Debug Console always evaluates things in the context of the stack frame that you have selected in the Stack pane, so unless module's top level is actively executing, there's no way to eval things in it without explicitly using `exec()` in the console.

**Comment by oplatek** [comment]
@int19h thank you for replying and mentioning [Debug Console](https://code.visualstudio.com/docs/editor/debugging#_debug-console-repl).
It seems exactly what I need.
