### ISSUE TITLE
Numeric key types are sorted like strings

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#223]
![image](https://user-images.githubusercontent.com/3840081/37372889-ac02e570-26d1-11e8-98af-68373bc34e73.png)

**Comment by fabioz** [comment]
Should this be actually done?

I mean, dicts are now being shown in the same insertion order (we could sort the keys if needed, but it's unclear when a dict should be shown ordered by insertion or sorted...).

If this is implemented we'd probably want to make it an option so that the user can choose how he wants to see it.

**Comment by int19h** [comment]
This was before all the Python versions we support had ordering guarantees for dicts. Ideally this should be something the IDE itself should do with the data it receives from DAP, so that the option can be toggled on the fly. But it didn't get any upvotes in all this time, so I think it's safe to close.
