### ISSUE TITLE
Breakpoints do not stop inside tf.data.Dataset map function

### ISSUE THREAD

**Issue by edurenye** [microsoft/debugpy#228]
##  Environment data

- Visual Studio Code and jupyterlab/debbuger (uses ptvsd)

See https://github.com/jupyterlab/debugger/issues/435#issuecomment-624566700 for more info and screenshots.

## Actual behavior

If in the code from below you set a breakpoint in the line `print('Dummy function')` it will not stop.
```
import tensorflow as tf

def read_tfrecord(x):
    print('Dummy function')
    return x

dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
print(dataset)
dataset = dataset.map(lambda x: read_tfrecord(x))
```

## Expected  behavior

The code execution should stop at that line and you should be able to debug that function.

## Steps to reproduce:
1. Write the previous code.
2. Set a breakpoint in the line `print('Dummy function')`.
3. Run the code.

See more in https://github.com/jupyterlab/debugger/issues/435

**Comment by int19h** [comment]
Do you know if Tensorflow spawns background threads to run the lambda on? If it does so, and doesn't use Python facilities (i.e. directly spawns native threads, and then just invokes Python code on them), then debugger will not be aware of those threads.

Detecting native threads is a long-standing issue that we've tried to resolve through various hacks, but ultimately it needs Python itself to provide an API to register a callback for every new thread that Python becomes aware of.

(Flowing through native code into a user callback is not a problem in and of itself, since most Python built-ins are also native code. )

**Comment by edurenye** [comment]
Thanks for your answer.

I have no idea how Tensorflow does it internally, so I created an issue there, maybe somebody that knows will answer.

**Comment by int19h** [comment]
If this really is what's happening, then adding `debugpy.debug_this_thread()` at the beginning of the function, it should work.

**Comment by edurenye** [comment]
It did not work, though I got the following message:

´´´
WARNING:tensorflow:AutoGraph could not transform <function _locked_settrace at 0x7f0fe2d73440> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: local variable 'kill' referenced before assignment
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
```

**Comment by edurenye** [comment]
The breakpoint does not work because the code is transformed to something else for the execution there, using 'eager execution' it can be debugged fine, so we can close this issue.

See https://github.com/tensorflow/tensorflow/issues/39320

Thank you very much everybody that helped and was involved in this issue!
