### ISSUE TITLE
Attach to remote process

### ISSUE THREAD

**Issue by puremourning** [microsoft/debugpy#247]
I'm not sure if this is a feature request, bug report, or just i'm using it wrong.

Scenario is that I have a process running on `remote-host` launched with the command `python -m debugpy --listen 0.0.0.0:9210 -m mymodule ....`

On `local-host` I am starting up `debugpy` 'adapter' and trying to use it to "attach" to `attach` to the process running on `remote-host`. I'm using this `attach` configuration, which worked with `vscode-python` but doens't with debugpy:

My DAP client (vimspector) starts a local copy of debugpy and sends it the followiong message:

```
2020-05-15 14:14:47,868 - DEBUG - Sending Message: {"command": "attach", "arguments": {"python": "/opt/rh/rh-python36/root/usr/bin/python3", "request": "attach", "host": "remote-host", "port": 9210, "name": "test"}, "seq": 1, "type": "request"}
```

After that all i get is:

```
2020-05-15 14:14:47,869 - DEBUG - Message received: {'seq': 4, 'type': 'event', 'event': 'debugpyWaitingForServer', 'body': {'host': '127.0.0.1', 'port': 55197}}
2020-05-15 14:14:47,869 - WARNING - User Msg: Unhandled event: debugpyWaitingForServer
2020-05-15 14:14:57,887 - DEBUG - Message received: {'seq': 5, 'type': 'response', 'request_seq': 1, 'success': False, 'command': 'attach', 'message': 'Timed out waiting for debug server to connect.'}
2020-05-15 14:14:57,887 - ERROR - Request failed: Timed out waiting for debug server to connect.

```

The full debugpy log for the `debugpy` running on `local-host` is here: https://gist.github.com/puremourning/84c40aecc03fe391355501ddd2940e9a (`remote-host` is actually `ukfd-ltp2l` )

The full log for the process running on `remote-host` requires anonymising, but it doesn't appear to indicate that the `local-host` version attempted to connect to it.

I was expecting the `local-host` adapter to connect to the process running on `remote-host` like other 'remote' debug adapters.

Am i doing it wrong ? How should this be done ? I coudn't find documentation for the debugpy attach request.

**Comment by puremourning** [comment]
Well i sort of made it work, if i tell the client to connect _directly_ to the remote debugpy it works. I guess that's what this is saying: https://code.visualstudio.com/docs/python/debugging#_remote-script-debugging-with-ssh

Is there no equivalent of the vscode-cpptools method where a local DA connects to a remote ptsd ?

**Comment by int19h** [comment]
Yep, when direction of connection for "attach" is client -> server, we assume that the client is going to take care of establishing a TCP transport for the DAP session (since VSCode added that ability, and the DAP spec was updated to allow for that - they call it "multi-session mode" in the overview).

However, we now also support the reverse: when the adapter waits for incoming connection from the server. In this case, the adapter is started by the client, so it works the same as with "launch". To use this mode, you need to use `--connect` rather than `--listen` when starting debugpy server, and do this in the debug config:
```json5
"listen": {
  "host": "localhost", // optional, default is 127.0.0.1
  "port": 5678
}
```

Side note: we made this symmetrical, so that when you tell the server to `--listen`, the config should use `"connect"`:
```sh
debugpy --listen 5678 ...
```
```json5
"connect": {"port": 5678}
```

This is the recommended syntax going forward, for clarity, and so that we can add direction-specific properties in the future. We still support top-level "host" and "port", and treat them as if they were inside "connect", but this is considered legacy syntax; although we aren't planning to drop it anytime soon.

**Comment by int19h** [comment]
BTW, I haven't tried it, but I think that you could also make this work by using `netcat` as the adapter on the client side, and telling it to connect to the socket on which the actual adapter is listening. It will then work as an stdio/socket bridge.

**Comment by puremourning** [comment]
Thanks again for the detailed explanation. As mentioned I was able to just tell vimspector to connect TCP directly to the host/port running the `remote` debugpy, which is fine.

> Side note: we made this symmetrical, so that when you tell the server to --listen, the config should use "connect":

That sounds like the equivalent of what I was trying to do.

BTW are all of the launch arguments doc'd somewhere ? I see things like 'sourceMapping' on the VScode website, but it's not actually defined anywhere that I could discern.

**Comment by int19h** [comment]
Some stuff is doc'd at https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings, but we've yet to fully update it with all the recent changes. On the other hand, https://code.visualstudio.com/docs/python/debugging is more complete, and covers stuff like "pathMappings", but is written with VSCode in mind.

**Comment by int19h** [comment]
Oh, I see that you meant *source* mapping. These aren't represented in the launch config, because it's not a one-off thing - rather, it's a similar mechanism that operates via custom DAP messages, to allow for dynamic changes in mapping. If you want to use it, you'd have to send those custom messages - but it's meant for rather specific scenarios (e.g. IPython support in VSCode uses it to map cells to editors).

@karthiknadig, do you recall if we document this stuff anywhere?

**Comment by puremourning** [comment]
You were right first time! I was being blind and didn't check the Wiki :(

It was `pathMapping` that I was on about - i.e. remote-to-local source path mapping.
