### ISSUE TITLE
Too much variable in the python console of VSCODE

### ISSUE THREAD

**Issue by ayeteng** [microsoft/debugpy#258]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. The python debug console become very complicated with a lot of special variables. (special variable & much more.) How can I hide the unnecessary variable like before? If possible to have a setting parameter in setup.

## Actual behavior
New version both 2020.5.80290 & 2020.5.78807
![bad_python](https://user-images.githubusercontent.com/12135212/82415165-b3ce9700-9aaa-11ea-8612-d84d60b276d4.png)

## Expected behavior
Old version 2020.4.76186
![old2](https://user-images.githubusercontent.com/12135212/82418093-22adef00-9aaf-11ea-87b9-f76f350e180d.png)

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local 
-   **Extension version:** 2020.5.80290
-   **VS Code version:** 1.45.1
-   **Setting python.jediEnabled:** true | false
-   **Python and/or Anaconda version:** 3.7.7
-   **OS:** Mac
-   **Virtual environment:** virtualenv

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by fabioz** [comment]
There's a setting for this:

`variablePresentation`

If you pass:

```
variablePresentation={
    "all": "hide",
    "protected": "inline",
}
```

in the launch configuration, it should behave the same way it did previously.

The keys accepted are: `special`, `function`, `class`, `protected`  and `all` (`all` sets the default for all the groups available). The valid values are: `group`, `inline`, `hide`, so, you should be able to customize as you'd like (I believe there are plans to set the default in the editor settings and automatically pass it in the launch, but I don't know if VSCode Python caught up with that already).

p.s.: this was actually done due to the following requests (https://github.com/microsoft/ptvsd/issues/763, https://github.com/microsoft/ptvsd/issues/1621).

@karthiknadig I don't think there's anything to do in the backend in this case, still, I'm leaving it open for you to decide whether something should still be done in the client/docs.

**Comment by int19h** [comment]
See https://github.com/microsoft/vscode-python/issues/12373

**Comment by JeremyDalby** [comment]
The variablePresentation setting only seems to hide some of the special variables and function variables.  Is there any way to hide all of them?

<img width="686" alt="image" src="https://user-images.githubusercontent.com/97484934/174409407-b67e78d6-b55b-4b5f-845b-5cad7b8053a8.png">

**Comment by int19h** [comment]
If you expand those groups, what are the variables under them? Or does it just show the empty group?

**Comment by JeremyDalby** [comment]
Inside "special variables", it show the special variables of the object's class, and inside "function variables", it shows the object's class methods.  In some cases they seems to be infinitely expandable.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/97484934/174643368-9096d23f-4551-49be-a3c5-c71db0e07882.png">

<img width="560" alt="image" src="https://user-images.githubusercontent.com/97484934/174644112-4861c8f0-9900-4b91-b595-ec6b131465fb.png">
