### ISSUE TITLE
SystemExit raised when debugging

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#273]
Still hasn't been fixed as of June 2020.

With my code being:

```python
import sys

while True:
  print('Type exit to exit')
  response = input()
  if response == 'exit':
      sys.exit()
  print('You typed ' + response + '.')
```

_Originally posted by @Thisisguillermo in https://github.com/microsoft/ptvsd/issues/982#issuecomment-637012192_

**Comment by karthiknadig** [comment]
@Thisisguillermo This issue is specifically for debugging tests. Your snippet looks like a plain console app - are you starting it via F5? If so, can you please file a separate issue, and include your launch.json and other steps necessary to repro?

_Originally posted by @int19h in https://github.com/microsoft/ptvsd/issues/982#issuecomment-637094245_

**Comment by Thisisguillermo** [comment]
@karthiknadig Thanks, I was just reporting it, it's not a real big issue since I'm learning Python.

**Comment by karthiknadig** [comment]
@Thisisguillermo Just wanted to check. Do you have "Raised Exceptions" ticked?
![image](https://user-images.githubusercontent.com/3840081/83562695-dca15400-a4ce-11ea-9b61-2323bfd5e2b6.png)

If so then it is expected that the debugger will break on `sys.exit()`.

**Comment by Thisisguillermo** [comment]
@karthiknadig Thanks.

**Comment by danielniccoli** [comment]
@karthiknadig @gllrmzndm 

The behavior of debugpy is not in compliance with the specifications. Because the underlying issue is broader, I raised a separate ticket on the matter, which explains the problem and suggests a solution that should not only fix the issue you are having, but other issues as well. Unforatunately, it was closed and moved to a discussion. Please contribute, if you wish to see it fixed.

The issue: https://github.com/microsoft/debugpy/issues/1590
The discussion: https://github.com/microsoft/debugpy/discussions/1591
