### ISSUE TITLE
debugger breaks on FileNotFoundError

### ISSUE THREAD

**Issue by dvirtz** [microsoft/debugpy#281]
## Environment data

-   VS Code version: 1.45.1
-   Extension version (available under the Extensions sidebar): 2020.5.86398
-   OS and version: MacOS Catalina
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pyenv
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Jedi
-   Value of the `python.languageServer` setting: Microsoft

## Expected behaviour

Debugger doesn't break on checked exceptions when `Raised Exceptions` is unchecked in `breapoints` window.

## Actual behaviour

Debugger breaks with `Exception has occurred: FileNotFoundError` error.

## Steps to reproduce:

Debug the following code:

```python
try:
    content = open('NO_SUCH_FILE', 'rb').read().decode('utf-8')
except Exception:
    content = 'unknown'
```

**Comment by int19h** [comment]
There are two issues here. 

The first one is that the "user unhandled" item is showing up at all. Showing it in the UI was not intended for this release, since we're still figuring out the UX specifics for VSCode integration. We'll fix this ASAP.

The second issue is with the implementation of "user unhandled". It looks at the call stack to see if the outer frame is user code or not - but that's not correct in cases where the exception is raised and then immediately caught in the same frame, and the outer frame is non-user-code.

**Comment by int19h** [comment]
@fabioz, can you take a look at the latter? This might require some brainstorming to cover all the corner cases. The obvious approach is to wait until the frame in which the exception is raised returns to the caller, because by then we definitely know if the exception was handled or not in that frame - if it returns to the caller with unhandled exception, and caller is non-user-code, then it's definitely okay to report.

The problem, of course, is that we lose the context of the exception - actual the call stack wouldn't have that frame anymore. So this might require a hack similar to what's done for unhandled exceptions, where pydevd reconstructs the original stack from exception trace, and reports it in lieu of the actual Python stack at the point where the exception is detected as unhandled.

**Comment by int19h** [comment]
@rchiodo I don't think this affects your particular scenario, but FYI.

**Comment by fabioz** [comment]
Some feedback here:

I'm still working on the best way to handle it.

After some failed attempts, I think that the best way to deal with it will be doing something close to what is done when dealing with unhandled exceptions in the main module on attach (where there's no back frame and if the exception isn't dealt with in that frame there's no other place to stop).

Handling the library frames to notify can work too, but the solution is not ideal due to performance issues (right now we can completely skip tracing of those frames and that wouldn't be the case anymore). Also, implementation wise, having another special tracer for this case is not ideal.

As for the context of the exception, the trace has all the info... right now I'm showing the place where it goes from user code to library code, but I could show the original location too (I don't think there's a way to say: here is the full exception trace and we're stopped at this particular frame in the DAP).

**Comment by fabioz** [comment]
Ok, this is fixed now in the debugger side... the UI is still disabled though (@int19h @karthiknadig waiting for feedback on whether you want me to re-enable it in a commit or if it'll go through some experiment).

**Comment by int19h** [comment]
We're still thinking how to best surface it in VSCode UI to avoid confusion, so yep, it'll likely be a gradual rollout via experiments.
