### ISSUE TITLE
VS Code improperly escaping args in launch.json

### ISSUE THREAD

**Issue by dansavio** [microsoft/debugpy#287]
## Environment data

-   VS Code version: 1.45.1
-   Extension version (available under the Extensions sidebar): XXX
-   OS and version: Debian 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.3

## Expected behaviour
I need to pass command line arguments to my application, so I edited my launch.json file's "args" parameter to include the command line args I need.  Everything used to work well in the past, but now when one of my args contains either a single-quote character inside the string (') or an escaped double-quote character (\"),  the argument that gets passed to the command line contains a backshash before the single quote or the double quote.  I need the argument to get passed to the command line as-is, without any additional escaping done by VS Code.

For instance, I have:
"args": [
                "'a:[1,2],b:[3,4]'",
            ]

(Notice that there is a single quote after the double-quote at the beginning, and a single quote before the double quote at the end)
## Actual behaviour

The argument gets passed to the command line as:   \\'a:[1,2],b:[3,4]\\'

It should not contain those backslashes.

**Comment by int19h** [comment]
Can you clarify what you expect the behavior of those single quotes to be? If they're meant to be seen by the app when it inspects `sys.argv` (i.e. `sys.argv[1] == "'a:[1,2],b:[3,4]'"), then quoting them is the right thing. If you want the entire string to be implemented as a single command line argument (i.e. `sys.argv[1] == "a:[1,2],b:[3,4]"), you shouldn't need those single quotes at all - the argument will automatically be quoted as necessary to achieve this.

In general, every argument in "args" is supposed to map to exactly one command line argument for the debuggee. This necessitates shell-escaping any special characters in the argument that might break that. We do not provide any facility that would allow you to provide a complete command line as a single string; and there are no means for us to implement such a thing, since all underlying APIs that we use expect an argument list, not a raw string.

**Comment by dansavio** [comment]
> Can you clarify what you expect the behavior of those single quotes to be? If they're meant to be seen by the app when it inspects `sys.argv` (i.e. `sys.argv[1] == "'a:[1,2],b:[3,4]'"`), then quoting them is the right thing to do. If you want the entire string to be implemented as a single command line argument (i.e. `sys.argv[1] == "a:[1,2],b:[3,4]"`), you shouldn't need those single quotes at all - the argument will automatically be quoted as necessary to achieve this.
> 
> In general, every argument in "args" is supposed to map to exactly one command line argument for the debuggee. This necessitates shell-escaping any special characters in the argument that might break that. We do not provide any facility that would allow you to provide a complete command line as a single string; and there are no means for us to implement such a thing, since all underlying APIs that we use expect an argument list, not a raw string.

I want the single quotes to be seen by the app when it inspects sys.argv (the case where you state quoting is the right thing to do).  In the above example, I want the actual argument that gets passed to the command line to be exactly:

'a:[1,2],b:[3,4]'

I cannot get VS Code to pass the argument to the command line like that, because it inserts backslashes before each of the single quotes as I noted above.  This behavior did not happen several versions back in VS.

**Comment by int19h** [comment]
Which shell are you using? It's actually VSCode itself that performs the quoting in this case, and it has several branches for different terminal types, but perhaps it's just not detecting it correctly for you?

**Comment by dansavio** [comment]
I'm using zsh  (Linux)

**Comment by int19h** [comment]
Ah, now I see the problem! For zsh, square brackets are glob syntax, so it will try to expand them unless they're escaped.

And one thing that we changed in debugpy recently is that it will pass "args" via terminal shell, allowing the shell to expand anything that it wants to expand - stuff like `*` and `?` globs, environment variables etc (#86). So this would explain why you're getting an error about "no matches found" - it's because there are no filenames matching the glob.

Now, there is a way to disable this. Add this to your debug configuration in launch.json:
```json5
"argsExpansion": "none",
```
(You will get squiggles, because we haven't updated the JSON schema yet - this is tracked by https://github.com/microsoft/vscode-python/issues/11678 - however, the setting should work regardless.)

Please let me know if this solves the problem.

**Comment by dansavio** [comment]
Adding "argsExpansion": "none"   does indeed fix my problem.   Thank you!

**Comment by jeff-hykin** [comment]
This fails for me. Adding that argument to the launch.json causes none of the arguments to be passed. 
VS Code
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d

Commandline argument with normal launch.json
```
cd /Project ; /usr/bin/env /Project/.venv/bin/python /home/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/lib/python/debugpy/launcher 52874 -- run.py -- -s a2c -t 1000 -d CartPole-v1 -e 2000 -a 0.001 -g 0.99 -l [64,64]
zsh: no matches found: "[64,64]"
```
First Launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "A2C",
            "type": "python",
            "request": "launch",
            "program": "run.py",
            "console": "integratedTerminal",
            "args": [
                // fails because VS Code isn't quoting the args
                "-s", "a2c", "-t", "1000", "-d", "CartPole-v1", "-e", "2000", "-a", "0.001", "-g", "0.99", "-l", "[64,64]",
            ],
            // "argsExpansion": "none",
        }
    ]
}
```

Commandline args with `"argsExpansion": "none"`
```
/usr/bin/env /Project/.venv/bin/python /home/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/lib/python/debugpy/launcher 53691 -- run.py 
```

**Comment by JHaller27** [comment]
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.11.0-7614-generic

Adding `"argsExpansion": "none"` works for me.

**Comment by JHaller27** [comment]
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.11.0-7614-generic

The OS is lying. `lsb_release -a` shows:
```
Distributor ID:	Pop
Description:		Pop!_OS 20.10
Release:		20.10
Codename:		groovy
```

Same as jeff-hykin - no arguments are passed with "argExpansion": "none".

**Comment by jeff-hykin** [comment]
An easy fix would be for all arguments on non-windows systems to replace all single quotes with `'"'"'` and then wrap each argument in single quotes. It's way more cross-shell reliable than trying to backslash escape every special character.

**Comment by parkitny** [comment]
None of these fixes are working for me. I have a launch config where one of the arguments is a string with single quotes that contains a space. VSCode always escapes the single quotes, is there a way to disable that behaviour? Config sample:

```
        ....
        {
            "name": "Python: rasterise",
            "type": "python",
            "request": "launch",
            "program": "./terrain/cli.py",
            "args":[
                "rasterise-labels",
                "--input-filename",
                "'zip://path/to/zipfile.zip!Some Folder With Spaces'",
                "--destination-path",
                "path/to/output"
            ],
            "console": "integratedTerminal"
        }
        ...
```

Running this as a debug config executes the following:

```
/bin/env /home/user/anaconda3/envs/terrain/bin/python /home/user/.vscode/extensions/ms-python.python-2021.5.926500501/pythonFiles/lib/python/debugpy/launcher 40325 -- ./terrain/cli.py rasterise-labels --input-filename "\'zip://path/to/zipfile.zip!Some Folder With Spaces\'" --destination-path path/to/output
```

Whereas the command I want to execute should have the following form:

```
/bin/env /home/user/anaconda3/envs/terrain/bin/python /home/user/.vscode/extensions/ms-python.python-2021.5.926500501/pythonFiles/lib/python/debugpy/launcher 40325 -- ./terrain/cli.py rasterise-labels --input-filename 'zip://path/to/zipfile.zip!Some Folder With Spaces' --destination-path path/to/output
```

Is there a way to achieve this?

**Comment by fabioz** [comment]
I think the culprit is probably: https://github.com/microsoft/vscode/issues/125934

Have you tried not using a diferent console? i.e.: instead of `integratedTerminal`, try to use `internalConsole`

**Comment by fabioz** [comment]
Or maybe if it automatically adds the quotes, try removing the `'`.

**Comment by parkitny** [comment]
Thanks, I tried your first suggestion and it looks like the debugger tries to run for a second but then terminates, probably from error, tried externalConsole with similar behaviour. Opens an external console which shuts down after a second or two.

The problem is that the command I want to run needs the argument with spaces to be single quoted. I've tested that outside of vscode environment, double quotes wont work. That's running with raw python 3.9.

**Comment by parkitny** [comment]
> I think the culprit is probably: [microsoft/vscode#125934](https://github.com/microsoft/vscode/issues/125934)
> 
> Have you tried not using a diferent console? i.e.: instead of `integratedTerminal`, try to use `internalConsole`

Yes I think you are right that the linked issue covers the same problem I described. Thanks for linking.

**Comment by jeff-hykin** [comment]
Sorry @parkitny when I talked about my fix I meant vs code needs to implement that. VS code is the one automatically escaping argument with backslashes, which is the cause of the problem. If they stopped escaping with backslashes and instead used a single quote method, it wouldn't be a problem.
