### ISSUE TITLE
Can't attach to remote process on Ubuntu when the remote machine has two versions of Python and debugpy is installed only in one python environment

### ISSUE THREAD

**Issue by mkashif14** [microsoft/debugpy#316]
## Environment data

- **debugpy version**: 1.0.0b5 (on both the machines - local and remote)
- **Local OS and version**: Windows 10 (Version 2004)
- **Local Python version** (& distribution if applicable, e.g. Anaconda): CPython 3.7.5 (64-bit)
- **Using VS Code or Visual Studio:** VS Community 2019 (Version 16.6.1)
- **Remote OS and version:** Linux-4.9.0-6-amd64-x86_64-with-debian-9.4 x86_64
- **Remote Python versions:** CPython 3.5.3 (64-bit) and CPython 2.7.13 (64-bit) 

## Actual behavior

On my remote Linux machine, I have two versions of Python - 3.5.3  and 2.7.13. Initially, I installed debugpy for Python 3.5.3 only and ran my first python 3.5.3 script for remote debugging. When I tried attaching to the remote process from VS on my local machine, I got the below error.
![image](https://user-images.githubusercontent.com/34096765/85856174-267f1080-b7d5-11ea-9a2f-1aba1e618cc3.png)

After much troubleshooting and looking for answers, I just randomly went ahead and installed debugpy for python 2.7.13 as well on the remote machine. That did the trick and I was successfully able to attach to the remote process.

And now that I have removed debugpy from python 2.7 environment, even then the attach to remote process is working.

## Expected  behavior
I would expect debugpy to look for the installation path on the remote machine/server only for the python environment it's running against.

**Comment by int19h** [comment]
For remote attach, this error message has absolutely nothing to do with the version of debugpy on the remote machine. On remote, you're manually launching debugpy server (either via command line - `python -m debugpy` - or by using `import debugpy` etc). The version of debugpy that you use is thus under your full control.

On the machine on which VS runs, it comes with a bundled version of debugpy. But even then, for attach, it shouldn't need it at all, because the adapter runs remotely in that case - VS just attaches to the socket that said remote adapter opens.

So, this error message is still a VS integration issue, and not a debugpy issue. Can you please re-open the referenced bug in the PTVS repo, and follow up there instead?

**Comment by mkashif14** [comment]
Thanks @int19h for the explanation. I have opened this issue under PTVS - https://github.com/microsoft/PTVS/issues/6156
