### ISSUE TITLE
Does this support calling bash script which then calls python script?

### ISSUE THREAD

**Issue by dwbelliston** [microsoft/debugpy#324]
Im trying to do something like

```
command: -c "pip3 install debugpy -t /tmp && python3 /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -c </glue/bin/gluesparksubmit /opt/src/main.py>"
```

I see in file https://github.com/microsoft/debugpy/blob/4331cf54c0156338d5179b8f5f54126035d448c5/src/debugpy/server/cli.py#L320 - there is a 'run_code' method that might be the general idea of what i am trying to achieve but not sure this is intended use.

**Comment by int19h** [comment]
We didn't doc "code" properly yet, but https://github.com/microsoft/vscode-python/issues/12500 mostly explains it. It's the equivalent of `python -c ...`.

So it doesn't apply to your scenario. In general, we do need to control the command line passed to Python, so intermediate scripts like that aren't supported - unless they're themselves written in Python, and the code that you want to debug runs in that same process, or a child process that is started directly by Python code (i.e. no intermediate bash scripts there, either). I'm not familiar with `gluesparksubmit`, so I don't know if doing an equivalent in Python is possible.

I think you can do `pip install` via a pre-launch task (look for `preLaunchTask` at https://code.visualstudio.com/docs/editor/debugging).

**Comment by int19h** [comment]
Oh, and keep in mind that there's also the API to spin up the debug server - this is more ugly, since you need to explicitly call it from the code you're trying to debug. But the advantage is that it doesn't matter how that process is started - so long as you can invoke `listen()` before the code you want to debug is executed (in the same process), it should work.

https://github.com/microsoft/debugpy/wiki/API-Reference
