### ISSUE TITLE
Python remote breakpoint to Raspberry Pi is not working with VS2019

### ISSUE THREAD

**Issue by mosbaker** [microsoft/debugpy#341]
## Environment data

- debugpy version: XXX (run `import debugpy; print(debugpy.__version__)` if uncertain) - 1.0.0b12
- OS and version: Raspbian - Raspberry Pi
- Python version (& distribution if applicable, e.g. Anaconda): 2.7
- Using VS Code or Visual Studio: VS2019

## Actual behavior

Python remote breakpoint to Raspberry Pi is not working

I set these on remote machine:
export PATHS_FROM_ECLIPSE_TO_PYTHON='[["c:\temp\a\", "/home/pi/moshe_bluePy_bu/"]]'
export DEBUGPY_LOG_DIR="/home/pi/moshe_bluePy_bu/"

However no logs produced either.
I also checked debugpy version on VS2019 - it is the same as in the remote.

This is a spin off from this thread:
https://github.com/microsoft/debugpy/issues/307#issuecomment-662827586

Thanks,
Moshe

**Comment by int19h** [comment]
Can you tell more about how you're starting the debugpy server on Pi? i.e. command line if you're using that, or source if you're doing `import debugpy` etc.

**Comment by mosbaker** [comment]
attached most basic python file

[test_debug.zip](https://github.com/microsoft/debugpy/files/4964695/test_debug.zip)

**Comment by int19h** [comment]
How does the process get launched? Are you connecting to Pi directly via `ssh`, and then starting it with `python test_debug.py` in the same shell in which the variables were exported? 

The fact that `DEBUGPY_LOG_DIR` doesn't trigger log creation is very disturbing, because it's supposed to be the single most reliable method to enable them. So I suspect that something is interfering with the environment - which would then also explain why `PATHS_FROM_ECLIPSE_TO_PYTHON` isn't having the desired effect.

One other thing that might be worth doing is `import os; print(os.environ)` in your sample - that would at least give us a clear picture of *what* environment the debugged process gets, and that might make it easier to figure out the why.

**Comment by mosbaker** [comment]
I run the python script on command line and then remote connect to the process from VS2019 using Connection type: Python remote (debugpy). See link of what I followed:
https://docs.microsoft.com/en-us/visualstudio/python/debugging-python-code-on-remote-linux-machines?view=vs-2019

"Are you connecting to Pi directly via ssh, and then starting it with python test_debug.py in the same shell in which the variables were exported?"
Yes

I added the print os.environ:

{'LANG': 'en_GB.UTF-8', 'SUDO_COMMAND': '/bin/su', 'SUDO_GID': '1000', 'SHELL': '/bin/bash', 'NO_AT_BRIDGE': '1', 'SHLVL': '1', 'SUDO_UID': '1000', 'PATHS_FROM_ECLIPSE_TO_PYTHON': '[["c:\\temp\\a", "/home/pi/moshe_bluePy_bu/"]]', 'DEBUGPY_LOG_DIR': '/home/pi/moshe_bluePy_bu/', 'TERM': 'xterm', u'PYDEVD_DEBUG_FILE': '/home/pi/moshe_bluePy_bu//debugpy.pydevd.log', 'MAIL': '/var/mail/root', 'PWD': '/home/pi', 'LOGNAME': 'root', 'USER': 'root', u'PYDEVD_DEBUG': 'True', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'HOME': '/root', 'SUDO_USER': 'pi', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', '_': '/usr/bin/python'}

**Comment by fabioz** [comment]
Have you done the change in this comment: https://github.com/microsoft/debugpy/issues/307#issuecomment-651231991 (to be able to set the client `OS` as Windows so that the paths are corrected)?

If you can't get it to work, please provide the pydevd logs/stdout -- I'm more interested in the pydevd logs for this case as the debugpy logs won't cover this -- although it's pretty strange that it's not there... are you setting it in the env prior to launching the executable? The fact that `PYDEVD_DEBUG_FILE` is a unicode seems to indicate that you're setting it from within the process, but it needs to be set before `pydevd` itself is imported (so, please set it at the shell and not from within the process).

Note that in this case you also have to fix the `PYDEVD_DEBUG_FILE` path, which doesn't seem correct (it has a `//` in it).

**Comment by int19h** [comment]
@fabioz debugpy [automatically sets](https://github.com/microsoft/debugpy/blob/499bbb2a1ec0f8a7c97d4c0869a63915b7eb926b/src/debugpy/_vendored/force_pydevd.py#L23-L26) `PYDEVD_DEBUG` and `PYDEVD_DEBUG_FILE` if `DEBUGPY_LOG_DIR` is set, so that's where it's coming from. The double slash in the path should be fine, since every supported OS just collapses them into a single slash.

Could the use of Unicode strings on 2.7 cause a problem here? But even then, I would expect `debugpy.server*.log` to be there at the minimum...

**Comment by int19h** [comment]
@mosbaker Can you try it with a recent version of debugpy? It fixes the issue with Unicode `"PYDEVD_DEBUG_FILE"`, so if that was the reason why logs weren't being written, we might be able to get some now.

**Comment by BrendanSimon** [comment]
I'm having a similar issue on another ARM based system (running Debian 10 Buster, and Python 2.7.16.

I installed `debugpy` manually (as board is not connected to internet) by downloading the wheel directly from PyPI.  I couldn't find an arm variant so figured the `any` variant should be ok.

https://files.pythonhosted.org/packages/0a/c4/b8c66a9947d586b8b836d4c82bfc6bcddc70b157e3e19d0527771baae724/debugpy-1.2.1-py2.py3-none-any.whl

I tried implementing the `os = 'WINDOWS'` kludge as mention in [#307 comment](https://github.com/microsoft/debugpy/issues/307#issuecomment-651231991), but could not `import pydevd_file_utils`

Is this a dependency?  Do I need to install `pydevd_file_utils` or `pydevd`?

**Comment by BrendanSimon** [comment]
Manual download of `pydevd` - install failed.

```
# pip install /mnt/data/tmp/pydevd-2.2.0-py3-none-any.whl 
pydevd-2.2.0-py3-none-any.whl is not a supported wheel on this platform.
```

I presume this is because I'm using Python 2.7.16.  Is there a way to get this working with Python 2.7?

**Comment by BrendanSimon** [comment]
I'm installing 'pydevd' on the target.  Maybe I should be on the remote dev host?

NOTE: I am using vscode on WIndows, my source files are on a VirtualBox Linux VM which I edit via Remote SSH extension.  Debugging my unit tests with pytest is fine.

I'm now trying to do proper remote debugging from vscode to the target arm platform :)

**Comment by BrendanSimon** [comment]
I got it working.  I didn't understand the pathMapping settings.  The docs aren't clear enough (for me).

I used the default that I copied from the net.

```
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": ".",
                }
```

My source code on dev lives in a folder called `root/opt/sbin/` and gets installed on the target in `/opt/sbin/`.  So the following settings got breakpoints working for me.

```
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}/root/opt/sbin",
                    "remoteRoot": "/opt/sbin",
                }
```

Hope that helps somebody else.  Sorry for the noise.

**Comment by int19h** [comment]
Please re-open if this issue is still reproducible.
