### ISSUE TITLE
Debugger crashes when expanding a string loaded from a numpy file

### ISSUE THREAD

**Issue by jakelevi1996** [microsoft/debugpy#395]
- VSCode Version:
Version: 1.48.2 (system setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
- OS Version: Windows 10 64-bit
I'm using Python 3.7.6, Numpy version 1.18.1.
Python extension version: v2020.8.105045
Using a virtual environment: No

Steps to Reproduce:

1. I have the following code in a Python module called `temp.py`:
```
import numpy as np

a = np.arange(1, 5)
b = np.arange(-1, 7)
c = np.arange(3, 10)
d = np.arange(11, 17)

np.savez("temp", a=a, b=b, c=c, d=d, name="name", verbose=True)
with np.load("temp.npz") as data:
    print(data)
    print(data["name"])
    print(type(data["name"]))
    pass
```
2. I have a breakpoint on the `pass` statement
3. I launch the debugger using the "Python: current file" option
4. After reaching the breakpoint, in the debug console, I enter `data["name"]`, which returns the output `array('name', dtype='<U4')`
5. I click on the arrow to expand the attributes of this object, and then the debugger crashes, with the error message `Server[1] disconnected unexpectedly`

Note: this issue has been referred from [here](https://github.com/microsoft/vscode/issues/105683).

**Comment by fabioz** [comment]
I believe this is already fixed in: https://github.com/microsoft/debugpy/commit/44b01c81657f21ed12632317e15bd368e6d516ab

In particular, the fix is the try..except in `https://github.com/microsoft/debugpy/blob/44b01c81657f21ed12632317e15bd368e6d516ab/src/debugpy/_vendored/pydevd/pydevd_plugins/extensions/types/pydevd_plugin_numpy_types.py#L81` (so, you should be able to open that file locally and do the try..except in your local contents until a new release is done).

**Comment by int19h** [comment]
Closing as presumably fixed - please re-open if you run into this issue again.
