### ISSUE TITLE
Debugger does not recognize that exception is handled in single line except statement scenario

### ISSUE THREAD

**Issue by huguesv** [microsoft/debugpy#404]
## Environment data

- debugpy version: 1.0.0rc2 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: Windows
- Python version (& distribution if applicable, e.g. Anaconda): 3.7 64-bit
- Using VS Code or Visual Studio: Visual Studio

## Actual behavior

Debugger breaks on exception when it shouldn't given the exception is handled. Break on thrown is 'off'.

## Expected  behavior

Debugger does not break on exception

## Steps to reproduce:
1. pip install `beautifulsoup4` and `lxml` in Python 3.7
2. debug this code:

```
from bs4 import BeautifulSoup

def has_cost(tag):
    try: class_names = tag.attrs['class']
    except: return False
    return True

shtml = "<html><head><title>The Dormouse's story</title></head>"
soup = BeautifulSoup(shtml, 'lxml')
soup_row_cost_arr = soup.find_all(has_cost)
print(soup_row_cost_arr)
```

result: breaks on exception thrown
![image](https://user-images.githubusercontent.com/1696845/92286672-858b9080-eebc-11ea-9cac-a252c4ca14be.png)

change the implementation to have the return statement on its own line like this:
```
def has_cost(tag):
    try: class_names = tag.attrs['class']
    except: 
        return False
    return True
```

result: does not break, it correctly recognizes that it is handled

exception settings:
![image](https://user-images.githubusercontent.com/1696845/92286841-f632ad00-eebc-11ea-8b4d-8d6679b19912.png)

logs for both scenarios:
[one-liner-breaks.txt](https://github.com/microsoft/debugpy/files/5177070/one-liner-breaks.txt)
[two-liner-no-break.txt](https://github.com/microsoft/debugpy/files/5177072/two-liner-no-break.txt)

from developer community feedback at https://developercommunity.visualstudio.com/content/problem/1158181/python-exception-in-try-block-stops-in-debugger.html?childToView=1173634

**Comment by fabioz** [comment]
I'll start to take a look at this.

**Comment by fabioz** [comment]
Note: from the logs it's possible to see that the filter is for `userUnhandled`. i.e.: 
```
{"type":"request","command":"setExceptionBreakpoints","arguments":
{"filters":[],"exceptionOptions":[
    {"breakMode":"userUnhandled","path":[{"names":["Python Exceptions"]}]},
    {"breakMode":"unhandled","path":[{"names":["Python Exceptions"]},
{"names":["GeneratorExit","IndexError","StopIteration","AttributeError","KeyError"]}]}]},"seq":12}
```

So, the correct thing here is to actually break.

**Comment by fabioz** [comment]
I'm still working on this...

@int19h as this is an issue on user handled exceptions, maybe we should only enable those on a default build when this is fixed 
(hopefully I'll be able to provide a fix today).

**Comment by fabioz** [comment]
Unfortunately I still haven't been able to fix it... let me try to give some feedback on why this happens and why this is tricky:

During Python tracing, Python does not provide a way to know whether we're exiting because of an exception or because of a return (it provides a tracing for the exception and another for the return), so, to differentiate we analyze the bytecode and obtain the information on where the `try` started and where's the `except` and possible `raise` statements.

With that the debugger uses some heuristics based on where the `return` of the function is being called. Until now, if it exited in the `except` line this meant that the exception was unhandled, but in this particular case, both the `except` and the `return` are at the same line, so, the debugger thinks that it's returning due to the unhandled exception in the `except` line instead of the `return` that's in the same line.

I still haven't discovered a really good way to differentiate here -- what I thought for now is checking the `arg` in the tracing during return (which apparently is always `None` on an exception, so, it'd fix this particular case) or trying to discover the list of exceptions that were handled (but the exception name could actually come from some call or an alias, in which case it's also not perfect).

So, I'm still investigating... I'll spend at most one more day checking if I can come up with a better approach, if I can't I'll probably do the pragmatic thing and just additionally check if the return value is really `None` -- this won't work in the case where the `return` on the except line actually returns `None`, but this is such an odd construct that I think it should be reasonable.
