### ISSUE TITLE
Conditional breakpoint is still triggered when expression value is false

### ISSUE THREAD

**Issue by molly-w** [microsoft/debugpy#407]
## Environment data

-   VS Code version: 1.48.2
-   Extension version (available under the Extensions sidebar): python v2020.8.106424
-   OS and version: windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.8.5-64bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Value of the `python.languageServer` setting: pylance

## Expected behaviour

when the expression value is false, debug will skip the breakpoint and it won't be triggered

## Actual behaviour

even though the expression value is false, the breakpoint is still  triggered
![image](https://user-images.githubusercontent.com/63043224/92360283-24afc280-f11f-11ea-8d2e-a7e065bfb719.png)

## Steps to reproduce:
I have following two python files in the same directory:
**main.py**
```
from module import f1
f1()
```

**module.py**
```
import traceback
def f1():
    print('f1')
    print(traceback.extract_stack()[-1].filename)
    print(traceback.extract_stack()[-2].filename)
    f2()

def f2():
    print('f2')
    print(traceback.extract_stack()[-1].filename)
    print(traceback.extract_stack()[-2].filename)
```
I started VSCode in the directory and set conditional breakpoints with following expression :
`traceback.extract_stack()[-2].filename != traceback.extract_stack()[-1].filename`
on the first print statement in f1() and f2().

## Logs

The running of main.py printed out :
```
f1
c:\Users\...\tmp\pythonTest-breakpoint\module.py
c:\Users\...\tmp\pythonTest-breakpoint\main.py
f2
c:\Users\...\tmp\pythonTest-breakpoint\module.py
c:\Users\...\tmp\pythonTest-breakpoint\module.py
```
Both breakpoints are triggerred.
Why the breakpoint in f2() get triggerred whereas the condition is not met ?

**Comment by karthiknadig** [comment]
Using `traceback.extract_stack()` as a breakpoint condition might lead to this. At the point where we evaluate breakpoint condition, the stacks will show debugger internal frames. So you will get different results there.
![image](https://user-images.githubusercontent.com/3840081/93281912-029eeb80-f782-11ea-82a6-33249323cee3.png)

**Comment by molly-w** [comment]
Thanks for your answer, but why the output of two print() sentences are the same, and in your debug console, they're different.

**Comment by karthiknadig** [comment]
This is because when the condition is evaluated, it is evaluated in the debugger, so the value of `traceback.extract_stack()` will be different there. But when you call `print(traceback.extract_stack())`. The stack trace would be calculated at the point where print is called. The location where that `traceback.extract_stack()` gets called is why you get different answers. To make this work right you could do this:
```py
import traceback
def f1():
    stack = traceback.extract_stack()
    print('f1')
    print(traceback.extract_stack()[-1].filename)
    print(traceback.extract_stack()[-2].filename)
    f2()

def f2():
    stack = traceback.extract_stack()
    print('f2')
    print(traceback.extract_stack()[-1].filename)
    print(traceback.extract_stack()[-2].filename)
```
Use this as the condition:
`stack[-2].filename != stack[-1].filename`

**Comment by molly-w** [comment]
No offense, but i don't understand your change to code, because the two print() content in f2() is still the same:

![tempsnip](https://user-images.githubusercontent.com/63043224/93300737-ee162e00-f829-11ea-8e92-b42d226f1858.png)

**Comment by karthiknadig** [comment]
Every time you call `traceback.evaluate_stack()` is called stack that it returns is re-built based on the location where it is called. So, the `print` wont change because the context of calling `traceback.evaluate_stack()` is the f1/f2 function `module.py` file. When you use `traceback.evalaute_stack()` in a condition, it is evaluated in the context of this file https://github.com/microsoft/debugpy/blob/44b01c81657f21ed12632317e15bd368e6d516ab/src/debugpy/_vendored/pydevd/pydevd.py#L733-L742 . Think about it like this, when a condition is tested, `traceback.evaluate_stack()`  will be called in  `handle_breakpoint_condition` inside `pydevd.py`. So the stack you get when doing condition evaluations is different from when it is called in `module.py`.

The change I recommended was to do `stack = traceback.evaluate_stack()` in `module.py` and use 'stack' (local variable) in the condition. This way, when testing for condition we don't re-evaluate the stack, and will use the stack value as it would be in the context where you expect it to be.

If this does not answer your question, I recommend asking this on stackoverflow.
