### ISSUE TITLE
Long strings in variable inspection get truncated

### ISSUE THREAD

**Issue by UnHumbleBen** [microsoft/debugpy#410]
Essentially the Python Version of this issue for Go: https://github.com/microsoft/vscode-go/issues/868

## Environment data

-   VS Code version: 1.49.0
-   Extension version (available under the Extensions sidebar): v2020.8.109390
-   OS and version: Linux x64 5.4.0-42-generic snap
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: Jedi

## Expected behaviour

When trying to debug a long string, it gets truncated. This is fine for display purposes, but if I then right click on the value and click "copy value", I should expect my clipboard to get the real value of the string, not the truncated version.

## Actual behaviour

I get the truncated version copied to my clipboard
 
## Steps to reproduce:

1. Make this python file:

```python
MAX_LIMIT = 65538

string = 'a' * (MAX_LIMIT + 10)

pass
```
2. Set breakpoint at `pass` and debug.
3. Try to `Copy Value` the `string` variable

You will find that when the copied value will be of length 65538 instead of the expected 65548 and that part of the string have been replaced with ellipsis (...)

I choose length of 65538 because this is seems to be the maximum length for which VS Code will not truncate the string. The exact number may vary for different systems.

**Comment by int19h** [comment]
We have to truncate at some point, because otherwise the debugger simply hangs if you happen to be stepping through a code that has, say, a string or a bytearray with a few million elements - the data has to be transferred over the wire, and it's a single channel for everything.

A better way to do this would be for VSCode to provide some UX to access the complete raw value of the variable, similar to [how VS does this](https://docs.microsoft.com/en-us/visualstudio/debugger/view-strings-visualizer?view=vs-2019). The Debug Adapter Protocol currently doesn't have this standardized, but VS has an [extension](https://github.com/microsoft/VSDebugAdapterHost/wiki/Stack-Trace-and-Value-Formatting#valueformat-object) for it, and we already implement that extension. So it'll light up in VSCode, as soon as it implements that extension (presumably after it's added to the DAP standard).

**Comment by nmay231** [comment]
I'm assuming this is the same issue that truncates other types (like lists) as well, correct?

The VSCode team has recently implemented the protocol and shown how it is done in [this issue comment](https://github.com/microsoft/vscode/issues/27950#issuecomment-613281366). DebugPy just has to implement it :smiley:. There is another issue already that shows the progress with it (#110).

**Comment by fabioz** [comment]
I hadn't noticed it was a duplicate. Closing this one then (I expect to work on #110 in the short-term).
