### ISSUE TITLE
Unicode not showing in Python debugger

### ISSUE THREAD

**Issue by rlayton6** [microsoft/debugpy#425]
Issue Type: <b>Bug</b>

When debugging the following python file (single file project), looking at the `message` variable will display only code points, not `こにちは` as expected.

```
# -*- coding: utf-8 -*-
message = u"こにちは"
print message
```

Extension version: 2020.9.111407
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:23:33.049Z)
OS version: Linux x64 4.15.0-118-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3899)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.30GB (18.25GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id df01ac53-d9d9-4a40-99e2-0283ae684348|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by fabioz** [comment]
I don't think this will be changed... the issue is that on Python 2 the `repr` gives that representation (as Py2 is not really unicode oriented).

i.e.: 

On Py2:

![image](https://user-images.githubusercontent.com/117621/94675136-a4c8e280-02ef-11eb-9156-d785288c1bb0.png)

On Py3:

![image](https://user-images.githubusercontent.com/117621/94675161-ae524a80-02ef-11eb-9375-8d7ddecce79a.png)

---

As a workaround to see the actual message in Py2 you can use the `Debug Console` to print it:

![image](https://user-images.githubusercontent.com/117621/94675541-44867080-02f0-11eb-94b8-70e58901a8a8.png)
