### ISSUE TITLE
Missing 1.0.0 release on PyPI

### ISSUE THREAD

**Issue by frenck** [microsoft/debugpy#427]
## Environment data

- debugpy version: 1.0.0
- OS and version:
- Python version (& distribution if applicable, e.g. Anaconda): 
- Using VS Code or Visual Studio:

## Actual behavior

Expected to be able to install the 1.0.0 release using `pip`

<https://github.com/microsoft/debugpy/releases/tag/v1.0.0>

## Expected  behavior

Release is not on PyPI, `pip install debugpy==1.0.0` fails.

<https://pypi.org/project/debugpy/#history>

![image](https://user-images.githubusercontent.com/195327/94788804-69541400-03d4-11eb-8987-b2b6246835b1.png)

## Steps to reproduce:

```bash
pip install debugpy==1.0.0
```

**Comment by int19h** [comment]
That's because it's not actually released yet - the commit that's tagged as v1.0.0 is the one that *will* become the release, but it's still in process (we have to tag it before we build it, because the version number in the build comes from the tag). It's expected to be published by the end of this week.
