### ISSUE TITLE
Messages sequence for attach different from that of PTVSD

### ISSUE THREAD

**Issue by JohanMabille** [microsoft/debugpy#439]
## Environment data

- debugpy version: 1.0.0b9
- OS and version: gentoo (5.4.60-gentoo-x86_64)
- Python version (& distribution if applicable, e.g. Anaconda): 3.8.6 from conda
- Using VS Code or Visual Studio: No

## Actual behavior

When trying to attach a process to the debugpy, the expected messages sequence is the following:

```
client -> debugpy: initialize request
client <- debugpy: intialize response
client <- debugpy: initialize event
client -> debugpy: attach request
client -> debugpy: setBreakpoints request
client <- debugpy: setBreakpoints response
client -> debugpy: configurationDone request
client <- debugpy: configurationDone response
client <- debugpy: attach response
```

This is different from the messages sequence required to attach a process to PTVSD:

```
client -> PTVSD: initialize request
client <- PTVSD: initialize response
client <- PTVSD: initialize event
client -> PTVSD: attach request
client <- PTVSD: attach response
client -> PTVSD: setBreakpoints request
client <- PTVSD: setBreakpoints response
client -> PTVSD: configurationDone request
client <- PTVSD: configurationDone response
```

## Expected  behavior

The sequence should be the same as that of PTVSD, that is, `attach response` should be sent once the process is attached instead of waiting for `configurationDone` request. Besides, this seems to break the "reply - response" pattern from the Debug Adapter protocol, and is not consistent with the initialization sequence described on this [page](https://microsoft.github.io/debug-adapter-protocol/overview)

## Steps to reproduce:

Build xeus-python from this branch: jupyter-xeus/xeus-python#329
Try to run the bugger

**Comment by marimeireles** [comment]
Reproducible on my Ubuntu 20.04.1 LTS with all the other configs same as Johan's.

**Comment by SylvainCorlay** [comment]
The fact that `debugpy` requires to intertwine the setup of breakpoints and configuration between the attach request and the attach response breaks a lot of assumptions about the request-response pattern of the DAP.

**Comment by fabioz** [comment]
This happens because the implementation (https://github.com/microsoft/debugpy/blob/main/src/debugpy/adapter/clients.py#L542) only responds to the attach/launch request on `configurationDone`.

@int19h do you know why is this done this way in debugpy (vs directly responding it)?

Still, I just wanted to add that there are other occasions where a request won't have an immediate reply (this is especially true on evaluate requests where it's possible that the evaluate never returns if one thread requires things from another thread -- in this case the user should be allowed to resume a thread even if the evaluate never returns as doing otherwise would effectively deadlock the debug session in such corner cases).

**Comment by karthiknadig** [comment]
This issue here describes the approach we have taken: https://github.com/microsoft/vscode/issues/4902#issuecomment-368583522

This is in our reference for DAP clients: https://github.com/microsoft/debugpy/wiki/DAP-Client-reference

**Comment by int19h** [comment]
As noted above, this is by design, and in conformance with the DAP specification. The older ptvsd behavior was actually not fully conforming, because we misunderstood the spec.

**Comment by JohanMabille** [comment]
> This issue here describes the approach we have taken (see "Late Case"): microsoft/vscode#4902 (comment)

Maybe I missed something, but it seems to me that the two constraints mentioned in the comment do not prevent the following sequence to work:

Client -> DAP : initialize request
Client <- DAP: initialize response
Client <- DAP: initialize event (constraint 1 is satisfied)
Client -> DAP: setBreakpoints/etc requests
Client <- DAP: setBreakpoints/etc response
Client -> DAP: configurationDone request
Client <- DAP: configurationDone response
Client -> DAP: launch request
Client <- DAP: launch reponse (condition 2 is satisfied)

Also, this is specific to the `launch` request. In the case of an `attach` request, the debuggee is already running, is there a reason for preventing attaching before the configuration is done?

Besides, it should be possible to add breakpoints when debugging (so after the launch / attach response has been sent). It was the case with `PTVSD` and I think it's still the case with `debugpy`. Therefore, is there any reason for requiring a `ConfigurationDone` response before launching / attaching?

> As noted above, this is by design, and in conformance with the DAP specification.

Does it mean that the initialization sequence diagram in the [official DAP documentation](https://microsoft.github.io/debug-adapter-protocol/overview) is wrong? Because in this case, the launch request is sent after the configurationDone response has been received (and this does not violate any of the two conditions mentionned above).

**Comment by SylvainCorlay** [comment]
Hey @int19h, we think that the issue was closed a bit quickly and that the said constraints do not prevent the sequence we mentioned.

**Comment by int19h** [comment]
@JohanMabille It's a legal sequence, but it's up to the debug adapter to signal the "initialized" event when the conditions are met. In case of debugpy, the conditions aren't met until after you issue the "launch" or "attach" request.

The reason why it needs it is because the adapter doesn't handle breakpoints - the debug server does. But, there's no debug server until one is either spawned (if "launch") or attached to. If "setBreakpoints" were an event, it could be deferred and propagated when the server is there - but it's a request, requiring a response, so you'd just end up with a deadlock where the client is waiting for a response, and the adapter is waiting for "launch" or "attach".

This is different from ptvsd 4, because in that one, the debug adapter proper was not a part of ptvsd at all, but rather a bunch of TypeScript code in the VSCode extension - ptvsd itself was strictly a debug server, and didn't meaningfully handle "launch" or "attach" at all, since, by definition, it's already in the process it's trying to debug. The old adapter was aware of ptvsd's non-coformance idiosyncracies, and massaged them into something that VSCode could handle; in particular, it would *not* send "initialized" event until it received "launch", and spawned the ptvsd server (and thus ready to receive "setBreakpoints"). The new adapter that's a part of debugpy itself does the same thing.

Previously, if you were using ptvsd directly as a client - e.g. by attaching to the socket - you were skipping the old adapter, and thus getting ptvsd's broken implementation of DAP. This is not an option with debugpy anymore. 

DAP spec needs to be updated to reflect the diagram linked above. There was an issue about that on their issue tracker somewhere. But in any case, the client is supposed to follow the adapter lead here - it's up to the adapter to decide which sequence is more appropriate to its implementation (whether it's because that's the only way to do it, or because it's just easier). A conforming client *should* wait until the "initialized" event is received before sending "setBreakpoints", and *should* be able to handle either sequence in the diagram - meaning that it cannot wait for "launch" or "attach" response before sending "setBreakpoints" and/or "configurationDone". This is not something that's clear from the DAP spec by itself, but it doesn't contradict it, either.

(@weinand, please correct me if anything is wrong in the above.)

From our perspective, which sequence debugpy implements is an implementation detail that can change at any time in the future, and should not be relied upon. The only guarantee that we make here is conformance to the spec as clarified by the diagram.

**Comment by JohanMabille** [comment]
Thanks for the detailed explanation!

**Comment by SylvainCorlay** [comment]
> DAP spec needs to be updated to reflect the diagram linked above. [...]
> This is not something that's clear from the DAP spec by itself, but it doesn't contradict it, either.

Considering the new debugpy sequence as legal is problematic because it makes it impossible for a single thread to hangle all legal sequences. Your diagram at https://github.com/microsoft/debugpy/wiki/DAP-Client-reference basically requires that another thread can pick up the initialize event and send a couple of requests while waiting for the attach response... This breaks the hypothesis that the attach sequence can be done sequencially (or the notion of request/response).

This issue should probably be reopened.

**Comment by puremourning** [comment]
> Considering the new debugpy sequence as legal is problematic because it makes it impossible for a single thread to hangle all legal sequences

Not so, just not a single thread using _blocking_ requests. 

It's perfectly doable in a single thread.

**Comment by int19h** [comment]
It does not require a single thread. It does require for the client to be able to not wait for a response to a request while issuing other requests, but this can be done perfectly well with an event loop, or some similar async arrangement with continuations. Indeed, the debugpy adapter itself uses a single thread to process all requests from a single client, while still handling nested requests where the protocol requires so (in this very case).

**Comment by SylvainCorlay** [comment]
> but this can be done perfectly well with an event loop, or some similar async arrangement with continuations

Sure, some model of concurrency - but it is already a strong departure from the documented sequence in the DAP.

**Comment by int19h** [comment]
https://github.com/microsoft/vscode/issues/4902 clarifies the spec on this matter, and we conform to that clarification. Furthermore, per comments there, the sequence that we implement is also the one implemented by most other debug adapters (Node, Go, PHP, Ruby, .NET, PowerShell), so we're not doing anything unusual here. There's a good reason for that, too - if the adapter has any debug configuration properties that can affect breakpoints, it needs to see the "launch" or "attach" request before it can properly process "setBreakpoints" requests.

**Comment by SylvainCorlay** [comment]
How about relaxing "Constraint 2"? I can attach a debugger, and set breakpoints after anyways...

**Comment by fabioz** [comment]
@SylvainCorlay in this case, in your client, can't you just not wait for the response from the `attach` or `launch` request in your specific use case (and just ignore when it's received after the configuration done)?

Seems a reasonably simple workaround for this case (it may be a bit of a hack, but then you don't need any concurrency model on your side in this specific case and everything else should work properly from what I can tell -- although as I said in: https://github.com/microsoft/debugpy/issues/439#issuecomment-714589848, you may want to do this anyways in the future as there are cases when not having a concurrency model at all may break debugging for the client).

The problem from what I could understand is that on concurrent clients, failing that constraint may make those miss breakpoints, so, while this would fix it for you it could break other clients (which may be expecting https://github.com/microsoft/vscode/issues/4902#issuecomment-368583522, which is what's implemented in the VSCode TypeScript Debug Adapter)... This wasn't the case before because `ptvsd` was not really a debug adapter, it was only a debug server.
