### ISSUE TITLE
debugpy fails to attach to process launched by systemd as a service

### ISSUE THREAD

**Issue by CodeGuro** [microsoft/debugpy#443]
## Environment data

- debugpy version: 1.0.0rc2
- OS and version: Linux Mint 20 x86_64
- Using VS Code or Visual Studio: VS Code

## Problem Summary

As the title implies, debugpy fails to attach to a process kicked off by systemd/systemctl.
I found this issue when I was trying to attach to a process ID a simple flask application served by the phusion-passenger web-app server with an apache back-end.

Kicking it off like so:

    systemctl start apache2

and attaching to the wsgi application/process associated with the python file:
`/usr/share/passenger/helper-scripts/wsgi-loader.py`
Doing this, the debug/adapter seems to be timing out.

However, stopping the systemd service and then launching the apache service this way:

    sudo apache2ctl restart

Allows me to attach the debugger to the wsgi-loader process normally and use it without issue. This kickoff does not register the apache service with systemd (`sudo apache2ctl start` _does_, however)

There is another odd thing that happens here. No matter which way I launch the wsgi application, using the remote-debugger feature to explicitly set a host/port to which to listen to and attaching it that way works fine, so I suspect there is something odd happening in PID injector.

**Comment by CodeGuro** [comment]
Attached are the VSCode and adapter debug logs for the failed cases (attach after launching with systemd)
[debugger.vscode_8516a643-cbf4-461c-80d5-d7c6ad247990.log](https://github.com/microsoft/debugpy/files/5428509/debugger.vscode_8516a643-cbf4-461c-80d5-d7c6ad247990.log)
[debugpy.adapter-28538.log](https://github.com/microsoft/debugpy/files/5428510/debugpy.adapter-28538.log)

**Comment by CodeGuro** [comment]
Attached are the VSCode and adapter debug logs for the successful cases (stop the systemd service and launch explicitely or with `sudo apache2ctl restart`) for the same wsgi application.

[debugger.vscode_f089920e-ad3e-44a2-b9b6-9323934456be.log](https://github.com/microsoft/debugpy/files/5428533/debugger.vscode_f089920e-ad3e-44a2-b9b6-9323934456be.log)
[debugpy.adapter-22328.log](https://github.com/microsoft/debugpy/files/5428534/debugpy.adapter-22328.log)

**Comment by fabioz** [comment]
What the debugger does is attaching with gdb to the process, adding a .so and then starting the debugger from inside.

The output from gdb says that the error is:

`b'stderr: b\'\\nwarning: "target:/usr/bin/python3.8": could not open as an executable file: Operation not permitted.\\n\\nwarning: target:/usr/bin/python3.8\\\': can\\\'t open to read symbols: Operation not permitted.\\n\\nwarning: Could not load vsyscall page because no executable was specified\\nNo symbol table is loaded.  Use the "file" command.\\nNo symbol table is loaded.  Use the "file" command.\\n\''`

So, it seems it's failing because you don't have permissions to do so in that process (in which case there's not much to be done).

If you want, you should be able to manually check it by running the gdb command line below (providing the proper pid):

`gdb --nw --nh --nx --pid 24249 --batch --eval-command=\'set scheduler-locking off\' --eval-command=\'set architecture i386:x86-64\' --eval-command=\'call (void*)dlopen("/home/tony/.vscode/extensions/ms-python.python-2020.9.114305/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_attach_to_process/attach_linux_amd64.so", 2)\'`

I'm going to close since there doesn't seem like there's much to be done in the debugger side here, but feel free to reopen or comment more if you'd like.

**Comment by CodeGuro** [comment]
@fabioz I'm trying to learn more about debugpy and don't know where to ask (is the IRC a good place?).
First question is - how does debugpy use GDB to interface to a running python process if GDB wasn't configured for python extensions? I've demonstrated that it can work without them, so how does it search the symbols? Is this all somehow implemented in the attach_linux_amd64.so mentioned earlier? Or is debugpy source code doing the heavylifting and if so, where?
