### ISSUE TITLE
inject_dll_x86.exe is detected like malware

### ISSUE THREAD

**Issue by michaelschmit** [microsoft/debugpy#450]
A little while ago McAfee just quarantined inject_dll_x86.exe.  It looks like a release was pushed 4 hours ago.  This previous issue looks like the same thing.

https://github.com/microsoft/vscode-python/issues/9474

## Environment data

-   VS Code version:  1.49.2
-   Extension version (available under the Extensions sidebar): 2020.10.332292344
-   OS and version: Mac 10.14.6

## Actual behaviour

McAfee flaged inject_dllx86.exe as malware.  Detected as GenericRXHX-RG!13065E9950E2

More Information: Accessed by process Code Helper

**Comment by karthiknadig** [comment]
Can you check and make sure that the version you have has this cert?
![image](https://user-images.githubusercontent.com/3840081/97508998-40289400-193e-11eb-9631-1ace9bf1d081.png)


Also can you verify the check sum. It should be this:
```
> fciv -sha1 "C:\Users\Karthik Nadig\.vscode\extensions\ms-python.python-2020.10.332292344\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_attach_to_process\inject_dll_x86.exe"
//
// File Checksum Integrity Verifier version 2.05.
//
a3b1778abf55bbb3c486326531a28019a355ea4a c:\users\karthik nadig\.vscode\extensions\ms-python.python-2020.10.332292344\pythonfiles\lib\python\debugpy\_vendored\pydevd\pydevd_attach_to_process\inject_dll_x86.exe
```

If these match then this is likely a false positive.

**Comment by michaelschmit** [comment]
I haven't had the time to dig into this further.  If no one else is experiencing this issue, then it is clearly a false positive.  Closing ...

**Comment by int19h** [comment]
Most likely, this is due to the threat database not being up-to-date.

These binaries implement attach-to-processID, and will often be detected as "generic" trojans or malware by heuristic detection algorithms, because they use the same techniques to inject code into a running process. To prevent this, anti-malware products add signatures for specific binaries that are known to not be a threat. When we release a new version of debugpy, part of the release process is a malware scan - and if it fails, then the binaries that trigger it are submitted to anti-malware owners for investigation and addition to the database. As it happens, the 1.0 release of debugpy had to go through this process; consequently, if your threat database predates the release, it might not have the signature of those binaries in its allow-list.

**Comment by benganellison** [comment]
> I haven't had the time to dig into this further. If no one else is experiencing this issue, then it is clearly a false positive. Closing ...

but my issue was closed and referred to this issue as duplicate.

**Comment by karthiknadig** [comment]
@benganellison See this response from @int19h https://github.com/microsoft/debugpy/issues/450#issuecomment-719795942 . Your issue and this are the same, MacAfee's signature database was probably out of date.

**Comment by TechRemedies** [comment]
The inject_dll_x86.exe file has been quarantined by some anti-virus suites. It is being marked as suspicious in VirusTotal again:

https://www.virustotal.com/gui/file/151ba420e5b2e8d49d035a38a1ad07e1e8114801a02dba4cd0ff8695ebc4e6b2/detection

This version has the SHA256 Hash of: 151ba420e5b2e8d49d035a38a1ad07e1e8114801a02dba4cd0ff8695ebc4e6b2

**Comment by karthiknadig** [comment]
@TechRemedies Which version of `debupy` do you see this issue with? we have not released a new version since https://pypi.org/project/debugpy/1.5.1/ which was released on OCT/18/2021

**Comment by karthiknadig** [comment]
Hash of inject_dll_x86.exe (v1.5.1): 
```
[SHA256] 1864f6ab915c03755863b1f731c7c6ca13fc0240eb9d22180c18e9d79b3c11d8 
[SHA1  ] 199eb5b7ceb9a6d4eaf9dee7d47c2ed0bee976e3
[MD5   ] a3c52a7186f8d0ececeb0d17cd670558
```
