### ISSUE TITLE
Asyncio Interface Requested

### ISSUE THREAD

**Issue by dougransom** [microsoft/debugpy#479]
so we can open the server connection without blocking our thread.

**Comment by fabioz** [comment]
`debugpy.listen` can already start listening to connections without blocking the thread... although it starts listening in a thread and not through asyncio, I don't really see much gain here in using asyncio.

So, I'm closing this request since I don't think there's anything to gain by creating an asyncio-related interface (since there's already a threaded non-blocking API). 

If you feel there's something to gain here, please elaborate a bit more on what would be the gains by implementing such an API.
