### ISSUE TITLE
Debugging on a remote machine doesn't work

### ISSUE THREAD

**Issue by eldarkurtic** [microsoft/debugpy#524]
Running any Python code on a remote machine from the vscode works just fine. Running in a debug mode (F5) crashes with the following message: **Timed out waiting for debuggee to spawn.**

_launch.json_ has a standard auto generated code:
```    
"configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
```

First time connecting to the remote machine results with this:

```
/usr/bin/env /my-home/miniconda3/envs/nml/bin/python /my-home/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/launcher 42517 -- /my-home/my-project/test.py 
Traceback (most recent call last):
  File "/my-home/miniconda3/envs/nml/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/my-home/miniconda3/envs/nml/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/my-home/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/launcher/__main__.py", line 95, in <module>
    main()
  File "/my-home/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/launcher/__main__.py", line 51, in main
    launcher.connect(host, port)
  File "/my-home/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/launcher/../../debugpy/launcher/__init__.py", line 34, in connect
    sock.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
```

If it helps, I have used the same setup (on a remote machine and on my laptop with vscode) for a while without this issue. At some point having: `"python.terminal.activateEnvironment": false` in my _settings.json_ helped but it's not the case anymore.

## Environment data

-   VS Code version: 1.52.1
    Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
    Date: 2020-12-16T16:30:02.420Z (3 wks ago)
    Electron: 9.3.5
    Chrome: 83.0.4103.122
    Node.js: 12.14.1
    V8: 8.3.110.13-electron.0
    OS: Darwin x64 20.2.0
-   Extension version (ms-python.python): v2020.12.424452561
-   Extension version (ms-python.vscode-pylance): v2021.1.0
-   Extension version (ms-vscode-remote.remote-ssh): v0.62.0
-   OS and version (remote machine): Debian 4.19.152-1 (2020-10-18) x86_64
-   Python version: Python 3.8.3
-   Type of virtual environment used: miniconda
-   Value of the `python.languageServer` setting: Pylance language server 2021.1.0 (pyright e372c657) 

## Steps to reproduce:

Running any python code has this issue. For example:
```
for i in range(10):
    print(i)
```

Additional info:
- Running a python code **without debugging works fine** and results with the following commands in the integrated terminal:
```
cd /my-home/my-project ; /usr/bin/env /my-home/miniconda3/envs/nml/bin/python /my-home/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/launcher 38687 -- /my-home/my-project/test.py 
```
- Running a python code **with debugging crashes** and results with the following commands in the integrated terminal:
```
cd /my-home/my-project ; /usr/bin/env /my-home/miniconda3/envs/nml/bin/python /my-home/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/launcher 40971 -- /my-home/my-project/test.py 
```

**Comment by int19h** [comment]
Can you try running it with `"logToFile": true` in your config, and then provide the logs from /my-home/.vscode-server/extensions/ms-python.python-2020.12.424452561 - there will be several files there matching `debugpy.*.log`.

**Comment by eldarkurtic** [comment]
I get the error message saying: `Cannot read property 'objectMode' of undefined.`
This is my `launch.json`:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "logToFile": true
        }
    ]
}
```

**Comment by eldarkurtic** [comment]
I am not sure if there is some causality here but check this:
- when I install [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) extension on my remote machine, I am able to run my python code in a debug mode without any issues
- when I remove the extension, I get the issue: _Timed out waiting for debuggee to spawn_

**Comment by int19h** [comment]
When you do get the "cannot read property" error, is that a dialog, or is it in Debug Console or Output pane? If the latter, does it include any stack trace or similar?

I'm honestly not sure why Live Server could play any role in this, since we don't depend on it or do anything special for it in any way. Perhaps installing that extension causes some configuration changes to networking on that machine? debugpy needs to be able to open ports on localhost, and to connect to them.

**Comment by eldarkurtic** [comment]
> When you do get the "cannot read property" error, is that a dialog, or is it in Debug Console or Output pane? If the latter, does it include any stack trace or similar?

It is a dialog with two clickable buttons: _Open launch.json_ and _Cancel_.

> I'm honestly not sure why Live Server could play any role in this, since we don't depend on it or do anything special for it in any way. Perhaps installing that extension causes some configuration changes to networking on that machine? debugpy needs to be able to open ports on localhost, and to connect to them.

To be honest, I have no idea what is happening nor how to debug this weird situation.

**Comment by int19h** [comment]
This one sounds like it's a distinct error, although it's worrying in and of itself. I'm still curious about the logs, though. If the property doesn't work, another way to do this is to set `DEBUGPY_LOG_DIR` environment variable to where you want the logs to be placed (and make sure that your VSCode instance sees the updated value).

**Comment by eldarkurtic** [comment]
I got only one _debugpy_ and one _debugger_ log file. Here they are:

[debugger.log](https://github.com/microsoft/debugpy/files/5801623/debugger.log)
[debugpy.log](https://github.com/microsoft/debugpy/files/5801624/debugpy.log)

**Comment by konidk** [comment]
I have the same issue, however, the python file is on my local machine. I uninstalled the "Remote - SSH" extension but it doesn't solve the issue.

[debugger.log](https://github.com/microsoft/debugpy/files/5832646/debugger.log)
[debugpy.log](https://github.com/microsoft/debugpy/files/5832648/debugpy.log)

**Comment by int19h** [comment]
For remote scenarios, this might be the same as https://github.com/microsoft/debugpy/issues/506 - in this case, the workaround suggested there (setting "remote.autoForwardPorts" to false) should work. However, it doesn't explain why this fails for local scenarios.

**Comment by AndreasLuckert** [comment]
As adviced by @int19h, I'm going to post the log-files generated in the failed process hereafter related to [my issue posted yesterday](https://github.com/microsoft/debugpy/issues/693) with the error **ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it**:

[debugpy.launcher-20708.log](https://github.com/microsoft/debugpy/files/6966491/debugpy.launcher-20708.log)
[debugger.vscode_75769758-4662-4edf-b6f2-5e79fe7685c0.log](https://github.com/microsoft/debugpy/files/6966492/debugger.vscode_75769758-4662-4edf-b6f2-5e79fe7685c0.log)
[debugpy.adapter-102912.log](https://github.com/microsoft/debugpy/files/6966493/debugpy.adapter-102912.log)

I hope with this the problem can be better understood, let me know if you need any other details.

**Comment by AndreasLuckert** [comment]
> For remote scenarios, this might be the same as #506 - in this case, the workaround suggested there (setting "remote.autoForwardPorts" to false) should work. However, it doesn't explain why this fails for local scenarios.

@int19h I tried out the setting `"remote.autoForwardPorts": false` in my main `settings.json` (as it's greyed out in my project-specific `settings.json`), reloaded the window, started the debugging process via `F5` and got the same error again:

```
$  /usr/bin/env 'DEBUGPY_LOG_DIR=c:\Users\username\.vscode\extensions\ms-python.python-2021.8.1105858891' c:\\Users\\username\\Projects\\FHH-venv\\Scripts\\python.exe c:\\Users\\username\\.vscode\\extensions\\ms-python.python-2021.8.1105858891\\pythonFiles\\lib\\python\\debugpy\\launcher 65156 -- c:\\Users\\username\\Projects\\FHH\\test_files\\prediction_performance_monitoring\\modified_app_for_docker_testing.py 
Traceback (most recent call last):
  File "C:\Users\username\.pyenv\pyenv-win\versions\3.8.9\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\username\.pyenv\pyenv-win\versions\3.8.9\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\username\.vscode\extensions\ms-python.python-2021.8.1105858891\pythonFiles\lib\python\debugpy\launcher\__main__.py", line 97, in 
<module>
    main()
  File "c:\Users\username\.vscode\extensions\ms-python.python-2021.8.1105858891\pythonFiles\lib\python\debugpy\launcher\__main__.py", line 53, in 
main
    launcher.connect(host, port)
  File "c:\Users\username\.vscode\extensions\ms-python.python-2021.8.1105858891\pythonFiles\lib\python\debugpy\launcher/../..\debugpy\launcher\__init__.py", line 34, in connect
    sock.connect((host, port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```


[debugpy.launcher-98472.log](https://github.com/microsoft/debugpy/files/6966623/debugpy.launcher-98472.log)
[debugger.vscode_b11d7f57-76ef-43ae-bec4-de37f091c7a0.log](https://github.com/microsoft/debugpy/files/6966624/debugger.vscode_b11d7f57-76ef-43ae-bec4-de37f091c7a0.log)
[debugpy.adapter-52760.log](https://github.com/microsoft/debugpy/files/6966625/debugpy.adapter-52760.log)

**Comment by int19h** [comment]
The fundamental problem here is that a localhost-to-localhost connection fails for some reason. To be more specific, here's the adapter setting up a listener port (successfully, otherwise it'd log the error):

    I+00000.750: /handling #2 request "launch" from Client[1]/
             Listening for incoming Launcher connections on 127.0.0.1:65156...

And then the launcher tries to connect to it:

    I+00000.328: Connecting to adapter at 127.0.0.1:65156

Which leads to the error message that you have observed. This is something that's not supposed to fail, generally speaking (opening a listener port might fail, but if it succeeds, it should be possible to connect to it). It could fail if the environment is interfering with the ports somehow though - automatic redirection is one example, but it could also be firewall rules etc. Can you think of anything in your environment that might be causing issues like that?

It would also be interesting to test this with a trivial Python app. Something like:

```py
# server.py
import socket
sc = socket.socket()
sc.bind(("127.0.0.1", 0))
sc.listen(1)
print(sc.getsockname())
sc.accept()
```

```py
# client.py
PORT = ...
import socket
sc = socket.socket()
sc.connect(("127.0.0.1", PORT)) 
```

**Comment by AndreasLuckert** [comment]
**Update:**

it seems like the problem vanishes with less CPU-/RAM-load on the system.
I'd previously experienced a similar problem also on my Ubuntu - machine, it happened usually when the system was lagging due to current overload.

Recently, I started less applications at the same time and since 3 days or so the problem has not occurred again. I hope this will continue.

On the other hand, if it's in the realm of your ambit, I'd suggest to make the error somehow clearer, since it does not really help as to what is the actual cause and how to resolve it.

**Comment by int19h** [comment]
I wish we could make the error clearer! The problem is that we don't really know *why* the socket connection is failing - only that it does.

**Comment by AndreasLuckert** [comment]
**The error returned and has been persisting since 3 days:**

As I pointed out already in [this issue](https://github.com/microsoft/debugpy/issues/693#issue-965149714), debugging local python scripts with VS Code fails with the message
> ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

I noted that the CPU and RAM utilization increased recently, but today I've taken care of that and still the error keeps on occurring, even when the CPU and Memory don't reach 100% workload.

**Are there any news on how to resolve this problem for good?**
It's really hindering my workflow as debugging is essential and I cannot afford to pass on interactive local debugging for several days until the service hopefully magically starts working again.
Thanks in advance for your help.

**Comment by int19h** [comment]
The only theory that I can come up with so far is that you have some kind of local firewall that processes all connections, including (unusually) localhost-to-localhost ones - and when your CPU usage spikes, that firewall slows down enough that it starts dropping connections. FWIW I haven't heard of anything like that before - but if you're in some kind of corporate enterprise environment, it might have its own bespoke arrangement.

**Comment by MehdiShekarnabi** [comment]
Is there any update on this? I've got the same issue!

**Comment by rhildrich** [comment]
I am also running into this same issue and would be curious to hear any updates.

**Comment by MehdiShekarnabi** [comment]
I solved my problem at the time by establishing a ssh tunnel between the computing node and the login node and making sure that the other side is really listening before connecting from one side. [This link](https://github.com/microsoft/debugpy/wiki/Debugging-over-SSH) can help. In any case, if the connection is refused, it means something is blocking halfway. In some HPC clusters, port-forwarding is not allowed due to security reasons, thus you have to check this with the admin. In that case, the solution could be running vscode on the server (login node) and X11 forwarding if the connection speed permits.

**Comment by stark-zhang** [comment]
Is there a workaround about this issue? I have met this problem today.

**Comment by int19h** [comment]
We still don't know what the root cause of the issue is for people who do hit it (and whether it's even the same in all cases). The analysis remains applicable, though: if the simple Python client/server example above gives you errors, then it's down to network configuration.

**Comment by AndreasLuckert** [comment]
**UPDATE:**

finally, I could resolved this persisting error. You can find the details in [answer on StackOverFlow](https://stackoverflow.com/a/73280867/12298276). I hope this helps other people as well struggling with this problem.
