### ISSUE TITLE
Recursive debugging in Jupyter Console (interactive window)

### ISSUE THREAD

**Issue by darim1** [microsoft/debugpy#525]
I got two questions regarding the general debugging experience of debugpy: 

**1. Interactive Window/ Debug Console**: It seems that the interactive workflow does not permit staying inside the interactive window, when stopping at some breakpoint. Instead the user has to switch to the debug console and any input in the interactive window is postponed to the future. Debugging with the console however, lacks the ability of plotting things. Is there a technical reason for this workflow? Would it be possible stay within the interactive window?

**2. Recursive Debugging**: When working with pdb/ ipdb it is possible to run a nested debug cycle from a currently active breakpoint. This is built in native python via [sys.call_tracing](https://docs.python.org/3/library/sys.html). For any python debugger (except pdb/ipdb), including debugpy/pydevd, I havn't seen such feature. Again the question is why. It would be really helpful to attach to some running kernel and stop at any interactively hit breakpoint.

Thanks,
Daniel

**Comment by fabioz** [comment]
For `1.` I'm not really sure of what you call `Interactive Window`. Is it the Jupyter integration? Can you provide a screenshot?

For `2.`, this is being tracked at: https://github.com/microsoft/debugpy/issues/510

**Comment by darim1** [comment]
For 1: Yes, I am talking about the Jupyter integration launched via command "Jupyter: Create interactive window". With respect to issue 2, staying always inside the jupyter console would greatly fit to recursive debugging, enabling the following workflow: 

- Stopping at some initial breakpoint
- investigate stack trace, create some plots
- modify the current stack by calling additional functions, eventually stop in between at some overlaped breakpoint
- create some other plot
- continue to breakpoint 1
- continue ... 
- ...

But even without recursive debugging, it would be nice to have the fully-fledged jupyter console available, when stopping at some breakpoint. What is the purpose of the current implementation, i.e. post-poning commands?

For 2: Ok, thanks for the hint (I thought I had searched the issues before, sorry!).

**Comment by fabioz** [comment]
Well, related to the Jupyter console, that's mostly out of the scope of the debugger itself... for that to work, what would be needed is that the Jupyter console itself would need to be aware that a breakpoint has been hit and that instead of posting a command to the Jupyter loop it should issue an evaluation to the debugger (but that's mostly in the client and I don't think there's much for the debugger backend to do here).

The current implementation postpones commands because there are 2 different loops there (one which deals with handling the commands you enter at the Jupyter console and another one which evaluates commands inside the debugger when you hit a breakpoint and enter a command in the `Debug Console`).

Also, note that such an evaluation happens in the context of the breakpoint, not from the global Jupyter interactive console namespace, so, it may not do what you expect and it may be a bit confusing entering commands for the debugger in the Jupyter interactive console.

@karthiknadig @int19h we already have an issue for part 2 of the request and part 1 is mostly on the Jupyter integration side, would you like to move this ticket to vscode-python?

**Comment by karthiknadig** [comment]
@darim1 @fabioz I created https://github.com/microsoft/vscode-jupyter/issues/4352 out of the last comment. We can close this here for now.
