### ISSUE TITLE
Provide API to automatically attach another embedded python process creation

### ISSUE THREAD

**Issue by novoselov-ab** [microsoft/debugpy#552]
I have an app with embedded python interpreter. I can debug it just fine (by setting `pythonPath` config param), I can also use `multiprocessing` module for multi process debugging. But can I launcher another instance of this app with embedded python interpreter and connect with this debugging session? I use `subprocess.Popen` basically to start another executable.

**Comment by int19h** [comment]
The debugger handles Python subprocesses by intercepting the command line, and adjusting it so as to get loaded into the subprocess first, so that it can control the rest of it. So, for this to work at all, your app with embedded Python would need to behave as a Python interpreter itself (wrt command line options and their behavior). 

If that is not the case, then your best bet is to manually attach from within the subprocess once it's ready to run, e.g. using `debugpy.connect()` at the appropriate place. From VSCode perspective, it won't be considered a single logical multi-process debug session, but rather two independent debug sessions; but for most practical purposes, there's little difference. And if that works for your scenario, we might consider extending `connect()` to support explicitly specifying the parent debug session.

**Comment by novoselov-ab** [comment]
thank you for such quick reply,

I see, I assumed so regarding command line. If I knew how it looks or what it calls I craft it myself and pass needed things to python.

I tried connect, but was not sure, should I connect to initial port parent process listens to? As I understood it spawn another adapter process, should I connect to it instead? When I tried connecting to port I listen to form other subprocess of mine it thows:
```
debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 258, in _on_run
    self.process_net_command_json(self.py_db, json_contents)
debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 165, in process_net_command_json
    assert request.type == 'request'
```

**Comment by int19h** [comment]
For `debugpy.connect()` as it is currently implemented, you'll have to add another debug configuration to your launch.json, that looks something like:
```json5
{
  "name": "Python: Attach (listen)",
  "type": "python",
  "request": "attach",
  "listen": {
    "host": "localhost", // can be omitted
    "port": 8765,
  }
}
```
Then launch that configuration, in addition to (and probably before) launching your main app. You can manually start multiple debug sessions in VSCode via the Debug panel, even if one is already running - just pick another from the drop-down, and launch it via the same.

That session will then be waiting for incoming connection from `debugpy.connect()`, so you'd just specify the same port - e.g. 8765 for the config above - as the destination.

This will result in two independent debug adapter processes that are not aware of each other, each managing its own Python process - but VSCode will be aware of both.

**Comment by novoselov-ab** [comment]
Ah I see, but that would have been the same if I started listen() in that subprocess on another port and added another attach in vscode. 
Just trying to wrap my head around, it looks like you flipped who connects and who listens and I am not sure if that matters.

Overall it is still pretty manual, I was just initially interested if I can invoke some API or anything to make it magical for end user like with `multiprocessing`.

**Comment by int19h** [comment]
Another possibility is to try to manually connect the subprocess as such to the existing debug adapter - I haven't tried that, but in theory, it should work, since that's how multiproc works normally. But to do so, you'll need to obtain the port on which the adapter is listening for debug servers (which is not the same as the one it listens on for clients!). There's no official support for that as yet, but there are some hacks.

Firstly, you can just enable logging - `"logToFile": true` in your debug config for launch, or `--log-to` for debug server CLI, or `debugpy.log_to()` for debug server API. Then you should look for `debugpy.server*.log`; this will contain an entry that looks something like this:
```
I+00000.437: Endpoints received from adapter: {
                 "client": {
                     "host": "127.0.0.1",
                     "port": 5680
                 },
                 "server": {
                     "host": "127.0.0.1",
                     "port": 57205
                 }
             }
```
The "server" part is the one that contains information about the socket to which debug servers should connect.

Another way to get this info is to use the undocumented variable `DEBUGPY_ADAPTER_ENDPOINTS`; if it's set, the debug adapter will write this same JSON out to the file with the specified name. But note that it must be set in whatever context the *adapter* is running in - which would be VSCode if you're doing the launch, and the shell you use to start the server if it's attach.

Either way, once you have the port, I think you should be able to just use that with `debugpy.connect()`, and the adapter will then hopefully pick it up from there, and it'll all "just work".

**Comment by int19h** [comment]
The magical part would be for us to somehow propagate this information in a way that transparently flows to subprocesses - e.g. via another environment variable - and then have a variant of `connect()` that would pick it up automatically; something like `debugpy.connect_subprocess()`. But it would be interesting to see if this works manually first.

**Comment by novoselov-ab** [comment]
yes that is what I thought of before asking and even tried a little. I was hoping there would be a way to get that port. I just tried that once again.. I pretty sure what happens is that this subprocess hangs in connect() call when I pass port from log file. 

Anyway if that is not something officially supported I'd say that will be useful thing to have. I feel like embedding python into application is quite popular use case.

**Comment by fabioz** [comment]
As a note, the related code is:

https://github.com/microsoft/debugpy/blob/main/src/debugpy/_vendored/pydevd/_pydev_bundle/pydev_monkey.py

The tests: 

https://github.com/microsoft/debugpy/blob/main/src/debugpy/_vendored/pydevd/tests_python/test_pydev_monkey.py

Show which command line produces what.

If you want the connect to happen automatically, I don't really see a way around actually handling the command line parameters as if you were Python... as a note, you don't need to handle all Python arguments, just the related subset based on what you're using.

My suggestion would be just printing the args you're receiving in your app and then handling what you need.

I don't think you need to fiddle with how the command line in the process that's spawning another process, you just need to handle it on the target spawned process.

If you obtain the logging it should also show what's being patched.

i.e.:
* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form ms-python.python-2020.*.****
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

I'm not sure there's much we can do here on the debugger side... maybe a utility just to check the command line and interpret it as python would do?
* Start debugging
* When done, go back into the extension directory and check the debug*.log files.

**Comment by novoselov-ab** [comment]
I totally  would not mind treating arguments correctly, I just don't think I receive them. If I would use multiprocessing module I might, but I basically spawn processes myself (with subprocess) and I doubt debugpy can hijack that part? So if I had some API to get that cmd that supposed to be passed as if I spawn another python instance I could work with that. I can pass it to my other instance and execute it there as soon as possible.

**Comment by fabioz** [comment]
Are you spawning those subprocesses using some Python API or are you calling your own executable directly?

**Comment by novoselov-ab** [comment]
I use `asyncio.create_subprocess_exec` from embeded python to call my own executable, the same one, if that makes sense.

**Comment by fabioz** [comment]
Ok... we don't currently monkey-patch the arguments in such cases because we don't know that the executable being called is python (for instance, you could be calling something as `notepad.exe`).

You can do a change locally to make it automatically monkey-patch things:

Steps are:
Run the following command under the debugger:

```
from _pydev_bundle import pydev_monkey
print(pydev_monkey.__file__)
```

Then, open the file which was printed and change:

`def is_python`

to be something as:


```
def is_python(path):
    single_quote, double_quote = _get_str_type_compatible(path, ["'", '"'])

    if path.endswith(single_quote) or path.endswith(double_quote):
        path = path[1:len(path) - 1]
    filename = os.path.basename(path).lower()
    for name in _get_str_type_compatible(filename, ['python', 'jython', 'pypy']):
        if filename.find(name) != -1:
            return True
        
    current_exe_basename = os.path.basename(sys.executable)
    return os.path.basename(filename) in (current_exe_basename, os.path.splitext(current_exe_basename)[0])
```

this change should make it so that if you're calling the `sys.executable` it'll start to automatically monkey-patch it...

Now, note that this may or may not work well (it depends on whether your own command line is compatible or not with CPython -- but if it's reasonably compatible, your own executable should be called with the monkey patched arguments... then, you can handle those, probably doing an `execfile` based on the received args).

Another option is detecting that the debugger is running and manually pass the arguments needed to setup the debugger and then actually do the setup on the target process -- this is probably better as your own command line doesn't need to be compatible with the debugger... it's something as:

```
import sys
import asyncio


def is_debugging():
    try:
        import pydevd
    except ImportError:
        return False

    return pydevd.get_global_debugger() is not None


def call_my_subprocess():
    args = [sys.executable, ...]
    if is_debugging():
        # Automatically attach subprocess to the debug session.
        args.append("--debug-pydevd")
        import pydevd
        from _pydev_bundle.pydev_monkey import _get_python_c_args
        from pydevd import SetupHolder

        host, port = pydevd.dispatch()
        code = ""  # Ok, we don't have code to exec
        unquoted_args = []  # Ok, not really used

        # This will be the arguments usually passed to `python -c <code to execute>`.
        # So, in the target it should be possible to simply `exec` it to connect to the debugger
        # and run the `code` afterwards (which in this case is empty).
        args.append(
            _get_python_c_args(host, port, code, unquoted_args, SetupHolder.setup)
        )

    asyncio.create_subprocess_exec(...)   # pass the args here 


def main(argv):
    if "--debug-pydevd" in argv:
        # Setup the debugger
        i = argv.index("--debug-pydevd")
        pydevd_exec_arg = argv[i + 1]
        exec(pydevd_exec_arg)
        argv = argv[:i]

        # Proceed to handle usual args.
```

Disclaimer: note that it's doing an `exec` based on the args passed to the application... please be aware of security issues. Depending on how your app is used/distributed you may want to remove that when you distribute to final users.

**Comment by fabioz** [comment]
Closing since this doesn't seem very common (and the comment: https://github.com/microsoft/debugpy/issues/552#issuecomment-787058619 has instructions for a user on how he'd do things in his own integration when an application has python embedded).
