### ISSUE TITLE
Add support for terminateThreads request.

### ISSUE THREAD

**Issue by cgittinger** [microsoft/debugpy#562]
I see no way (*) to unwind a stopped thread into a defined caller frame (or restart a caller frame).

 - supportsRestartFrame: NO
 - supportsTerminateThreadsRequest: NO
 - evaluate in frame: NO
  (passing code like: "Exception raise" does not do what I expected, although it does look reasonable to me. It looks like evaluate() only evaluates in the variable context, but not the stackframe/continuation context. I.e. it should push a synthetic call frame and let the target thread itself execute in that. Not sure if the python interpreter allows for that, though).

*) Or am I missing something (i.e. is there any way to implement such a function)?
Is there a chance to get one of the above in the near future (if not, I might have to give up on debugpy)?

Background:
I have a python (slave) running under surveillance of another program (master), which controls the slave via debugpy.
The master implements a kind of save environment for code execution entered by a user.
The slave sits in main loop, waiting for commands from the master.
When the code hits an error or breakpoint, the master wants to unwind the slave's stack to force the slave to return to the mainloop.

**Comment by fabioz** [comment]
Python itself has no way to restart a caller frame, so, `debugpy` just reflects a shortcoming of Python itself.

Still, I haven't understood why exactly you're using `debugpy` in this case and not just have a loop where you do your own evaluations and have an exception raised to return to the mainloop under some circumstances... (you're off course free to debug using debugpy regardless, but I don't really see how the scenario you're proposing is benefiting from `debugpy`).

**Comment by cgittinger** [comment]
because the code was entered by (a possibly naive) user, ending in an endless loop or whatever, and I want to provide a "STOP"button, to get the executor out of that without loosing previously defined code or state (especially: open connections, file descriptors etc.). Thus, I like to unwind and not terminate python.As I wrote: I can of course run the user's code in a. separate thread and terminate that (which I can't with debugpy).
So I will need an extra debug connection to do that...
Which is possible, but a kludge; I'd rather have debugPy super the terminateThread request.

**Comment by fabioz** [comment]
I'm not sure I follow here... as far as I know, you can't really run the user code in a separate thread and terminate that -- terminating a thread isn't really supported by Python as far as I know -- maybe I'm missing something here, in which case, I'd really appreciate some pointers/docs on how to do that ;)

i.e.: as far as I know, the best you can get here is call some `PyThreadState_SetAsyncExc` which will set an exception at a given thread or send a `Ctrl+C` signal if it's the main thread.

None of these are guaranteed to actually terminate a thread and the `PyThreadState_SetAsyncExc` won't even do anything if no code is executing (so, if the user is stopped because he called `input()` or some socket `read()` or is waiting on some lock, etc, nothing will happen). Sending the `Ctrl+C` signal is a bit better on some occasions (but it's also not perfect).

As a note, in `debugpy` you can actually already set an environment variable such as: `PYDEVD_INTERRUPT_THREAD_TIMEOUT` to some value, in which case it'll try to automatically interrupt an evaluation if it takes too long (say `PYDEVD_INTERRUPT_THREAD_TIMEOUT=10` would try to interrupt a thread after `10` seconds elapsed).

See: https://github.com/microsoft/debugpy/blob/3d472df2d65dc4c50d5b2cf765607c34bc1446ec/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py#L314 for some additional comments.

On a 2nd thought, maybe we can try to support the thread terminate request along those lines (although it's full of caveats it may be useful under some circumstances). I'll rename the issue accordingly.

As a note, I'm not sure when I'll be able to get it -- pull requests are welcome ;)

The API which'd probably be used to actually do the interrupt is: `_pydevd_bundle.pydevd_timeout.create_interrupt_this_thread_callback`, which creates a callback which can be called from any thread to interrupt the thread where the callback was created.

**Comment by cgittinger** [comment]
Thank you very very much. I really appreciate your work.

It's a pity, that the pythonVM does not seem to support these primitives well (which imho it should in the long run).

I cannot tell how Python does it or could do it - I can only describe how some other VMs do it: 
force the thread to execute a "raise TerminateProcessException", which does all the finally-cleanup and then does the actual terminate in its start-thread handler.

Long ago, I myself designed a VM where the code looks like:
     Thread >> terminate
         Processor activeProcess == self ifTrue:[
             TerminateException raise
         ] ifFalse:[
             self interruptWith: [ self terminate ]
         ]
         
TerminateException is of course handled in the thread's start method.

And interruptWith: is a low-level VM primitive, which massages the continuation-stack, so that the thread continues there (actually pushes a stackframe, which executes the given lambda); waking it up, if it sits in a blocking I/O or semaphore sleep operation.

I must say that this mechanism is very very convenient and given that it works reliably finds many uses. For example:
    [
        [
             Socket connectTo:...
             ...
        ] ensure:[
            socket close
        ]
    ] newThreadWithWatchdog:(5 seconds).

Again, I can't tell if the Python infrastructure allows for such fiddling around with continuations/stack frames. But that could be a save way to go, if it did.

If you could implement some kind of terminateThread I'd be super happy. 
Even if there are dangers involved (like leftover Semaphores).
 
PS: as you might have guessed: the sample code is in Smalltalk, and the VM I described is a Smalltalk VM ;-)

**Comment by int19h** [comment]
Injecting an exception is exactly how Python does it as well. The problem is that Python exceptions are processed by the Python VM, so if the thread is stuck in native code, it will continue running unaware - the async Python exception will only be raised once it returns back to Python. Hence the examples with `input()` and `read()`, which all block in native code.

**Comment by judej** [comment]
Thank you for the report. Given our current resources are working on the Python 3.12 debugger, we will not be fixing this issues in the pre Python 3.12 debugger.
