### ISSUE TITLE
Uncaught exception in child thread from ThreadPoolExecutor isn't considered as "uncaught exceptions"

### ISSUE THREAD

**Issue by fireattack** [microsoft/debugpy#565]
## Environment data

- debugpy version: 1.2.1
- OS and version: Win7 / Win10 x64
- Python version (& distribution if applicable, e.g. Anaconda): 3.8.7 x64
- Using VS Code or Visual Studio: VS Code

## Steps to reproduce:
1. Create a default launch.json and check "Uncaught Exceptions" checkbox for breakpoint (but not "Raised Exceptions")

![image](https://user-images.githubusercontent.com/4130991/111760312-8db18900-886c-11eb-84ac-7f10577d8ca2.png)

2. Snippet:
```python
import concurrent.futures

def child():
    try:
        raise Exception('error in child thread that is handled')
    except:
        pass
    
    raise Exception('error in child thread that is not handled')

with concurrent.futures.ThreadPoolExecutor(max_workers=3) as ex:
    ex.submit(child)
```
3. Debug it

## Actual behavior
No break at any exception

## Expected  behavior

It should break at the second exception since it's uncaught

**Comment by fabioz** [comment]
This should be handled by the user unhandled feature.

i.e.: because the exception in this case is actually caught in the `ThreadPoolExecutor`, it's not really unhandled (so, `debugpy` is doing the correct thing here). 

Now, there is a feature to stop whenever an exception leaves user code and goes into library code which would work for this case, but right now it needs to be enabled by setting an environment variable.

So, to enable it you need to set an environment variable: `DEBUGPY_EXCEPTION_FILTER_USER_UNHANDLED=1`, restart VSCode (so that the related environment variable is loaded in VSCode), make one launch (at which point VSCode should recompute the exception filters shown) and then you should be able to select `User Uncaught Exceptions` -- as shown in: https://github.com/microsoft/debugpy/issues/550#issuecomment-785982229.

In this case, it should stop at that exception when it leaves user code and goes into library code.

**Comment by fireattack** [comment]
Thanks for the help.
