### ISSUE TITLE
VSCode interface should warn if configuration wouldn't permit to stop in a breakpoint

### ISSUE THREAD

**Issue by pauloneves** [microsoft/debugpy#572]
I created an [issue](https://github.com/microsoft/debugpy/issues/544) because VSCode wouldn't stop in a breakpoint. The problem was that it was configured to stop just in my code and the breakpoint was inside my library. The tests were in a file outside my library. 

It would have been nice if VSCode interface showed me that it couldn't stop in the breakpoint. Maybe displaying a notification when I tried to create it. Maybe displaying as disabled. 

It also would be nice if it told me that I should have set `"justMyCode": False`in the launch.json

**Comment by fabioz** [comment]
The notification and visibility on that should be done by VSCode itself (debugpy does what it should given the protocol: specify that the breakpoint is disabled with a message giving the details... I haven't checked it now, but from what I remember the breakpoint should appear disabled in this case and when you hover over it, it shows the related message).

@karthiknadig @int19h what do you think? Should `debugpy` do anything differently here?

**Comment by int19h** [comment]
If we're already reporting the breakpoint as disabled, but it doesn't show up as such in UI, that sounds like a VSCode (not even extension) bug.

**Comment by fabioz** [comment]
It seems it shows the breakpoint disabled in the editor but not in the breakpoint panel:

![image](https://user-images.githubusercontent.com/117621/112641284-fecede80-8e20-11eb-84df-292c5192ef3d.png)

Anyways, I'm closing the issue here as this is really up to `VSCode`, not `debugpy` (so, if you feel this could be better, please create an issue in the VSCode repo).
