### ISSUE TITLE
VS Code's debug console cannot display complete data.

### ISSUE THREAD

**Issue by Jill-Cheng** [microsoft/debugpy#582]
## Environment data

-   VS Code version: 1.55.0 (user setup)
-   Extension version (available under the Extensions sidebar):  Python Extension version:2021.3.680753044 
-   Python version (& distribution if applicable, e.g. Anaconda):Python3.8.3 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: none
-   Relevant/affected Python-related VS Code extensions and their versions: Jupyter: 2021.5.702919634  Pylance: 2021.3.4
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

The debug console can display complete data:

![image](https://user-images.githubusercontent.com/61971386/113821767-20c84980-97af-11eb-9382-e607bf642308.png)

## Actual behaviour

Only part of the data is shown:

![image](https://user-images.githubusercontent.com/61971386/113821705-07bf9880-97af-11eb-8414-67316ea81ea7.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. code:

```
my_list = []
for i in range(0,100000):
    my_list.append(i)
print(my_list)

```

2. Run the above code, click the run button and then the data is displayed completely, but click F5 to debug the code, the debug console only displays part of the data.

Related Links: [Running python script in VSCode produces truncated output](https://stackoverflow.com/questions/66970346/running-python-script-in-vscode-produces-truncated-output)

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
none
```

</p>
</details>

**Comment by int19h** [comment]
It sounds like you're hitting https://github.com/microsoft/debugpy/issues/299, and the underlying https://bugs.python.org/issue42044 - can you try the workaround mentioned there?

**Comment by DoS007** [comment]
@int19h Thank you.

I created an launch.json and added the solution [from here](https://github.com/microsoft/debugpy/issues/299#issuecomment-709327920). 

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "testpython.py",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "env": {
                "PYTHONUNBUFFERED": "0"
            }
        }
    ],
    
}
```

And voilà it works. 

Yet I find it is just really a current workaround. Before this I never touched launch.json files. For a beginner in python this is very confusing, when those outputs are truncated and such a workaround is needed (if found). [Also that if i run without debugger (CTRL+F5) that the debug console is used (i ran without debugger?).]

Couldn't this problem not just be fixed by making
```
            "env": {
                "PYTHONUNBUFFERED": "0"
            }
```

the default setting? (Probably [this issue](https://github.com/microsoft/vscode-python/issues/14411) is about that?) 

That issue and also your linked cpython issue is from october 2020. Is there a reason why using the solution by setting the above default is not good?

Greets DoS007

**Comment by Gordonguy** [comment]
Workaround in [https://github.com/microsoft/debugpy/issues/299] worked for a while then stopped working. See my comment there.

**Comment by fabioz** [comment]
Closing (answered in: https://github.com/microsoft/debugpy/issues/299#issuecomment-854932743).
