### ISSUE TITLE
Need port mapping through http / websocket

### ISSUE THREAD

**Issue by Honma-Rika** [microsoft/debugpy#590]
Is there any possibility to implement debugpy with http / websocket in order to get headers?

I've recently got trapped at a problem that I wanna debug locally over a docker container on the server which has a public domain name. In launch.json I'm supposed to listen port 80 at host 6167.port.example.com to conduct 6167:5678 mapping, getting debug info from the container. Extremely sorry for my poor explanation but hope you would understand it.

**Comment by fabioz** [comment]
For dealing with such issues, I think your best approach is probably using `ssh tunneling` (which will also give you proper encryption in the connection).

Note: closing since this would be out of the scope of `debugpy` and there are tools that properly implement `ssh tunneling` which can do it for you already.
