### ISSUE TITLE
Step into targets showing options from line below as well

### ISSUE THREAD

**Issue by luabud** [microsoft/debugpy#608]
## Environment data

- debugpy version: v.1.3.0
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): venv, Python 3.8.9 
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Step into targets is also showing options from line below the breakpoint:

![image](https://user-images.githubusercontent.com/45497113/117086834-97029200-ad02-11eb-9140-bd0ded0b0c22.png)

## Expected  behavior
I wouldn't expect it to show options from the line below. In this case, it's even a bit tricky to define what would be expected. I guess my expectation would be to see "get" and "bs" ?

## Steps to reproduce:
1. Clone this repo https://github.com/luabud/pvscc-logo/
2. Open generate_logo.py file in VS Code
3. Add a breakpoint to line 23

![image](https://user-images.githubusercontent.com/45497113/117087310-ebf2d800-ad03-11eb-88ce-515b631b7c0b.png)

4. Either delete the logo_app/static/images/logo.png file or make the debugger skip execution of line 14 (`if not logo_path.exists()`)
5. Debug the file with the "current file" configuration
6. Once it his the breakpoint on line 23, right click and select "Step into targets". You'll see it includes "join" and "findAll", when these are the options that should be displayed (and are indeed displayed) when you click on "Step into targets" when the debugger has hit the line below (with `clean_raw_content = "".join(parsed_content.findAll(text=True))`)

**Comment by fabioz** [comment]
Well, that was done that way on purpose... it should be straightforward to just show the targets for the current line if needed, but I left it like that because in constructs such as the one below it'd be possible to directly go to `another_call()`, which wouldn't be possible if the results were capped to the current line.

```
1. method(  # stop at breakpoint here
2.     1,
3.      some_call(),
4.      another_call()  #step into this method
5. )
```

Also, I think that it's nice to be able to jump further along in the line instead of being constrained by the current line/statement.

Anyways, changing that is straightforward (if based only on the current line heuristics), so, waiting on further opinions (@luabud @karthiknadig @int19h) on whether this should be changed -- as a note, right now it'll get the next 15 function calls in the scope: https://github.com/microsoft/debugpy/blob/c7bb27609005765100fcf44bb1cf36315a6f11c4/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py#L1064)

**Comment by luabud** [comment]
That's fair! I agree, so closing it.
