### ISSUE TITLE
Support for supportsLoadedSourcesRequest

### ISSUE THREAD

**Issue by goanpeca** [microsoft/debugpy#654]
It seem debugpy does not support `supportsLoadedSourcesRequest`

Is this something that could be implemented?

Any code pointers would be extremely valuable

Cheers!

**Comment by fabioz** [comment]
Yes, this could be implemented, but it's currently not planned for...

Are you volunteering to implement it?

**Comment by goanpeca** [comment]
Sure, @fabioz, could you give me some pointers on the codebase to start working on this? 

Thanks :)

**Comment by goanpeca** [comment]
@fabioz any pointers in the codebase so I can gauge the amoung of work needed?

Thanks!

**Comment by int19h** [comment]
Is there a specific scenario that is enabled by supporting this?

**Comment by mlucool** [comment]
This was discussed in context of JuptyerLab: https://github.com/jupyterlab/jupyterlab/issues/10139#issuecomment-872169353

@fcollonval do you know if this is still needed to improve the JupyterLab debugger?

**Comment by fcollonval** [comment]
The final implementation for navigating in the Python source implemented in https://github.com/jupyterlab/jupyterlab/pull/11566 uses `supportsModulesRequest`. That capability is available due to:

https://github.com/microsoft/debugpy/blob/bf5c644bc39a1040d83ea74a40ef87b0d6ae9344/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py#L216

I guess we don't need this one any more.

**Comment by int19h** [comment]
Thank you for the confirmation! I'll go ahead and close it for now then; please let us know if something comes up that could use it.
