### ISSUE TITLE
vscode Debugger hangs on certain variables

### ISSUE THREAD

**Issue by daverous** [microsoft/debugpy#657]
## Environment data

- debugpy version: 1.3.0
- OS and version: Windows_NT x64 10.0.19043
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.5 64 bit
- Using VS Code or Visual Studio: VS code 1.57.1

## Actual behavior
![image](https://user-images.githubusercontent.com/8770065/124771579-873e3e80-df3b-11eb-89c6-86785e23572a.png)

**Evaluation of variable causes debugger to "hang" infinitely** 

When debugging, a variable that is problematic for the debugger is assigned to a object:

```
   self.x = x
   i = 1
```

if i set a breakpoint  on this line, I can see self and x displayed correctly on the debugger. 

However, on the next line, the variables view will hang. 

We know this variable is problematic for the debugger, and when expanding certain fields, the debugger will also hang. This is likely due to the variable having its attribute dictionary manually updated and incorrect use of the @property decorator. Unfortuately, I cannot share this code, and cannot change the codebase. 

My current workaround is to disable "Variables" view in the debugger, and just use **watch**  on the variables i care about. 

## Expected  behavior

Either the variables will be shown, or a timeout will occur on those particular variables, and their values won't be shown, but values of other variables will. 

## Steps to reproduce:
1. Unfortunately, cannot share the code. So reproducer is hard. Again, the desired should have little to do with the code itself, rather that the debugger "times out" and doesn't crash the whole debug session. Logs are attached. 

[debugpy.adapter-23968.log](https://github.com/microsoft/debugpy/files/6777747/debugpy.adapter-23968.log)
[debugpy.server-42132.log](https://github.com/microsoft/debugpy/files/6777748/debugpy.server-42132.log)
[debugger.vscode_72765185-ca49-4923-a093-0a4e2e8b0968.log](https://github.com/microsoft/debugpy/files/6777749/debugger.vscode_72765185-ca49-4923-a093-0a4e2e8b0968.log)
[debugpy.launcher-6836.log](https://github.com/microsoft/debugpy/files/6777750/debugpy.launcher-6836.log)
[debugpy.pydevd.42132.log](https://github.com/microsoft/debugpy/files/6777751/debugpy.pydevd.42132.log)

**Comment by fabioz** [comment]
Well, usually your program needs to be introspectable for the debugger to work properly...

Having said that, the usual workaround for this case (since you can't do the usual alternative which would be fixing the program) would be creating a resolver for the classes in case so that you don't trip over that while expanding the variables in the variables view.

This can be done as a `pydevd_plugin`.
See: the `README` for how to create a plugin:
https://github.com/microsoft/debugpy/tree/main/src/debugpy/_vendored/pydevd/pydevd_plugins/extensions

And you can refer to https://github.com/microsoft/debugpy/tree/main/src/debugpy/_vendored/pydevd/pydevd_plugins/extensions/types which has a couple of custom resolvers to know how to do your own resolver.

https://github.com/microsoft/debugpy/tree/main/src/debugpy/_vendored/pydevd/tests_python/my_extensions/pydevd_plugins may also be interesting (which is the test-case for this feature).

Given that, I don't think there's anything else to be done in the debugger in this case, so, I'm closing this issue (but feel free to add more comments if you can't sort something out).
