### ISSUE TITLE
Enable CI for python 3.10

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#677]

**Comment by int19h** [comment]
This one turns out to be more complicated than it looks, because of https://github.com/pytest-dev/pytest/issues/8539. While the most recent pytest versions already have a fix for that, we currently pin pytest to `<5` (4.6.11, in practice), because newer versions don't support Python 2.

We could switch to newer version of pytest just for Python 3. However, there have been several major releases of pytest since 4.x that contain potentially breaking changes, especially as we use advanced functionality such as test hooks. This might be possible to accommodate with some conditional code, as we already do with py2/py3; but in some cases, it might require altogether separate implementations.

**Comment by int19h** [comment]
There's also a bunch of deprecation warnings getting triggered by pydevd for things like `Thread.setName()` that will need to be fixed before the runs can succeed. Django has the [same problem](https://code.djangoproject.com/ticket/32074), so we'll just have to disable Django tests on 3.10 until they ship 3.3 with the fix.

I'm working on fixing up pydevd uses; down to the last 9 failing tests.

**Comment by int19h** [comment]
The test suite is now passing on 3.10 (with some tests disabled). However, for CI purposes, we also need an image with Python 3.10, and there isn't one available for Python 3.10 at the moment. In the meantime, we'll have to run those tests locally as needed.

**Comment by int19h** [comment]
Python 3.10 should now be available on `windows-latest` agents.
