### ISSUE TITLE
Weird debugging content

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/debugpy#703]
## Environment data
版本: 1.59.1 (user setup)
提交: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
日期: 2021-08-19T11:56:07.791Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT ia32 10.0.18363

## Actual behaviour
When I hit a breakpoint on line 14 and debugged to line 5, I found that getattribute was executed 37 times. What happened?
![image](https://user-images.githubusercontent.com/33288114/130585038-a67219f9-6634-4c15-8700-8a4655677417.png)

#  Code
```python

flag=0
class Student:
  
    def __init__(self, math):
        self.math = math
    
    def __getattribute__(self, name: str) :
        global flag
        flag+=1
        print(flag,'execute getattribute',self,name)
        return super().__getattribute__(name)
   

std = Student( 10)
```

**Comment by int19h** [comment]
The debugger accesses `__class__` on many code paths to perform object type checks etc on variables in Locals and Watch - if you use `__getattribute__` rather than `__getattr__`, it will always get invoked before retrieving the attribute directly. Furthermore, every time you step, all variables are refreshed, so all those accesses are repeated. 

@fabioz, do you think there's a perf issue here? Would using `type()` perhaps be better?

**Comment by CatNofishing** [comment]
Okay，Thank you for your reply
