### ISSUE TITLE
Support `post_mortem` debugging

### ISSUE THREAD

**Issue by TauPan** [microsoft/debugpy#722]
Since pytest supports the --pdb and --pdbcls switches to launch a debugger if a test assertion fails:

```
  --pdb                 start the interactive Python debugger on errors or
                        KeyboardInterrupt.
  --pdbcls=modulename:classname
                        start a custom interactive Python debugger on errors.
                        For example:
                        --pdbcls=IPython.terminal.debugger:TerminalPdb
```

it could be useful (at least to me) if debugpy could support this. See https://github.com/emacs-lsp/dap-mode/issues/506

I may be wrong but it looks like debugpy (and vscode) do not support this yet.

Adding this directly in debugpy could be easier than grafting it onto a pytest plugin, as I proposed in https://github.com/emacs-lsp/dap-mode/issues/506

**Comment by fabioz** [comment]
This is already available (in `debugpy` it's the `Uncaught exceptions` breakpoint).

**Comment by fabioz** [comment]
As a note, for pytest it's not the `Uncaught exceptions` (because the exceptions are actually caught by pytest), instead, you want the `User Uncaught Exceptions` -- in this case it's not available by default, but it should appear to you if you set an environment variable such as `DEBUGPY_EXCEPTION_FILTER_USER_UNHANDLED=1` and make a launch in VSCode -- when the client will update the `exceptionBreakpointFilters`.

@karthiknadig @int19h maybe it's time to remove the need for the `DEBUGPY_EXCEPTION_FILTER_USER_UNHANDLED` environment variable to enable this flag? -- reopening to check whether this should be done...

**Comment by fabioz** [comment]
It seems like https://github.com/microsoft/debugpy/issues/724 is tracking that (so, I'm closing this issue).

**Comment by wookayin** [comment]
See #723 as well to make debugpy handle an thrown exception
