### ISSUE TITLE
Autocomplete does not work in debug console of the first debugging session

### ISSUE THREAD

**Issue by serend1p1ty** [microsoft/debugpy#726]
## Environment data

- VS Code version: 1.40.2
- Extension version (available under the Extensions sidebar): 2019.11.50794
- OS and version: win10
- Python version (& distribution if applicable, e.g. Anaconda): Latest
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Relevant/affected Python packages and their versions: None
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): Jedi

## Expected behaviour

When I start the first debugging session after launch vscode, autocomplete does not work in debug console.
But the strange problem won't appear in the second debugging session.

## Actual behaviour

Autocomplete can work in the first debugging session.

## Logs
```
> ~/anaconda3/envs/person_search/bin/python completion.py
cwd: ~/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles
> ~/anaconda3/envs/person_search/bin/python completion.py
cwd: ~/.vscode-server/extensions/ms-python.python-2019.11.50794/pythonFiles
```

**Comment by int19h** [comment]
I can't repro this, on Anaconda or otherwise. Can you please share a step-by-step repro, including your launch.json, directory layout, and source code?

**Comment by mlut-cau** [comment]
Unfortunately Intellisense is not working for me in the Python Debug Console. It is working in the editor however. This problem is not perfectly aligned with the original title of this issue, but is not working in general as reported in **https://github.com/microsoft/debugpy/issues/726#issuecomment-865699141**

For illustration purposes I have included a screenshot.

![Image](https://github.com/user-attachments/assets/bd43377b-7158-4dfd-93c3-31423b382f03)

Version: 1.97.0
Commit: 33fc5a94a3f99ebe7087e8fe79fbe1d37a251016
Date: 2025-02-04T22:41:26.688Z
Electron: 32.2.7
ElectronBuildId: 10660205
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-52-generic snap

ms-python.python
Version 2025.0.0


ms-python.debugpy
Version 2025.0.1

I would be grateful for hints on where to look to get this to work again (was working when I previously used VS Code about 2 years ago for same project)

**Comment by rchiodo** [comment]
This doesn't work for me either. Autocomplete isn't handled by debugpy though, so this would be Pylance I think? @karthiknadig do you know what handles completion requests in the Debug Console?

**Comment by rchiodo** [comment]
There's a dupe bug in the vscode-python-debugger extension:
https://github.com/microsoft/vscode-python-debugger/issues/639

**Comment by mlut-cau** [comment]
Thanks for the hint, I will keep an eye on that.
