### ISSUE TITLE
Add test support for linux aarch64 

### ISSUE THREAD

**Issue by odidev** [microsoft/debugpy#737]
Hi Team, 

I tried testing debugpy package on Arm64 architectures but it is generating **91 failed with 1104 passed, 11 skipped** for the tox test command with the below error locally: 
```
E           debugpy.common.messaging.MessageHandlingError: Timed out waiting for debug server to connect. 

 .tox/py38/lib/python3.8/site-packages/debugpy/common/messaging.py:955: MessageHandlingError 
```
After investigation found this [issue](https://github.com/microsoft/debugpy/issues/512#issuecomment-751655985) where it is suggested that there is a need of Microsoft Visual C++ 2015-2019 Redistributable to function properly. Tried doing it with MobaXterm which solves the graphical issue but there also same result as above was found. 

As **TravisCI** used, so I added the Arm64 job there but getting an error: `The job exceeded the maximum log length, and has been terminated.  `

**TravisCI** log: https://app.travis-ci.com/github/odidev/debugpy/builds/238637683  

So added both architectures over Github Actions and getting this result: **92 failed, 1103 passed, 11 skipped** on Arm64 architectures with same error as above. 

**GHA log:** https://github.com/odidev/debugpy/actions/runs/1282395586  

Could you please share your feedback regarding this and suggest what can be done to test this over ARM64 server? 

Thanks in advance.

**Comment by int19h** [comment]
I suspect that you're running into https://github.com/microsoft/debugpy/issues/286

The error message is very generic - it's going to show up whenever it couldn't spin up the debug server (pydevd, basically) - so that other bug you've mentioned is highly unlikely to be related.

For the time being, we don't run tests on ARM or ARM64. We do, however, have an open issue to track this: https://github.com/microsoft/debugpy/issues/182 - so this one is a dupe. The other issue is likely to see more attention going forward since Macs are also ARM now.
