### ISSUE TITLE
Debugging a python module: args in launch.json not being passed to python program correctly, "unrecognized switch"

### ISSUE THREAD

**Issue by bbiney1** [microsoft/debugpy#739]
I have a python module that I want to run in VScode's debugger. The full address is `~/Code/APPRES-483/cqs/update-query-definition/__main__.py`.  The main script is called `__main__.py`. I have a virtualenv at `~/Code/APPRES-483/venv-cqs/` that I'm trying to use with the relevant packages. There's also an input file at `~/Code/APPRES-483/LOCAL-query-definition.yml`. Normally, if I was running this in the commandline, I'd type out something like the following:

```
python3 . --verbose --file-to-write ../../LOCAL-query-definition.yml 
```
So I made a launch.json, I activated my virtual environment in the vs code terminal.

Here's my launch.json

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Module",
            "type": "python",
            "python":"${env:HOME}/Code/APPRES-483/venv-cqs/bin/python",
            "request": "launch",
            "module": "__main__",
            
            "args":[
                "--verbose",
                "--file-to-write", "/../../LOCAL-query-definition.yml"
            ],
        }
    ]
}
```

 But it appears that launch.json isn't recognizing my arguments for the program correctly. I see this in my terminal.

```
(venv-cqs) 8c859081d52b:update-query-definition bineyb$  cd /Users/bineyb/Code/APPRES-483/cqs/update-query-definition ; /usr/bin/env /Users/bineyb/Code/APPRES-483/venv-cqs/bin/python /Users/bineyb/.vscode/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/launcher 50826 -- -m __main__ --verbose --file-to-write /../../LOCAL-query-definition.yml 
debugpy 1.4.3
See https://aka.ms/debugpy for documentation.

Usage: debugpy --listen | --connect
               [<host>:]<port>
               [--wait-for-client]
               [--configure-<name> <value>]...
               [--log-to <path>] [--log-to-stderr]
               <filename> | -m <module> | -c <code> | --pid <pid>
               [<arg>]...

Error: unrecognized switch --verbose
```

I'm basically having the issue described here: https://github.com/Microsoft/vscode/issues/2167
except, I'm definitely not making the same error.

## Environment data

- VS Code Version: Version: 1.60.2 (Universal)
- Extension version: 2021.9.1246542782
- OS Version: Mac/OSX, Darwin x64 19.6.0
- Python version: 3.9.7
- Type of virtual environment used: virtualenv

## Expected behaviour

I would think my launch.json should be able to pass the --verbose, --file-to-write arguments correctly to the debugger and allow it to boot.

## Actual behaviour

The debugger always generates the "error unrecognized switch" for whatever I set as the first argument in args, and never launches

**Comment by int19h** [comment]
The command line that is produced looks correct to me - `debugpy.launcher` will spawn your process and pass over any arguments after the `--`. 

The problem, rather, is that `__main__` is a special name - it is assigned to the Python script is the entrypoint for a given Python process. And when debugging with debugpy, that's going to be debugpy. Hence why when you tell it to `-m __main__`, it basically just runs debugpy instead of your code.

If you're using `__main__`, that means that the entire directory it is contained in is an executable package, and can be run as if it were a file; debugpy supports this usage:
```json5
"program": "${env:HOME}/Code/APPRES-483/cqs/update-query-definition/"
```

I believe the change should fix the issue for you. However, debugpy should also try to present a clean environment to the debuggee, so I'll keep this issue open to track cleanup of `sys.modules["__main__"]`.
