### ISSUE TITLE
User Uncaught Exceptions setting should be false by default

### ISSUE THREAD

**Issue by RobertCsordas** [microsoft/debugpy#751]
## Environment data

-   VS Code version: 1.61.0
-   Extension version (available under the Extensions sidebar): v2021.10.1317843341
-   OS and version: Ubuntu 20.04.2 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: pytorch (troch==1.9.0)
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

The following code should not raise an exception.

```python
import torch.utils.data


class Cls():
    def __getattr__(self, item):
        raise AttributeError()


o = Cls()
print(isinstance(o, torch.utils.data.IterableDataset))

```

## Actual behaviour

The code stops on the "raise AttributeError()" line and shows an exception is raised. If one clicks "Continue", the code continues correctly. But it is still pretty annoying to click it every single time it happens in a big project.

If one runs it from the terminal without VSCode debugger, it runs without issues.

## Steps to reproduce:

Run the code above from vscode. The launch.json entry for it:

```json
{
    "type": "python",
    "request": "launch",
    "name": "Debug File",
    "justMyCode": false,
    "program": "${file}",
    "cwd": "${fileDirname}"
}
```

### Other

It might be related to https://github.com/microsoft/vscode-python/issues/17687, but not sure.

**Comment by fabioz** [comment]
@sknowles0143 they do happen when running outside of VSC, the only difference is that when running inside of VSC they are shown to you due to the `User Uncaught Exceptions`.

I believe you're confusing this with `Uncaught Exceptions`.

i.e.: `User Uncaught Exceptions` appear when an exception is raised in user code and ends up being handled inside some library, whereas `Uncaught Exceptions` appear when the exception isn't handled anywhere (which would show only when a thread/program would finish due to it).

**Comment by adebuyss** [comment]
This is also an issue when using @property decorators. Since the debugger appears to to now call hasattr on an uninstantiated object on file import, this can cause exceptions or other bad behavior. I am seeing an import loop due and other problems due to this bad behavior. For instance, any accessor using 'self' is likely to throw an exception now since the 'self' argument in this case is really 'cls'.

**Comment by lordmauve** [comment]
What constitutes "user code" vs "library code"? We're seeing the debugger stop on exceptions that are fully raised and caught in library code.

**Comment by fabioz** [comment]
> What constitutes "user code" vs "library code"? We're seeing the debugger stop on exceptions that are fully raised and caught in library code.

In general anything in site-packages and lib is library code, anything else is user code... 

So, any exception that at some point passes through user code (even if originally raised in library code) and then keeps on being raised until it reaches library code is considered here.

In general, this is nice for test frameworks, which can stop at caught exceptions inside those -- and can under some circumstances -- show actual errors of unexpected exceptions, but it seems it's also common under some frameworks to work this way (so, the default should probably be opt in instead of opt out).

A second step as @int19h mentioned would be trying to discover those common scenarios to skip those, but this is probably a much harder task (given that finding which are the common cases where this shouldn't be reported is hard).

Given that initially this was done to support showing exceptions that are handled in unit-testing frameworks, maybe we could whitelist for those frameworks instead of blacklisting other scenarios (in which case the breakpoint would be renamed to something as "Exceptions caught by test frameworks").
