### ISSUE TITLE
ImportErrors with django when invoking debugpy; works fine without debugpy call

### ISSUE THREAD

**Issue by Breich90** [microsoft/debugpy#779]
## Environment data

- debugpy version: 1.5.1
- OS and version: Docker
- Python version (& distribution if applicable, e.g. Anaconda): Python:3.6 (which is 3.6.15 at the moment)
- Using VS Code or Visual Studio: VS Code but invoked from command line
- Django 1.11.3

## Actual behavior

Attach VSC to running container ->
CD to code dir (dir where codebase is copied to in the docker build)
`python -m debugpy --listen localhost:5678 manage.py test`
```
======================================================================
ERROR: code.package1 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: code.package1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
ModuleNotFoundError: No module named 'code.package1'; 'code' is not a package
```
etc for all packages

Yet `python manage.py test` runs fine.

## Expected behavior

`python -m debugpy --listen localhost:5678 manage.py test` imports packages properly and `manage.py test` runs
Note I'm able to successfully attach the debugger, its just the packages aren't importing.  FWIW `ptvsd` was doing the same thing

## Steps to reproduce:
I haven't really tested this outside our codebases but I would suspect that spinning up a barebones django project, importing a few packages in a test file and then running `manage.py test` would cause the same issues.

**Comment by fabioz** [comment]
The fix is renaming your `code` package to a different thing (to avoid the conflict with the standard library module of the same name).

This happens because the debugger pre-imports some standard library modules and one of those is `code`... I find it strange that it didn't find your own version of the `code` package when it did that `import code` (which would've given you a better error message).

I guess this is due to django lazily loading your modules (so, initially your own code wasn't loaded because it wasn't on the `PYTHONPATH` and later on, when `import code` is actually run for django, it'll find the `code.py` from the standard library which was already loaded and not the one you have defined in your project).

I can't really think of any other workaround (the real fix is not having names conflict with standard library modules).
