### ISSUE TITLE
Don't do eval/exec inside of `except` clause

### ISSUE THREAD

**Issue by thegunslingers** [microsoft/debugpy#812]
## Environment data

- debugpy version: 1.5.1
- OS and version: Win 10
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.9 via Anaconda
- Using VS Code or Visual Studio: VS Code

## Actual behavior

In the debug console of VS Code there is a syntax error when using an f string in an assert statement. The same line does not produce a syntax error without a debuger or in VS Code when using run and debug.

## Expected  behavior

For the example script below there should be no syntax error when trying to run a line similar to below in the debug console.

```python 
assert testval >200, f"Test Value was not greater than 200, the value was {testval:d}"
```

## Steps to reproduce:
1. Create an example script like below and set a breakpoint on the assert line
2. Start a debugging session in VS Code
3.  Open the debug console and run the assert line. (Observe the syntax error that is raised before being caught by the assert error
4. In the debugging session run the next line (the same assert line and observe no syntax error before the assert error is raised).

Example Script:
```python
testval = 100
assert testval >200, f"Test Value was not greater than 200, the value was {testval:d}"
```

**Comment by int19h** [comment]
The reason why this happens is that we try to evaluate the code as an expression first (so that we can print out the result if there is one), and only if that fails, try treating it as a statement. Basically something like:
```py
try:
    code = compile(src, "<string>", "eval")
except Exception:
    code = compile(src, "<string>", "exec")
```     
Since `assert` is a statement, the first `compile()` fails, and we fall back onto the second one. But then when we actually try to eval it, the assertion itself fails. Since the eval is also in the except-block, it is treated as a chained exception, and when Python prints out the traceback, it prints the original exception (i.e. `SyntaxError` in this case) first, followed by `AssertError`. 

The same issue appears if you try to run e.g. `raise Exception`, or `if True: 1/0` - basically, any statement that is not a valid expression, and that raises an exception.

To avoid this, we shouldn't be doing `eval()` while handling the exception. Note, however, that this will not preclude the `SyntaxError` from actually happening - it's by design - but only from being reported alongside the actual error.

**Comment by thegunslingers** [comment]
Thanks for the explanation!

**Comment by rftw** [comment]
I too came across a similar issue and wondered why the debug console is complaining about a syntax error.
A simple fix could be to suppress the exception chaining like:
```
try:
    code = compile(src, "<string>", "eval")
except Exception:
    try:
        exec(compile(src, "<string>", "exec"))
    except Exception as e:
        raise e from None
```
