### ISSUE TITLE
Comprehension list in Debug Console doesn't get updated

### ISSUE THREAD

**Issue by CryptoCashCashoo** [microsoft/debugpy#815]
### VS Code version

1.63.2

### Extension version

v2021.7.1060902895

### OS type

Linux

### OS version

20.04

### Python distribution

Anaconda

### Python version

3.8

### Language server

Pylance

### Expected behaviour

If I'm stoped at some point of the code and in the Debug console I run the following:
```[python]
lis = ["abc","efg"]
for l in lis:
    print(l)
    result = [l[i] for i in range(3)]
    print(result)
```

I expect the console to print:
"abc"
['a'.'b','c']
"efg"
['e','f','g']

### Actual behaviour

The response is:

abc
**['e', 'f', 'g']**
efg
['e', 'f', 'g']

### Steps to reproduce

Stop at any point of your code with a  breakpoint, open the debug console and insert the code provided above.

![image](https://user-images.githubusercontent.com/83143288/148479422-603543b5-5e49-4d1e-a5a6-78ecdbaa069b.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by int19h** [comment]
It looks like the problem is that newly created variables aren't immediately accessible. If I try to repro it on a simple one-line hello world script, the first time I get this:
```py
lis = ["abc","efg"]
for l in lis:
    print(l)
    result = [l[i] for i in range(3)]
    print(result)
```
```
abc
Traceback (most recent call last):
  File "c:\Users\pminaev\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_vars.py", line 420, in evaluate_expression
    compiled = compile_as_eval(expression)
  File "c:\Users\pminaev\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_vars.py", line 374, in compile_as_eval
    return compile(_expression_to_evaluate(expression), '<string>', 'eval')
  File "<string>", line 1
    lis = ["abc","efg"]
        ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "<string>", line 4, in <listcomp>
NameError: name 'l' is not defined
```

(`SyntaxError` is a known artifact and can be ignored - the real error here is that `l` is not defined.)

But then doing it again (without resuming the debug session) shows this:
```py
lis = ["abc","efg"]
for l in lis:
    print(l)
    result = [l[i] for i in range(3)]
    print(result)
```
```
abc
['a', 'b', 'c']
efg
['a', 'b', 'c']
```
So it looks like it uses the value of `l` as it was at the end of the previous eval. It seems to be specific to the range variable used in `for`, though, since `lis` and `result` are correctly assigned and read, as is `i` in the list comprehension.

Note that this only happens if the range variable is in the current stack frame of the debuggee. If you force a new frame, e.g. by creating a function and then immediately calling it, everything works as it should:
```py
def f():
    lis = ["abc","efg"]
    for l in lis:
        print(l)
        result = [l[i] for i in range(3)]
        print(result)
f()
```
```
abc
['a', 'b', 'c']
efg
['e', 'f', 'g']
```
So this can be used as a workaround until we figure out the underlying issue.

**Comment by fabioz** [comment]
As a note, the related place in the code is:

https://github.com/microsoft/debugpy/blob/main/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py#L422 (inside of `def evaluate_expression(py_db, frame, expression, is_exec):`).

Getting this right is indeed tricky because `frame.f_globals`/`frame.f_locals` are special and usually require a call to `PyFrame_LocalsToFast` to work accordingly when local variables are changed from eval/exec. In this case, the locals are mutated but as that call isn't made between calls Python doesn't recognize it as it should... (that is already called across evaluate calls, so, simple statements work if issued once at a time -- I need to investigate more to see if we can overcome this limitation in this case).

**Comment by CryptoCashCashoo** [comment]
Thanks!
