### ISSUE TITLE
Show lambda functions in "Step Into Targets" 

### ISSUE THREAD

**Issue by rftw** [microsoft/debugpy#826]
Hi, is it possible to show lambda functions when using "Step Into Targets". It will be extremely useful for people who use pandas a lot.

![image](https://user-images.githubusercontent.com/55868021/150865727-ed440521-b5a3-4d41-8675-0f505fe1a18b.png)

**Comment by fabioz** [comment]
I don't think it's feasible to do this because there's no real way to know the caller of that lambda to indicate the scope where it'll be called as in this case there's no call for it in the current scope, which is required for the step into to work (i.e.: the lambda may be called inside of `apply`, but it may also be called inside of some other function inside of the `apply` many levels deep or may not be called at all because there's no way to know where that lambda may be called).

The step-into works because it can determine both the call site (which is the place the debugger is currently paused) and the caller, so, it'll stop accordingly (it'll actually determine the proper bytecode at the caller and then stop when a function is called exactly at that bytecode location in the parent frame). 

The workaround for you is just leave a breakpoint in that location and resume the execution until it hits that lambda in the breakpoint...
