### ISSUE TITLE
Hang with "redirectOutput":true and too much output

### ISSUE THREAD

**Issue by oliviercwa** [microsoft/debugpy#83]
Hello,
I am debugging Python code in VS Code and and in the middle of the debugging session, at random time, it hangs. Everything is still responsive and you can interact with everything, but the execution is frozen and anything related to debugging does not evaluate. I try to press F5, click on the Start button, but the debugging session does not continue.

Notes:

- It can also happen after when it hits a breakpoint and I type a debug command. Once it happens, there's a small arrow that appears to the left of the last command that was sent to the debug windows. All subsequent commands will show the same sign to the left (no evaluation performed). Also threads are shown as paused and clicking on resume does nothing. Again the VS code window is responsive, just the debugging seems frozen.
- It also happens when using RUN WITHOUT DEBUGGING. But it does not happen when running outside of VS Code from a Powershell windows for example.
- The only way to continue is to STOP and restart.

This is very painful as prevents the ability to debug Python in good conditions.

Environment:
OS: Windows_NT x64 10.0.19041
Python: 3.7.4 64 bits
VS:
  Version: 1.43.1 (user setup)
  Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
  Date: 2020-03-18T07:01:20.184Z
  Electron: 7.1.11
  Chrome: 78.0.3904.130
  Node.js: 12.8.1
  V8: 7.8.279.23-electron.0

**Comment by int19h** [comment]
With "redirectOutput", we read debuggee's stdout and stderr, convert them to "output" events, and then tee them into the launcher's stdout/err.

The problem is that with "internalConsole", the launcher's stdout/err is also redirected by the adapter to its stderr. If nothing is reading from there, then the entire logical pipe gets clogged eventually - i.e. it freezes once the buffers are filled up. We are kinda assuming that adapter's stderr is going to be drained by the client, but this is not guaranteed. 

The fix is for the adapter to stop trying to tee launcher's stdout to its stderr if "internalConsole" is in effect, and stdout is used for DAP. It should just dump it all to /dev/null.

**Comment by oliviercwa** [comment]
Just some additional information. I was actually to repro the bug even when using "integratedTerminal" or "externalTerminal". As @ssouques mentioned, it seems related to the number of data that goes through the debug output. For example, if I print a few dataframe, it hangs very rapidly.

**Comment by oliviercwa** [comment]
It seems to work with ```"redirectOutput":false```. I will use it trough out the day and report back if otherwise Thank you for your help!

**Comment by int19h** [comment]
@oliviercwa, did you have it explicitly set to true in your launch.json before? It should default to false if you have "integratedTerminal", so you should be able to just omit it. If that's not working somehow, that would be another bug.

**Comment by oliviercwa** [comment]
I did not have it before, so the default value was used.
I have noticed you closed the bug, but right now, we can't debug reliably using the internalConsole or integrateTerminal. Is there a plan to fix this issue?

**Comment by int19h** [comment]
The fix is already in master - it's in the commit referenced from the message that says that issue is closed. It'll be in the next debugpy prerelease, and from there, in the next extension release.

In the meantime, the suggested workaround is to use `{"console":"integratedTerminal", "redirectOutput":false}` - this should avoid the bug while still giving you access to the output of your app.

You can also use the most recent debugger bits directly from GitHub to get the fix early. Just clone this repository somewhere - say, `C:\git\debugpy` - and then you can do this in your launch.json:
```json5
"debugAdapterPath": "C:\git\debugpy\src\debugpy\adapter"
```
(However, this skips building native modules that debugger uses to speed things up, so it will be a bit slower than the version packaged with the extension.)
