### ISSUE TITLE
launch.json option for debugpy.debug_this_thread()

### ISSUE THREAD

**Issue by dakotajunkman** [microsoft/debugpy#840]
Currently, to debug Python scripts called by external applications (e.g. Python being called by MATLAB) it is necessary to import debugpy and call debugpy.debug_this_thread() at the top of the file. I am proposing a launch.json option that handles this, or some other way to no longer need to manually add this statement to a Python script in order to properly debug.

**Comment by dakotajunkman** [comment]
Thanks for the feedback. My current workflow is to use attach-to-pid within the launch.json to attach to an external process. However, when calling Python from that external process, breakpoints are not respected unless `debugpy.debug_this_thread()` is entered in to the file that is called. The hope is to no longer need to include that marker.

**Comment by int19h** [comment]
Note that the issue here isn't actually about hosted Python, but rather about the manner of starting threads. This same issue arises in regular Python apps when they use libraries (like Qt) that start their own OS threads and *then* run Python code on them - the debugger can intercept those threads that are started via `threading` and other standard mechanisms, but it can't do so for an arbitrary thread. 

This is fundamentally a CPython limitation - there's no API available to us to detect initialization of Python on a given thread. Thus we provide `debug_this_thread()` as a workaround, but we can't really do anything better here right away. What could be done, however, is a PEP to add the API that we need to CPython.
