### ISSUE TITLE
Support ReadMemory request in Debug Adapter

### ISSUE THREAD

**Issue by geajack** [microsoft/debugpy#848]
I'm not sure if this is the correct place to report this issue, but I'm trying to develop a debugger extension for VS Code that would include the ability to inspect numpy arrays in python code. Existing extensions that do what I'm trying to do just send an `evaluate` request to the Debug Adapter to get it to save the array to a file, and then inspect that. I was hoping it would be possible to do it all over the DAP, and I found out about the [ReadMemory](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_ReadMemory) request in the DAP. However, it seems that the Python DA does not support this feature, as when I inspected its response to the [`initialize` command](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Initialize) in my extension, the `supportsReadMemoryRequest` field is absent.

It's possible I'm misunderstanding the DAP docs. The flow I was imagining was:

1. Evaluate a Python expression for a numpy array using an `evaluate` request.
2. Get the `variablesReference` field of the response and issue a [`variables` request](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Variables) for it. (I've gotten this far)
3. Get the [`memoryReference`](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Variable) field from the response and issue a `readMemory` request for it. (the `memoryReference` field is not present on responses from the Python DA, so I'm stuck here)
4. The `data` field of the response will now contain the base64 raw bytes of the numpy array. Decode them from base64 in JavaScript, and presumably painstakingly research how numpy arrays are stored in memory to interpret the resulting bytes and do what I need with them.

If I'm completely misunderstanding the docs and the `readMemory` request would not allow me to do this, then this feature request is invalid.

**Comment by geajack** [comment]
> We didn't implement this because there's no good way to obtain the memory representation of an arbitrary Python object.

That's interesting. Is there an archived public discussion about this? I'm not really much of a low-level guy, but the only reason I can think of would be pointers - is it that most Python objects include lots of pointers to other data, which would then be meaningless to the process on the other side of the DAP?

> The trick that we use in notebooks is to issue an evaluate request that produces a value, and retrieve that value - this way you don't have to muck around with temp files etc. While the result is always a single value, this can be a string with e.g. JSON inside, which you can then parse on the other end

So in short, basically base64 encode the string in Python and send it over directly through `evaluate`, right?

**Comment by int19h** [comment]
It's more that we don't operate on the level where the pointers can be readily obtained - this requires native code, but the debugger is supposed to be fully functional even when running pure Python, just slower. But also, yes, most Python objects consist entirely of pointers to other objects, so interpreting them as binary data doesn't make much sense. In other cases the representation of the objects is basically an implementation detail (e.g. strings), and encoding cannot be guaranteed.

For my suggestion, you don't need to base64-encode anything, since strings can be marshalled just fine via JSON already. If you use JSON for your own structuring, you'll end up with JSON-in-a-string-literal-in-JSON, which looks ugly on the wire because of all the escaping necessary, but works fine otherwise.
