### ISSUE TITLE
Debugpy connection times out during Autodesk Maya boot

### ISSUE THREAD

**Issue by nambread** [microsoft/debugpy#859]
Autodesk Maya has a mechanism for extending functionality by way of plugins. Many of these plugins will use a feature where a python module named "userSetup.py" will be executed on application launch. See the ["Initializing the Maya Environment in and for Python" section here.](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2020/ENU/Maya-Scripting/files/GUID-C0F27A50-3DD6-454C-A4D1-9E3C44B3C990-htm.html)

I've found that the debugpy server will not connect whilst this userSetup.py is being executed. If you wait until Maya is completely booted and idle, then the connection works as expected.

I have used standalone pydev before in eclispe and pycharm, and have been able to connect during the boot sequence fine, but would need to recheck on latest versions if that's still the case.

## Environment data

- debugpy version: 1.5.1
- OS and version: Windows 10 Version 10.0.19042 Build 19042
- Python version 2.7 bundled with Autodesk Maya 2022 & 2018
- Using VS Code or Visual Studio: VS Code

## Actual behavior

The maya boot process will stall as expected during debugpy.wait_for_client(), but vs code will time out when trying to connect.

## Expected  behavior

The debugger should connect at launch and allow breakpoints to be set and hit in any python code.

## Steps to reproduce:
1. Download and install Maya 2022 or 2018
2. If downloading Maya 2022 set the environment variable MAYA_PYTHON_VERSION to 2
3. Download the attached zip file, extract to a folder [debugpy_not_connecting_during_boot.zip](https://github.com/microsoft/debugpy/files/8181667/debugpy_not_connecting_during_boot.zip)
4. Open the extracted folder as a workspace in VS Code
5. In the folder extract the file connection_repro.mod to %USERPROFILE%\Documents\maya\modules
6. Update the paths in the .mod file to point to the folder containing the "scripts" folder that you just unzipped
7. In scripts/userSetup.py, update debugpy_location on line 8 to point to your local debugpy installation
8. Ensure port 5678 is clear on your current machine.
9. Boot Maya
10. Observe the Maya boot process has hung, as it is awaiting a connection to debug py
11. Using the launch config in .vscode/launch.json, remotely connect to the debugger
12. Observe that the connection does not work and maya remains hung
13. Use task manager to close any open Maya instances
14. open scripts/userSetup.py and comment out the call to await_debugger_attach() on line 36
15. Reboot Maya, it will not attempt to connect on boot now
16. [Instead, after the boot is complete, run the line await_debugger_attach() in Maya's script editor](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2020/ENU/Maya-Scripting/files/GUID-7C861047-C7E0-4780-ACB5-752CD22AB02E-htm.html)
17. Observe Maya once again hang as it waits for a connection
18. Connect via the same launch config used in step 9
19. Observe that this time the debugger connects

**Comment by fabioz** [comment]
Python 2.7 has a great flaw in that trying to setup the debugger / tracing inside some import will deadlock and there's no way around it for Python 2.7 (this has to do with how it locks imports and deals with tracing and is the reason why the debugger must pre-import all its requisites instead of lazy-loading modules).

So, this will really only work on Python 3 (and there's no way around it for Python 2.7).

For the attach to PID if it's a custom build of Python it's really possible that the attach to PID won't work (but this needs more investigation on how Maya works and if it doesn't work it would probably need fixes on Maya itself, not on the debugger, although this would need further investigation to be completely sure about it -- @int19h @karthiknadig do you think this warrants further investigation on our side?).

I'm closing the bug given that the reported issue is really expected not to work with Python 2.7 (we can reopen if further investigation should be done for the attach to pid with Maya).
