### ISSUE TITLE
debugpy update to version v1.6.0 doesn't support Python 2.7

### ISSUE THREAD

**Issue by lemueljay** [microsoft/debugpy#884]
Hi, all. 

I am using a VS Code extension called [Python ](https://code.visualstudio.com/docs/languages/python), and I would like to raise this issue that ever since we upgraded to debugpy v1.6.0, it now doesn't support Python 2.7 debugging.

It would be very great to have a fix for this to support Python 2.7 just like the previous releases. Thank you very much. Your help is very much appreciated. 

## Environment data

- debugpy version: 1.6.0
- OS and version: WIN 10
- Python version: Python 2.7
- VS Code

## Actual behavior

Before the April update, I was still able to run the debugger. But currently, I get issues like `import _thread as thread`. I think this is mainly because I am running the debugpy from a Python 2.7 interpreter. I tried to convert some of the lines to support Python 2 but I am still getting issues. 

I rolled back and installed the February release and it works fine for me.

## Expected  behavior

It's expected that I should be able to run the debugger with no issues when using the latest release of debugpy.

## Steps to reproduce:
1. Set your interpreter to Python 2.7
2. Run the debugger.
3. It throws out an error like `import _thread as thread`

**Comment by int19h** [comment]
This is by design - we no longer support Python 2.7. For what it's worth, [neither does VSCode](https://github.com/microsoft/vscode-python#python-extension-for-visual-studio-code).

Note that Python 2.7 has been unsupported by upstream (i.e. PSF) for over two years, so it's basically legacy all around - even most libraries have dropped support by now. If you can't migrate to a newer version, you'll have to use an older version of the VSCode extension.

**Comment by fabioz** [comment]
Note for those that can't upgrade: the workaround is downgrading to the python `v2022.2.1924087327` version (which has the last version of the debugger supporting Python 2.7).
