### ISSUE TITLE
Add sudo support without an external terminal

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/debugpy#91]
According to the docs, it is possible to debug as `sudo` using an external terminal for the password input.

This doesn't work when debugging remotely, for that you need the integrated terminal and therefore can't sudo.

A use case for this is Raspberry Pi development - connecting remotely and needing to run as sudo to control certain hardware.

**Comment by int19h** [comment]
If  `"sudo":true` is specified in launch.json, we basically just prepend `sudo` to the command line. So long as there is any terminal at all - whether it's `"console":"externalTerminal"` or `"integratedTerminal"` - that's where sudo runs, and where password can be entered. Is there something going wrong with that?

For `"console":"internalConsole"` there is indeed no terminal to input the password from - the reason why we still allow `"sudo"`  in this case is because it can be configured to skip the password prompt altogether.

**Comment by int19h** [comment]
Your launch.json is set to start `"${file}"`, i.e. the file you currently have open in the editor. So when you have launch.json open, it tries to start it as if it were a Python script - all the errors that you're seeing come from Python itself trying to run it. Note the last argument in the command line in the terminal:
```
pi@raspberrypi:~/LightPi/app $ ... debugpy/launcher /home/pi/LightPi/app/.vscode/launch.json 
```

**Comment by jimbobbennett** [comment]
![](https://media.giphy.com/media/8WdsK61D9YOOc/200.gif)

Apologies for wasting folks time with such an obvious mistake on my part. I shall now hide away in embarrassment.

Thanks @int19h!

**Comment by int19h** [comment]
No worries, it happens - we all do it every now and then!

**Comment by BitCalSaul** [comment]
> If `"sudo":true` is specified in launch.json, we basically just prepend `sudo` to the command line. So long as there is any terminal at all - whether it's `"console":"externalTerminal"` or `"integratedTerminal"` - that's where sudo runs, and where password can be entered. Is there something going wrong with that?
> 
> For `"console":"internalConsole"` there is indeed no terminal to input the password from - the reason why we still allow `"sudo"` in this case is because it can be configured to skip the password prompt altogether.

Could we configure the password in the launch.json?
