### ISSUE TITLE
VSCode debugger looks for python in a directory that does not exist even though python is being run from another environment that is active

### ISSUE THREAD

**Issue by rbavery** [microsoft/debugpy#926]
Issue Type: <b>Bug</b>

# Behaviour

I run the debugger and it doesn't look for python 3.9 in '~/.local/lib' after it correctly uses the python environment in my conda environment to launch the debugger.

## Expected vs. Actual

I run the debugger like so

```
(fastai2) root@ml-jupyter-b7f19843-f258-99fc-b0bc-fbbc7ca10744:~/work#  cd /root/work ; /usr/bin/env /root/miniconda3/envs/fastai2/bin/python /root/.vscode-server/extensions/ms-python.python-2022.4.0/pythonFiles/lib/python/debugpy/launcher 34175 -- /root/.vscode-server/extensions/ms-python.python-2022.4.0/pythonFiles/testlauncher.py /root/work pytest --rootdir /root/work --override-ini junit_family=xunit1 --junit-xml=/tmp/tmp-1857gwM7hbSMdi0g.xml ./tests/test_coco_parse.py::test_coco_parse 
```

and end up getting an error in posixpath.py

```
[Errno 2] No such file or directory: '/root/.local/lib'
  File "/root/miniconda3/envs/fastai2/lib/python3.9/posixpath.py", line 167, in islink
    st = os.lstat(path)
  File "/root/miniconda3/envs/fastai2/lib/python3.9/posixpath.py", line 426, in _joinrealpath
    if not islink(newpath):
  File "/root/miniconda3/envs/fastai2/lib/python3.9/posixpath.py", line 392, in realpath
    path, ok = _joinrealpath(filename[:0], filename, {})
  File "/root/miniconda3/envs/fastai2/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/fastai2/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
```

If I artificially create the lib folder it looks for a python3.9 folder in lib/

## Steps to reproduce:

I'm not sure how one would reproduce this but I'll try to provide as much detail as I can

I'm running vscode remotely on an AWS instanc, using a custom conda environment and testing with pytest installed in the conda environment.

I made a simple test here that causes the error so it seems to be an issue with the debugger and not something specific to the python code being tested

```
import pytest


def test_test():
    print("test")
```

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "black"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: true
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.4.0
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:41.156Z)
OS version: Linux x64 5.4.0-107-generic
Restricted Mode: No
Remote OS version: Linux x64 5.13.0-1021-gcp

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.31GB (21.54GB free)|
|Process Argv|--unity-launch --crash-reporter-id 87736c97-e58f-4780-9c5e-2f5f8c2ac377|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|unity|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|unity|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: icevision-Trainer|
|OS|Linux x64 5.13.0-1021-gcp|
|CPUs|Intel(R) Xeon(R) CPU @ 2.30GHz (4 x 2299)|
|Memory (System)|14.64GB (12.99GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by int19h** [comment]
Note that using "python" overrides the interpreter used to run, but does not override the *environment* that is selected in the drop-down on the status bar; if the latter is something activatable, then it will be activated regardless. I'm not entirely sure what the effect of activating the environment and then using an interpreter from the outside would be, but it might be worth checking to make sure that they match first.

**Comment by rbavery** [comment]
@int19h thanks for the advice. This error occurs when I don't edit the launch.json beyond changing justMyCode. are you saying I need to edit `"type": "python",` to be something else? how would I check what `"type": "python"` refers to?

**Comment by rbavery** [comment]
I can confirm I'm using the correct conda environment but I'm not sure what other python you are referring to and how I would check which python it refers to.

**Comment by int19h** [comment]
I was referring to this bit:
```json5
"python": "/root/work/test-icevision/bin/python"
```
(`"type": "python"` just tells VSCode that this is a Python debug config; it doesn't affect the interpreter used)

debugpy will use this binary to spawn your process, but it's not aware of things such as virtual environments and their activation - VSCode or other client is what normally takes care of those. However, in VSCode, it's driven by the dropdown rather than your launch.json. So if you set the environment to one thing, but then point the debug configuration at an interpreter for a different environment, things might get weird.

**Comment by rbavery** [comment]
I'm happy to provide anymore info I can about this issue. It's currently blocking me on a project, so it's personally priority 1 for me to fully debug programs running on remote vms, with either virtual environments or conda environments

**Comment by rbavery** [comment]
I've also tried to do this in my base conda environment, no virtual environment, and no change to the launch.json except for the justMyCode flag. same error.

**Comment by fabioz** [comment]
@rbavery I think the issue you're having is that it's showing regular exceptions because you have `Raised Exceptions` checked... if you don't want it to stop at exceptions, please uncheck that.

i.e.: that's not a bug, you have the option to show `Raised Exceptions` selected, so, the debugger (correctly) stops at all raised exceptions (note that if you leave `justMyCode:true`, it'll only stop at exceptions in your code, not in the standard library).

**Comment by rbavery** [comment]
this ende dup being the issue. Thanks. I think this should be addressed in the ui somehow so people aren't caught by this.

**Comment by krlng** [comment]
Just ran into this. I also think it is a bit unlucky. My workflow (probably a typical one) was: I needed a breakpoint to debug what was going on in a third-party library, so I deactivated the justMyCode option. Then I got those weird errors of Python versions and tried all kinds of configurations because I suspected that the `justMyCode` would only affect break-points and not exceptions.

**Comment by thebirdgr** [comment]
A random solution but reloading my python extension fixed this issue for me.

**Comment by subhashb** [comment]
@rbavery Thank you for having raised this and done the hard work of digging through the issue. 🙏

In my case, the issue flared up suddenly. One test run, everything was fine. The next, debugging broke.

Does this mean we can never have the combo of `"justMyCode": false` and `Raised Exceptions`? That's unfortunate.

**Comment by hedkar** [comment]
I just came here to say I wasted a _lot_ of time on this same issue, most likely having ticked the Raised Exceptions box by mistake. Thank you for having this issue documented. 
Just like @subhashb, my experience was that debugging just suddenly stopped working. Endless back-and-forth with Copilot Chat couldn't help pinpoint the issue either. I would also suggest a warning of some sort if the culprit is a combination of "justMyCode: false" and "Raised Exceptions".

**Comment by rchiodo** [comment]
Sounds like a separate setting for exceptions might work. `JustMyBreakpoints` and `JustMyExceptions` but that might be even more confusing.

**Comment by rchiodo** [comment]
Or maybe nobody ever wants to stop on raised exceptions in code that isn't user code? So that 'justMyCode' : false wouldn't apply to exception handling.

**Comment by int19h** [comment]
The usual scenario for wanting exceptions in library code is when you're working on said library, or need to debug a library that you're using - exactly the same rationale as for breakpoints. It's not particularly common, but when you need it, it makes for a big difference.

That said, the current overall design of "just my code" and how it interacts with exceptions is derived from what it has been in PTVS, minimally adjusted for VSCode. And PTVS in turn derived it from what C# and C++ VS project systems do. 

My gut feel says that the real culprit here is the need for `"justMyCode":false` in this scenario. That setting should be very rare, and if it's not, it means that there's some other gap in functionality. Note, by the way, that this isn't just about breakpoints and exceptions - JMC also affects stuff like Step In.

If the specific use case is "I want to be able to hit a breakpoint in library code", then maybe having an explicit breakpoint set in a file should override JMC for that particular breakpoint. After all, the user is already explicitly requesting that particular path, that is as unambiguous as it gets.
