### ISSUE TITLE
Allow for launching console_scripts or their specs

### ISSUE THREAD

**Issue by thejcannon** [microsoft/debugpy#955]
Howdy! Love the tool!

I have a use-case for being able to launch a debug server with each of the following:
- Specifying both module and function (e.g. `path.to.mod:main`) 
- Specifying a console script (e.g. inside a virtualenv I might launch `pytest`, I'd like to `debugpy ... pytest`).

Thanks again!

**Comment by int19h** [comment]
For module + function, I would suggest using "code". It's not in the VSCode schema for the configuration, but it should still work if you specify it, despite the squiggles. And then you can do something like:
```json5
"type": "python",
"request": "launch",
"code": "import foo; foo.bar()"
```

For `pytest` and most other tools that are installed as scripts (e.g. pip), you can usually run them as modules, i.e. `debugpy ... -m pytest` or `"module": "pytest"` in launch.json. However, the script name doesn't always match the module name, so doing this automatically might not be reliable. And we do need to be able to go via python.exe so that we can inject our own code in the right places - I don't think the stubs allow for any of that.

**Comment by thejcannon** [comment]
Ah I should clarify, I'm launching `debugpy` directly as part of my build tools, so VS Code doesn't come into play for server launching.

---

The more detailed background here is I'm adding a feature to the excellent [Pantsbuild Build System](https://www.pantsbuild.org/) to launch the relevant _thing_ with `debugpy` when requested. In this case Pants (the build tool) supports mode/module+function/console_script.

**Comment by thejcannon** [comment]
I think for the `console_script` case, `importlib.metadata` would suffice? https://docs.python.org/3/library/importlib.metadata.html#entry-points

**Comment by int19h** [comment]
For the debugpy server CLI, "code" corresponds to the `-c` switch, same as in regular Python:
```
debugpy ... - c "import foo; foo.bar()"
```

**Comment by thejcannon** [comment]
> I think for the `console_script` case, `importlib.metadata` would suffice? [docs.python.org/3/library/importlib.metadata.html#entry-points](https://docs.python.org/3/library/importlib.metadata.html#entry-points)

Since `importlib.metadata` was added in 3.8, and finding `console_scripts` is nontrivial. @int19h , how likely would a PR be accepted which vendors [`importlib_metadata`](https://pypi.org/project/importlib-metadata/) until 3.7 is dropped?

**Comment by int19h** [comment]
We already have vendored code under ASL, so that shouldn't be a problem. But I'm hesitant to add a non-trivial package for a what feels like fairly exotic use case. Although I may be wrong here - is there any particular Python tool that ships a console script without the corresponding Python package that can be directly invoked with `-m` (and thus debuggable via "module")?

**Comment by thejcannon** [comment]
Well, if I wanted to use `-m` (or the `-c` case above for functions) I'd have to hardcode or assume the module/function names. Which I can't do in our build system as these are user-provided values :sweat_smile:

**Comment by int19h** [comment]
Oh, I didn't realize you meant a generic build system rather than something project-specific. In this case, I think the easiest way to do it would be to provide a runner script that is guaranteed to be present as a module, and which uses `importlib.metadata`, `runpy`, and whatever else is necessary to run it according to the inputs:
:
```json5
"module": "console_script_runner",
"args": ["pytest", ...]
```
(debugpy itself simply wraps `runpy`; the only interesting bits there are those that handle command line args like `-m` and `-c` to match Python's own behavior, which is exactly the stuff that's not relevant in this scenario)

**Comment by thejcannon** [comment]
Yeah I was hoping to avoid having to provide `importlib_metadata` on our side. But with also needing to support module/func combo I think we're entering into unavoidable territory.

I'll close.
