### ISSUE TITLE
"variablePresentation" isn't hiding special and function variables

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#961]
The variablePresentation setting only seems to hide some of the special variables and function variables.  Is there any way to hide all of them?

<img width="686" alt="image" src="https://user-images.githubusercontent.com/97484934/174409407-b67e78d6-b55b-4b5f-845b-5cad7b8053a8.png">

_Originally posted by @JeremyDalby in https://github.com/microsoft/debugpy/issues/258#issuecomment-1159284117_

**Comment by fabioz** [comment]
The problem in the example is that:

```
      "variablePresentation": {
        "all": "hide",
        "protected": "inline"
      }
```

needs to be added inside the `Hockey Team Script` python launch (the example shows it added as a separate item which is not supported).

Maybe the idea was using it as a template? (if that's the case, this is already reported at: https://github.com/microsoft/vscode-python/issues/12373).

Note that `variablePresentation` will appear underlined with yellow because it's not declared in `package.json` in `vscode-python` (but debugpy should understand it anyways).

**Comment by JeremyDalby** [comment]
Thank you!  Works exactly how I was wanting it to.  The yellow underline led me to believe it had to be outside the configuration.  
<img width="575" alt="image" src="https://user-images.githubusercontent.com/97484934/175350601-e206226c-af0f-4d28-9505-3044d980a453.png">

**Comment by ydmykr** [comment]
@fabioz  Hi, I have the similar request. What means Hockey Team Script python launch? How can I find this setting.

**Comment by JeremyDalby** [comment]
A "python launch" is a configuration used to launch (i.e., run) a Python script using the debugger in VS Code.  These configurations are defined in a file named launch.json.  You can read more about them here: [https://code.visualstudio.com/docs/python/debugging](url)

In the screenshots shown above, I just happened to be using a Python launch configuration that I named "Hockey Team Script" because it described the script I was trying to debug, but each launch configuration can be named anything you want and the name is not relevant this thread.

**Comment by ydmykr** [comment]
@JeremyDalby Thank you for your response, should my `launch.json` be set like the one in your picture? There does exist the yellow line.

**Comment by JeremyDalby** [comment]
The image I posted on June 23, 2022 shows a working launch configuration, so yes, you could set yours like that, but I assume your script has nothing to do with a hockey team, so there will at least be some different values for the "name" and "program" values.

As @fabioz explains above, "`variablePresentation` will appear underlined with yellow because it's not declared in `package.json` in `vscode-python` (but debugpy should understand it anyways)", so I believe you can just ignore the yellow line.

**Comment by ydmykr** [comment]
@JeremyDalby Thank you.
