### ISSUE TITLE
Add Option to Disable pydevd Warning

### ISSUE THREAD

**Issue by fierval** [microsoft/debugpy#990]
Issue Type: <b>Feature Request</b>

pydevd keeps warning that execution of a function was slow in a toaster dialog of VSC.
These messages keep appearing with no clear way to disable them.

Extension version: 2022.10.1
VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by judej** [comment]
Here is the solution for the problem. Please reopen if this does not work for you.

https://stackoverflow.com/questions/71695716/pydevd-warnings-in-visual-studio-code-debug-console

**Comment by Ray-Eldath** [comment]
I don't want a longer timeout, I think if a value isn't able to be computed out in 0.5s, then it's very possible that shouldn't be printed out at all (e.g., a `torch.Tensor`)

this is annoying because when you enable Inlay Values in VSCode, it'll constantly try to print `torch.Tensor` then timeout, but keeps popping up this annoying dialog.

**Comment by rchiodo** [comment]
If you set this environment variable to a really big number, the timeout error won't show:

`PYDEVD_WARN_SLOW_RESOLVE_TIMEOUT`

**Comment by rchiodo** [comment]
Oh you want it to timeout, you just don't want an error message. Sorry misunderstood. I suggest adding a discussion item for an enhancement request. Should be easy to just add another environment variable that disables the warning altogether.
