### ISSUE TITLE
Allow throwing exceptions in the debugger

### ISSUE THREAD

**Issue by dgilmanAIDENTIFIED** [microsoft/debugpy#991]
Please allow throwing exceptions in the debugger, like how the built-in pdb debugger can throw a `BdbQuit` exception when you hit q. This is helpful for many common use cases, such as debugging web servers, which have their own exception-handling logic that eats the BdbQuit and errors out the single response being debugged while allowing the entire Python interpreter to stay alive and listen for the next request.

**Comment by int19h** [comment]
Are you asking for a generic facility to inject exceptions, or specifically for `BdbQuit`? And how would you expect this facility to be triggered by the clients?

**Comment by dgilmanAIDENTIFIED** [comment]
I don't have a ton of preference on how it would be triggered. I'd be ok with `raise Exception()` in the debug console, I'm ok with a button/icon in the debugger start/stop popout, I'd be ok with something more hidden like a context menu somewhere or a keyboard shortcut.

It looks like the BdbQuit exception is not anything special, [it just subclasses from Exception](https://github.com/python/cpython/blob/main/Lib/bdb.py#L13). So for strict equivalence of the bdb/pdb feature you could just raise your own Quit exception. Maybe there is an argument for raising BdbQuit specifically for compatibility, as pdb is raising it for compatibility with bdb, and outside of the stdlib at least [pytest explicitly handles the BdbQuit exception](https://github.com/pytest-dev/pytest/blob/e54c6a1362589b32a2e63bb780192b86216ecec8/src/_pytest/runner.py#L239) to allow for users to abort in-flight unit tests. And there are probably others but a GitHub search is turning up 10000 copies of the standard library. For my own purposes it would not matter what exception you raised as long as it inherits from Exception.

**Comment by int19h** [comment]
The trick with UI is how to specify *where* the exception goes, since there may be multiple threads in general.

You can already do `raise Exception()` in the debug console, but it's not allowed to leak out of that frame (if we allowed it, then any input that raises an exception unhandled by the debuggee would immediately crash it, which is usually not what you'd expect). 

I guess we could provide some magic function that'd set some flag to indicate that the exception should be propagated before raising it. This would also take care of thread selection, since debug console operates in the context of the current selected stack frame (and thus thread). However, I'm not sure if we can allow an exception to leak from a `settrace()` hook without breaking debugging thereafter, so this might actually be more complicated.

**Comment by dgilmanAIDENTIFIED** [comment]
Digging into pdb behavior some more, looks like pdb is special-casing BdbQuit quite a bit: all exceptions are intercepted, unless you raise the special BdbQuit, and unless you raised it with the specific quit command in the debugger.

```
Python 3.10.5 (main, Jun  7 2022, 08:51:33) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> breakpoint()
--Return--
> <stdin>(1)<module>()->None
(Pdb) raise Exception()
*** Exception
(Pdb) raise BaseException()
*** BaseException
(Pdb) raise BaseException
*** BaseException
(Pdb) raise SystemExit(1)
*** SystemExit: 1
(Pdb) raise KeyboardInterrupt()
*** KeyboardInterrupt
(Pdb) import bdb
(Pdb) raise bdb.BdbQuit()
*** bdb.BdbQuit
(Pdb) q
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 94, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 156, in dispatch_return
    if self.quitting: raise BdbQuit
bdb.BdbQuit
```
