### ISSUE TITLE
Python Debugger Doesn't Stop on Breakpoint

### ISSUE THREAD

**Issue by wschin** [microsoft/debugpy#999]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

VSCode dbuuger doesn't stop at breakpoint. It never works when debugging Pytorch-related tool. Pdb command line works well. It's Python 3.9.12. It should be re-producable by running tests in TorchDynamo repo.

Extension version: 2022.10.1
VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.15.0-1014-azure
Remote OS version: Linux x64 5.15.0-1014-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz (24 x 3504)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.72GB (46.82GB free)|
|Process Argv|-n --crash-reporter-id 61209673-cca9-43ad-8d8f-dde89a091fd6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 20.211.136.127|
|OS|Linux x64 5.15.0-1014-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (24 x 2593)|
|Memory (System)|440.89GB (392.80GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 20.211.136.127|
|OS|Linux x64 5.15.0-1014-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (24 x 2593)|
|Memory (System)|440.89GB (392.80GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30535728

```

</details>

**Comment by fabioz** [comment]
Humm, from the description of https://github.com/pytorch/torchdynamo, TorchDynamo hooks into the frame evaluation API in CPython.

This will definitely compete with the debugger when frame eval mode is enabled, so, the first step would be disabling frame-eval to see if it works.

This can be done by setting an environment variable:

`PYDEVD_USE_FRAME_EVAL=0`

If it still doesn't work, this may be because TorchDynamo is doing something to the tracing (since it's replacing the way that the frame evaluation works to use its own jit, this may be expected, unless it calls the tracing itself).

In this case there's still one additional thing which can be done which is by using programmatic breakpoints (which is the same way that pdb works).

In debugpy you can do this with:

```
import debugpy
debugpy.debug_this_thread()
debugpy.breakpoint()
```

If that still doesn't work, please report back...
